apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
