# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-python

# invoke makefile with TAG variable set to specify the image tag
# e.g. TAG=example make build-image

DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs
