apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ include "notifier.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "notifier.labels" . | nindent 4 }}
