apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  labels:
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
    {{- include "inference-gateway.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inference-gateway.selectorLabels" . | nindent 4 }}
