"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
INTEL CONFIDENTIAL

Copyright (C) 2024 Intel Corporation

This software and the related documents are Intel copyrighted materials, and your use of them is governed by
the express license under which they were provided to you ("License"). Unless the License provides otherwise,
you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
without Intel's prior written permission.

This software and the related documents are provided as is, with no express or implied warranties,
other than those that are expressly stated in the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PreUrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESIGNED_URL_FIELD_NUMBER: builtins.int
    presigned_url: builtins.str
    def __init__(
        self,
        *,
        presigned_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["presigned_url", b"presigned_url"]) -> None: ...

global___PreUrlResponse = PreUrlResponse
