"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2022-2025 Intel Corporation
LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PreUrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRESIGNED_URL_FIELD_NUMBER: builtins.int
    presigned_url: builtins.str
    def __init__(
        self,
        *,
        presigned_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["presigned_url", b"presigned_url"]) -> None: ...

global___PreUrlResponse = PreUrlResponse
