"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2022-2025 Intel Corporation
LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OrganizationStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    status: builtins.str
    organization_id: builtins.str
    created_by: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        organization_id: builtins.str = ...,
        created_by: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_by", b"created_by", "organization_id", b"organization_id", "status", b"status"]) -> None: ...

global___OrganizationStatusRequest = OrganizationStatusRequest

@typing.final
class OrganizationStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    id: builtins.str
    status: builtins.str
    organization_id: builtins.str
    created_by: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        status: builtins.str = ...,
        organization_id: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        created_by: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "created_by", b"created_by", "id", b"id", "organization_id", b"organization_id", "status", b"status"]) -> None: ...

global___OrganizationStatusResponse = OrganizationStatusResponse

@typing.final
class ListOrganizationStatusesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUSES_FIELD_NUMBER: builtins.int
    @property
    def statuses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OrganizationStatusResponse]: ...
    def __init__(
        self,
        *,
        statuses: collections.abc.Iterable[global___OrganizationStatusResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["statuses", b"statuses"]) -> None: ...

global___ListOrganizationStatusesResponse = ListOrganizationStatusesResponse
