# INTEL CONFIDENTIAL
# 
# Copyright (C) 2025 Intel Corporation
# 
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by
# the express license under which they were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
# without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_settings.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13user_settings.proto\x12\ruser_settings\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n\x0cUserSettings\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x03 \x01(\t\x12\x12\n\nproject_id\x18\x04 \x01(\t\x12\x10\n\x08settings\x18\x05 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x07 \x01(\t\x12/\n\x0bmodified_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bmodified_by\x18\t \x01(\t\")\n\x13UserSettingsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"\'\n\x14UserSettingsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x13UserSettingsPayload\x12\x10\n\x08settings\x18\x01 \x01(\t\"e\n\x19UserSettingsCreateRequest\x12\x34\n\x08settings\x18\x01 \x01(\x0b\x32\".user_settings.UserSettingsPayload\x12\x12\n\nproject_id\x18\x02 \x01(\t2\xff\x01\n\x13UserSettingsService\x12\x80\x01\n\x06\x63reate\x12(.user_settings.UserSettingsCreateRequest\x1a#.user_settings.UserSettingsResponse\"\'\x82\xd3\xe4\x93\x02!\"\x15/api/v1/user_settings:\x08settings\x12\x65\n\x03get\x12\".user_settings.UserSettingsRequest\x1a\x1b.user_settings.UserSettings\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/user_settingsB\"Z geti.com/account_service_grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z geti.com/account_service_grpc/pb'
  _globals['_USERSETTINGSSERVICE'].methods_by_name['create']._options = None
  _globals['_USERSETTINGSSERVICE'].methods_by_name['create']._serialized_options = b'\202\323\344\223\002!\"\025/api/v1/user_settings:\010settings'
  _globals['_USERSETTINGSSERVICE'].methods_by_name['get']._options = None
  _globals['_USERSETTINGSSERVICE'].methods_by_name['get']._serialized_options = b'\202\323\344\223\002\027\022\025/api/v1/user_settings'
  _globals['_USERSETTINGS']._serialized_start=102
  _globals['_USERSETTINGS']._serialized_end=346
  _globals['_USERSETTINGSREQUEST']._serialized_start=348
  _globals['_USERSETTINGSREQUEST']._serialized_end=389
  _globals['_USERSETTINGSRESPONSE']._serialized_start=391
  _globals['_USERSETTINGSRESPONSE']._serialized_end=430
  _globals['_USERSETTINGSPAYLOAD']._serialized_start=432
  _globals['_USERSETTINGSPAYLOAD']._serialized_end=471
  _globals['_USERSETTINGSCREATEREQUEST']._serialized_start=473
  _globals['_USERSETTINGSCREATEREQUEST']._serialized_end=574
  _globals['_USERSETTINGSSERVICE']._serialized_start=577
  _globals['_USERSETTINGSSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
