name: geti-components
apiVersion: v2
type: application
description: Chart that contains all the components of Geti
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.11.0"

dependencies:
  - name: migration-job
    version: 0.0.1
    repository: "file://../../interactive_ai/migration_job/chart"
    condition: enabled.migration_job
  - name: auto-train-controller
    version: 0.0.2
    repository: "file://../../interactive_ai/services/auto_train/chart"
    condition: enabled.auto_train
  - name: dataset-ie
    version: 0.0.11
    repository: "file://../../interactive_ai/services/dataset_ie/chart"
    condition: enabled.dataset_ie
  - name: director
    version: 0.0.8
    repository: "file://../../interactive_ai/services/director/chart"
    condition: enabled.director
  - name: inference-gateway
    version: 0.0.1
    repository: "file://../../interactive_ai/services/inference_gateway/chart"
    condition: enabled.inference_gateway
  - name: jobs
    version: 0.0.1
    repository: "file://../../interactive_ai/services/jobs/chart"
    condition: enabled.jobs
  - name: media-ms
    version: 0.0.8
    repository: "file://../../interactive_ai/services/media/chart"
    condition: enabled.media
  - name: mlflow-geti-store
    version: 0.0.1
    repository: "file://../../interactive_ai/services/mlflow_geti_store/chart"
    condition: enabled.mlflow_geti_store
  - name: modelregistration
    version: 0.0.3
    repository: "file://../../interactive_ai/services/model_registration/chart"
    condition: enabled.model_registration
  - name: project-ie
    version: 0.0.10
    repository: "file://../../interactive_ai/services/project_ie/chart"
    condition: enabled.project_ie
  - name: resource
    version: 0.0.12
    repository: "file://../../interactive_ai/services/resource/chart"
    condition: enabled.resource
  - name: visual-prompt
    version: 0.0.1
    repository: "file://../../interactive_ai/services/visual_prompt/chart"
    condition: enabled.visual_prompt
  - name: account-service
    version: 0.0.2
    repository: "file://../../platform/services/account/chart"
    condition: enabled.account
  - name: auth-proxy
    version: 0.1.0
    repository: "file://../../platform/services/auth_proxy/chart"
    condition: enabled.auth_proxy
  - name: credit-system
    version: 0.1.0
    repository: "file://../../platform/services/credit/chart"
    condition: enabled.credit
  - name: initial-user
    version: 0.0.1
    repository: "file://../../platform/services/initial_user/chart"
    condition: enabled.initial_user
  - name: notifier
    version: 0.0.1
    repository: "file://../../platform/services/notifier/chart"
    condition: enabled.notifier
  - name: observability
    version: 0.0.1
    repository: "file://../../platform/services/observability/chart"
    condition: enabled.observability
  - name: onboarding-service
    version: 0.0.1
    repository: "file://../../platform/services/onboarding/chart"
    condition: enabled.onboarding
  - name: platform-cleaner
    version: 0.0.4
    repository: "file://../../platform/services/platform_cleaner/chart"
    condition: enabled.platform_cleaner
  - name: user-directory
    version: 0.0.1
    repository: "file://../../platform/services/user_directory/chart"
    condition: enabled.user_directory
  - name: weights_uploader
    version: 0.0.1
    repository: "file://../../platform/services/weights_uploader/chart"
    condition: enabled.weights_uploader
  - name: web
    version: 0.0.5
    repository: "file://../../web_ui/chart"
    condition: enabled.web_ui
  - name: configuration
    version: 0.0.1
    condition: enabled.configuration
  - name: jobs-execution-namespace
    version: v0.1.15
    condition: enabled.jobs_execution_namespace
  - name: modelmesh-serving
    version: 0.1.0
    condition: enabled.modelmesh_serving
  - name: opa-bundle
    version: 0.0.1
    condition: enabled.opa_bundle
  - name: telemetry-compression
    version: 0.0.1
    condition: enabled.telemetry_compression
