// INTEL CONFIDENTIAL
//
// Copyright (C) 2024 Intel Corporation
//
// This software and the related documents are Intel copyrighted materials, and your use of them is governed by
// the express license under which they were provided to you ("License"). Unless the License provides otherwise,
// you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
// without Intel's prior written permission.
//
// This software and the related documents are provided as is, with no express or implied warranties,
// other than those that are expressly stated in the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: organization.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country             string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Location            string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Type                string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CellId              string                 `protobuf:"bytes,6,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt           *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy           string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAt          *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ModifiedBy          string                 `protobuf:"bytes,11,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	RequestAccessReason string                 `protobuf:"bytes,12,opt,name=request_access_reason,json=requestAccessReason,proto3" json:"request_access_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrganizationData) Reset() {
	*x = OrganizationData{}
	mi := &file_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationData) ProtoMessage() {}

func (x *OrganizationData) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationData.ProtoReflect.Descriptor instead.
func (*OrganizationData) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationData) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *OrganizationData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *OrganizationData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrganizationData) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *OrganizationData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrganizationData) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrganizationData) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *OrganizationData) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *OrganizationData) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *OrganizationData) GetRequestAccessReason() string {
	if x != nil {
		return x.RequestAccessReason
	}
	return ""
}

type OrganizationDataWithAdmins struct {
	state               protoimpl.MessageState                        `protogen:"open.v1"`
	Id                  string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country             string                                        `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Location            string                                        `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Type                string                                        `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CellId              string                                        `protobuf:"bytes,6,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Status              string                                        `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt           *timestamp.Timestamp                          `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy           string                                        `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAt          *timestamp.Timestamp                          `protobuf:"bytes,10,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ModifiedBy          string                                        `protobuf:"bytes,11,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	RequestAccessReason string                                        `protobuf:"bytes,13,opt,name=request_access_reason,json=requestAccessReason,proto3" json:"request_access_reason,omitempty"`
	Admins              []*OrganizationDataWithAdmins_AdminSimpleData `protobuf:"bytes,12,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrganizationDataWithAdmins) Reset() {
	*x = OrganizationDataWithAdmins{}
	mi := &file_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationDataWithAdmins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationDataWithAdmins) ProtoMessage() {}

func (x *OrganizationDataWithAdmins) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationDataWithAdmins.ProtoReflect.Descriptor instead.
func (*OrganizationDataWithAdmins) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizationDataWithAdmins) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrganizationDataWithAdmins) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *OrganizationDataWithAdmins) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetRequestAccessReason() string {
	if x != nil {
		return x.RequestAccessReason
	}
	return ""
}

func (x *OrganizationDataWithAdmins) GetAdmins() []*OrganizationDataWithAdmins_AdminSimpleData {
	if x != nil {
		return x.Admins
	}
	return nil
}

type OrganizationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationIdRequest) Reset() {
	*x = OrganizationIdRequest{}
	mi := &file_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationIdRequest) ProtoMessage() {}

func (x *OrganizationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationIdRequest.ProtoReflect.Descriptor instead.
func (*OrganizationIdRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

func (x *OrganizationIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOrganizationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,17,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country             string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Location            string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Type                string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CellId              string                 `protobuf:"bytes,5,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAtFrom       *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`
	CreatedAtTo         *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`
	CreatedBy           string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAtFrom      *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=modified_at_from,json=modifiedAtFrom,proto3" json:"modified_at_from,omitempty"`
	ModifiedAtTo        *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=modified_at_to,json=modifiedAtTo,proto3" json:"modified_at_to,omitempty"`
	ModifiedBy          string                 `protobuf:"bytes,12,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	RequestAccessReason string                 `protobuf:"bytes,18,opt,name=request_access_reason,json=requestAccessReason,proto3" json:"request_access_reason,omitempty"`
	Skip                int32                  `protobuf:"varint,13,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit               int32                  `protobuf:"varint,14,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy              string                 `protobuf:"bytes,15,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                      //attribute name
	SortDirection       string                 `protobuf:"bytes,16,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` //asc/desc
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindOrganizationRequest) Reset() {
	*x = FindOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrganizationRequest) ProtoMessage() {}

func (x *FindOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrganizationRequest.ProtoReflect.Descriptor instead.
func (*FindOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{3}
}

func (x *FindOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindOrganizationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FindOrganizationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *FindOrganizationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FindOrganizationRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *FindOrganizationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindOrganizationRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *FindOrganizationRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

func (x *FindOrganizationRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FindOrganizationRequest) GetModifiedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtFrom
	}
	return nil
}

func (x *FindOrganizationRequest) GetModifiedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtTo
	}
	return nil
}

func (x *FindOrganizationRequest) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *FindOrganizationRequest) GetRequestAccessReason() string {
	if x != nil {
		return x.RequestAccessReason
	}
	return ""
}

func (x *FindOrganizationRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *FindOrganizationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindOrganizationRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *FindOrganizationRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

type ListOrganizationsResponse struct {
	state             protoimpl.MessageState              `protogen:"open.v1"`
	Organizations     []*OrganizationDataWithAdmins       `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	TotalCount        int32                               `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalMatchedCount int32                               `protobuf:"varint,3,opt,name=total_matched_count,json=totalMatchedCount,proto3" json:"total_matched_count,omitempty"`
	NextPage          *ListOrganizationsResponse_NextPage `protobuf:"bytes,4,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*OrganizationDataWithAdmins {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrganizationsResponse) GetTotalMatchedCount() int32 {
	if x != nil {
		return x.TotalMatchedCount
	}
	return 0
}

func (x *ListOrganizationsResponse) GetNextPage() *ListOrganizationsResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

type OrganizationLogoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*OrganizationLogoRequest_UserData
	//	*OrganizationLogoRequest_Photo
	Request       isOrganizationLogoRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationLogoRequest) Reset() {
	*x = OrganizationLogoRequest{}
	mi := &file_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationLogoRequest) ProtoMessage() {}

func (x *OrganizationLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationLogoRequest.ProtoReflect.Descriptor instead.
func (*OrganizationLogoRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationLogoRequest) GetRequest() isOrganizationLogoRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *OrganizationLogoRequest) GetUserData() *OrganizationIdRequest {
	if x != nil {
		if x, ok := x.Request.(*OrganizationLogoRequest_UserData); ok {
			return x.UserData
		}
	}
	return nil
}

func (x *OrganizationLogoRequest) GetPhoto() []byte {
	if x != nil {
		if x, ok := x.Request.(*OrganizationLogoRequest_Photo); ok {
			return x.Photo
		}
	}
	return nil
}

type isOrganizationLogoRequest_Request interface {
	isOrganizationLogoRequest_Request()
}

type OrganizationLogoRequest_UserData struct {
	UserData *OrganizationIdRequest `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3,oneof"`
}

type OrganizationLogoRequest_Photo struct {
	Photo []byte `protobuf:"bytes,2,opt,name=photo,proto3,oneof"`
}

func (*OrganizationLogoRequest_UserData) isOrganizationLogoRequest_Request() {}

func (*OrganizationLogoRequest_Photo) isOrganizationLogoRequest_Request() {}

type OrganizationInvitiationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationData *OrganizationData      `protobuf:"bytes,1,opt,name=organizationData,proto3" json:"organizationData,omitempty"`
	AdminData        *UserData              `protobuf:"bytes,2,opt,name=adminData,proto3" json:"adminData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrganizationInvitiationRequest) Reset() {
	*x = OrganizationInvitiationRequest{}
	mi := &file_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationInvitiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationInvitiationRequest) ProtoMessage() {}

func (x *OrganizationInvitiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationInvitiationRequest.ProtoReflect.Descriptor instead.
func (*OrganizationInvitiationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{6}
}

func (x *OrganizationInvitiationRequest) GetOrganizationData() *OrganizationData {
	if x != nil {
		return x.OrganizationData
	}
	return nil
}

func (x *OrganizationInvitiationRequest) GetAdminData() *UserData {
	if x != nil {
		return x.AdminData
	}
	return nil
}

type OrganizationDataWithAdmins_AdminSimpleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationDataWithAdmins_AdminSimpleData) Reset() {
	*x = OrganizationDataWithAdmins_AdminSimpleData{}
	mi := &file_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationDataWithAdmins_AdminSimpleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationDataWithAdmins_AdminSimpleData) ProtoMessage() {}

func (x *OrganizationDataWithAdmins_AdminSimpleData) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationDataWithAdmins_AdminSimpleData.ProtoReflect.Descriptor instead.
func (*OrganizationDataWithAdmins_AdminSimpleData) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OrganizationDataWithAdmins_AdminSimpleData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *OrganizationDataWithAdmins_AdminSimpleData) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *OrganizationDataWithAdmins_AdminSimpleData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListOrganizationsResponse_NextPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse_NextPage) Reset() {
	*x = ListOrganizationsResponse_NextPage{}
	mi := &file_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse_NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse_NextPage) ProtoMessage() {}

func (x *ListOrganizationsResponse_NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse_NextPage.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse_NextPage) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListOrganizationsResponse_NextPage) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListOrganizationsResponse_NextPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_organization_proto protoreflect.FileDescriptor

const file_organization_proto_rawDesc = "" +
	"\n" +
	"\x12organization.proto\x12\forganization\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\x11user_common.proto\"\x9d\x03\n" +
	"\x10OrganizationData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x17\n" +
	"\acell_id\x18\x06 \x01(\tR\x06cellId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12;\n" +
	"\vmodified_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1f\n" +
	"\vmodified_by\x18\v \x01(\tR\n" +
	"modifiedBy\x122\n" +
	"\x15request_access_reason\x18\f \x01(\tR\x13requestAccessReason\"\xde\x04\n" +
	"\x1aOrganizationDataWithAdmins\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x17\n" +
	"\acell_id\x18\x06 \x01(\tR\x06cellId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12;\n" +
	"\vmodified_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1f\n" +
	"\vmodified_by\x18\v \x01(\tR\n" +
	"modifiedBy\x122\n" +
	"\x15request_access_reason\x18\r \x01(\tR\x13requestAccessReason\x12P\n" +
	"\x06admins\x18\f \x03(\v28.organization.OrganizationDataWithAdmins.AdminSimpleDataR\x06admins\x1ac\n" +
	"\x0fAdminSimpleData\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"'\n" +
	"\x15OrganizationIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x05\n" +
	"\x17FindOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x11 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x17\n" +
	"\acell_id\x18\x05 \x01(\tR\x06cellId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12B\n" +
	"\x0fcreated_at_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedAtFrom\x12>\n" +
	"\rcreated_at_to\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedAtTo\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12D\n" +
	"\x10modified_at_from\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0emodifiedAtFrom\x12@\n" +
	"\x0emodified_at_to\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedAtTo\x12\x1f\n" +
	"\vmodified_by\x18\f \x01(\tR\n" +
	"modifiedBy\x122\n" +
	"\x15request_access_reason\x18\x12 \x01(\tR\x13requestAccessReason\x12\x12\n" +
	"\x04skip\x18\r \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x0e \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x0f \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\x10 \x01(\tR\rsortDirection\"\xd4\x02\n" +
	"\x19ListOrganizationsResponse\x12N\n" +
	"\rorganizations\x18\x01 \x03(\v2(.organization.OrganizationDataWithAdminsR\rorganizations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12.\n" +
	"\x13total_matched_count\x18\x03 \x01(\x05R\x11totalMatchedCount\x12R\n" +
	"\tnext_page\x18\x04 \x01(\v20.organization.ListOrganizationsResponse.NextPageH\x00R\bnextPage\x88\x01\x01\x1a4\n" +
	"\bNextPage\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_next_page\"\x80\x01\n" +
	"\x17OrganizationLogoRequest\x12B\n" +
	"\tuser_data\x18\x01 \x01(\v2#.organization.OrganizationIdRequestH\x00R\buserData\x12\x16\n" +
	"\x05photo\x18\x02 \x01(\fH\x00R\x05photoB\t\n" +
	"\arequest\"\xa1\x01\n" +
	"\x1eOrganizationInvitiationRequest\x12J\n" +
	"\x10organizationData\x18\x01 \x01(\v2\x1e.organization.OrganizationDataR\x10organizationData\x123\n" +
	"\tadminData\x18\x02 \x01(\v2\x15.user_common.UserDataR\tadminData2\x92\t\n" +
	"\fOrganization\x12j\n" +
	"\x06create\x12\x1e.organization.OrganizationData\x1a\x1e.organization.OrganizationData\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/organizations\x12o\n" +
	"\x06modify\x12\x1e.organization.OrganizationData\x1a\x1e.organization.OrganizationData\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/v1/organizations/{id}\x12~\n" +
	"\tget_by_id\x12#.organization.OrganizationIdRequest\x1a(.organization.OrganizationDataWithAdmins\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/organizations/{id}\x12u\n" +
	"\x04find\x12%.organization.FindOrganizationRequest\x1a'.organization.ListOrganizationsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/organizations\x12i\n" +
	"\x06delete\x12#.organization.OrganizationIdRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/organizations/{id}\x12N\n" +
	"\tadd_photo\x12%.organization.OrganizationLogoRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12v\n" +
	"\fdelete_photo\x12#.organization.OrganizationIdRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#*!/api/v1/organizations/{id}/photos\x12s\n" +
	"\tget_photo\x12#.organization.OrganizationIdRequest\x1a\x16.common.PreUrlResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/organizations/{id}/photos\x12\x85\x01\n" +
	"\x0fsend_invitation\x12,.organization.OrganizationInvitiationRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/organizations/invitations\x12~\n" +
	"\x16send_invitation_simple\x12,.organization.OrganizationInvitiationRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/invitationsB\"Z geti.com/account_service_grpc/pbb\x06proto3"

var (
	file_organization_proto_rawDescOnce sync.Once
	file_organization_proto_rawDescData []byte
)

func file_organization_proto_rawDescGZIP() []byte {
	file_organization_proto_rawDescOnce.Do(func() {
		file_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)))
	})
	return file_organization_proto_rawDescData
}

var file_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_organization_proto_goTypes = []any{
	(*OrganizationData)(nil),                           // 0: organization.OrganizationData
	(*OrganizationDataWithAdmins)(nil),                 // 1: organization.OrganizationDataWithAdmins
	(*OrganizationIdRequest)(nil),                      // 2: organization.OrganizationIdRequest
	(*FindOrganizationRequest)(nil),                    // 3: organization.FindOrganizationRequest
	(*ListOrganizationsResponse)(nil),                  // 4: organization.ListOrganizationsResponse
	(*OrganizationLogoRequest)(nil),                    // 5: organization.OrganizationLogoRequest
	(*OrganizationInvitiationRequest)(nil),             // 6: organization.OrganizationInvitiationRequest
	(*OrganizationDataWithAdmins_AdminSimpleData)(nil), // 7: organization.OrganizationDataWithAdmins.AdminSimpleData
	(*ListOrganizationsResponse_NextPage)(nil),         // 8: organization.ListOrganizationsResponse.NextPage
	(*timestamp.Timestamp)(nil),                        // 9: google.protobuf.Timestamp
	(*UserData)(nil),                                   // 10: user_common.UserData
	(*empty.Empty)(nil),                                // 11: google.protobuf.Empty
	(*PreUrlResponse)(nil),                             // 12: common.PreUrlResponse
}
var file_organization_proto_depIdxs = []int32{
	9,  // 0: organization.OrganizationData.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: organization.OrganizationData.modified_at:type_name -> google.protobuf.Timestamp
	9,  // 2: organization.OrganizationDataWithAdmins.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: organization.OrganizationDataWithAdmins.modified_at:type_name -> google.protobuf.Timestamp
	7,  // 4: organization.OrganizationDataWithAdmins.admins:type_name -> organization.OrganizationDataWithAdmins.AdminSimpleData
	9,  // 5: organization.FindOrganizationRequest.created_at_from:type_name -> google.protobuf.Timestamp
	9,  // 6: organization.FindOrganizationRequest.created_at_to:type_name -> google.protobuf.Timestamp
	9,  // 7: organization.FindOrganizationRequest.modified_at_from:type_name -> google.protobuf.Timestamp
	9,  // 8: organization.FindOrganizationRequest.modified_at_to:type_name -> google.protobuf.Timestamp
	1,  // 9: organization.ListOrganizationsResponse.organizations:type_name -> organization.OrganizationDataWithAdmins
	8,  // 10: organization.ListOrganizationsResponse.next_page:type_name -> organization.ListOrganizationsResponse.NextPage
	2,  // 11: organization.OrganizationLogoRequest.user_data:type_name -> organization.OrganizationIdRequest
	0,  // 12: organization.OrganizationInvitiationRequest.organizationData:type_name -> organization.OrganizationData
	10, // 13: organization.OrganizationInvitiationRequest.adminData:type_name -> user_common.UserData
	0,  // 14: organization.Organization.create:input_type -> organization.OrganizationData
	0,  // 15: organization.Organization.modify:input_type -> organization.OrganizationData
	2,  // 16: organization.Organization.get_by_id:input_type -> organization.OrganizationIdRequest
	3,  // 17: organization.Organization.find:input_type -> organization.FindOrganizationRequest
	2,  // 18: organization.Organization.delete:input_type -> organization.OrganizationIdRequest
	5,  // 19: organization.Organization.add_photo:input_type -> organization.OrganizationLogoRequest
	2,  // 20: organization.Organization.delete_photo:input_type -> organization.OrganizationIdRequest
	2,  // 21: organization.Organization.get_photo:input_type -> organization.OrganizationIdRequest
	6,  // 22: organization.Organization.send_invitation:input_type -> organization.OrganizationInvitiationRequest
	6,  // 23: organization.Organization.send_invitation_simple:input_type -> organization.OrganizationInvitiationRequest
	0,  // 24: organization.Organization.create:output_type -> organization.OrganizationData
	0,  // 25: organization.Organization.modify:output_type -> organization.OrganizationData
	1,  // 26: organization.Organization.get_by_id:output_type -> organization.OrganizationDataWithAdmins
	4,  // 27: organization.Organization.find:output_type -> organization.ListOrganizationsResponse
	11, // 28: organization.Organization.delete:output_type -> google.protobuf.Empty
	11, // 29: organization.Organization.add_photo:output_type -> google.protobuf.Empty
	11, // 30: organization.Organization.delete_photo:output_type -> google.protobuf.Empty
	12, // 31: organization.Organization.get_photo:output_type -> common.PreUrlResponse
	11, // 32: organization.Organization.send_invitation:output_type -> google.protobuf.Empty
	11, // 33: organization.Organization.send_invitation_simple:output_type -> google.protobuf.Empty
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_organization_proto_init() }
func file_organization_proto_init() {
	if File_organization_proto != nil {
		return
	}
	file_common_proto_init()
	file_user_common_proto_init()
	file_organization_proto_msgTypes[4].OneofWrappers = []any{}
	file_organization_proto_msgTypes[5].OneofWrappers = []any{
		(*OrganizationLogoRequest_UserData)(nil),
		(*OrganizationLogoRequest_Photo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_proto_goTypes,
		DependencyIndexes: file_organization_proto_depIdxs,
		MessageInfos:      file_organization_proto_msgTypes,
	}.Build()
	File_organization_proto = out.File
	file_organization_proto_goTypes = nil
	file_organization_proto_depIdxs = nil
}
