// INTEL CONFIDENTIAL
//
// Copyright (C) 2024 Intel Corporation
//
// This software and the related documents are Intel copyrighted materials, and your use of them is governed by
// the express license under which they were provided to you ("License"). Unless the License provides otherwise,
// you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
// without Intel's prior written permission.
//
// This software and the related documents are provided as is, with no express or implied warranties,
// other than those that are expressly stated in the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: user.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserIdRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UserExtIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExtIdRequest) Reset() {
	*x = UserExtIdRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExtIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExtIdRequest) ProtoMessage() {}

func (x *UserExtIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExtIdRequest.ProtoReflect.Descriptor instead.
func (*UserExtIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserExtIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindUserRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	FirstName               string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName              string                 `protobuf:"bytes,2,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Email                   string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ExternalId              string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Country                 string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Status                  string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LastSuccessfulLoginFrom *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_successful_login_from,json=lastSuccessfulLoginFrom,proto3" json:"last_successful_login_from,omitempty"`
	LastSuccessfulLoginTo   *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=last_successful_login_to,json=lastSuccessfulLoginTo,proto3" json:"last_successful_login_to,omitempty"`
	Role                    string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	ResourceType            []string               `protobuf:"bytes,10,rep,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId              string                 `protobuf:"bytes,11,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	WorkspaceId             string                 `protobuf:"bytes,12,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	OrganizationId          string                 `protobuf:"bytes,13,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAtFrom           *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`
	CreatedAtTo             *timestamp.Timestamp   `protobuf:"bytes,15,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`
	CreatedBy               string                 `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAtFrom          *timestamp.Timestamp   `protobuf:"bytes,17,opt,name=modified_at_from,json=modifiedAtFrom,proto3" json:"modified_at_from,omitempty"`
	ModifiedAtTo            *timestamp.Timestamp   `protobuf:"bytes,18,opt,name=modified_at_to,json=modifiedAtTo,proto3" json:"modified_at_to,omitempty"`
	ModifiedBy              string                 `protobuf:"bytes,19,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	Skip                    int32                  `protobuf:"varint,20,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                   int32                  `protobuf:"varint,21,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy                  string                 `protobuf:"bytes,22,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                      //attribute name
	SortDirection           string                 `protobuf:"bytes,23,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` //asc/desc
	Name                    string                 `protobuf:"bytes,24,opt,name=name,proto3" json:"name,omitempty"`                                        // user to search for first name OR second name OR email
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FindUserRequest) Reset() {
	*x = FindUserRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserRequest) ProtoMessage() {}

func (x *FindUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserRequest.ProtoReflect.Descriptor instead.
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *FindUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *FindUserRequest) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *FindUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FindUserRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FindUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindUserRequest) GetLastSuccessfulLoginFrom() *timestamp.Timestamp {
	if x != nil {
		return x.LastSuccessfulLoginFrom
	}
	return nil
}

func (x *FindUserRequest) GetLastSuccessfulLoginTo() *timestamp.Timestamp {
	if x != nil {
		return x.LastSuccessfulLoginTo
	}
	return nil
}

func (x *FindUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *FindUserRequest) GetResourceType() []string {
	if x != nil {
		return x.ResourceType
	}
	return nil
}

func (x *FindUserRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *FindUserRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *FindUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *FindUserRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *FindUserRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

func (x *FindUserRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FindUserRequest) GetModifiedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtFrom
	}
	return nil
}

func (x *FindUserRequest) GetModifiedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtTo
	}
	return nil
}

func (x *FindUserRequest) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *FindUserRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *FindUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindUserRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *FindUserRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *FindUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListUsersResponse struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Users             []*UserData                 `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount        int32                       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalMatchedCount int32                       `protobuf:"varint,3,opt,name=total_matched_count,json=totalMatchedCount,proto3" json:"total_matched_count,omitempty"`
	NextPage          *ListUsersResponse_NextPage `protobuf:"bytes,4,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetUsers() []*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResponse) GetTotalMatchedCount() int32 {
	if x != nil {
		return x.TotalMatchedCount
	}
	return 0
}

func (x *ListUsersResponse) GetNextPage() *ListUsersResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

type UserPhotoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*UserPhotoRequest_UserData
	//	*UserPhotoRequest_Photo
	Request       isUserPhotoRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPhotoRequest) Reset() {
	*x = UserPhotoRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPhotoRequest) ProtoMessage() {}

func (x *UserPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPhotoRequest.ProtoReflect.Descriptor instead.
func (*UserPhotoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserPhotoRequest) GetRequest() isUserPhotoRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UserPhotoRequest) GetUserData() *UserIdRequest {
	if x != nil {
		if x, ok := x.Request.(*UserPhotoRequest_UserData); ok {
			return x.UserData
		}
	}
	return nil
}

func (x *UserPhotoRequest) GetPhoto() []byte {
	if x != nil {
		if x, ok := x.Request.(*UserPhotoRequest_Photo); ok {
			return x.Photo
		}
	}
	return nil
}

type isUserPhotoRequest_Request interface {
	isUserPhotoRequest_Request()
}

type UserPhotoRequest_UserData struct {
	UserData *UserIdRequest `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3,oneof"`
}

type UserPhotoRequest_Photo struct {
	Photo []byte `protobuf:"bytes,2,opt,name=photo,proto3,oneof"`
}

func (*UserPhotoRequest_UserData) isUserPhotoRequest_Request() {}

func (*UserPhotoRequest_Photo) isUserPhotoRequest_Request() {}

type UserRolesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Roles          []*UserRoleOperation   `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserRolesRequest) Reset() {
	*x = UserRolesRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolesRequest) ProtoMessage() {}

func (x *UserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolesRequest.ProtoReflect.Descriptor instead.
func (*UserRolesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserRolesRequest) GetRoles() []*UserRoleOperation {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRolesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UserGetRolesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ResourceType   string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserGetRolesRequest) Reset() {
	*x = UserGetRolesRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetRolesRequest) ProtoMessage() {}

func (x *UserGetRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetRolesRequest.ProtoReflect.Descriptor instead.
func (*UserGetRolesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserGetRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserGetRolesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserGetRolesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type UserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*UserRole            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRolesResponse) Reset() {
	*x = UserRolesResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolesResponse) ProtoMessage() {}

func (x *UserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolesResponse.ProtoReflect.Descriptor instead.
func (*UserRolesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserRolesResponse) GetRoles() []*UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type OrganizationExtended struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrganizationName      string                 `protobuf:"bytes,1,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	UserStatus            string                 `protobuf:"bytes,2,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	OrganizationStatus    string                 `protobuf:"bytes,3,opt,name=organization_status,json=organizationStatus,proto3" json:"organization_status,omitempty"`
	OrganizationId        string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationCreatedAt *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=organization_created_at,json=organizationCreatedAt,proto3" json:"organization_created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrganizationExtended) Reset() {
	*x = OrganizationExtended{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationExtended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationExtended) ProtoMessage() {}

func (x *OrganizationExtended) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationExtended.ProtoReflect.Descriptor instead.
func (*OrganizationExtended) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *OrganizationExtended) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *OrganizationExtended) GetUserStatus() string {
	if x != nil {
		return x.UserStatus
	}
	return ""
}

func (x *OrganizationExtended) GetOrganizationStatus() string {
	if x != nil {
		return x.OrganizationStatus
	}
	return ""
}

func (x *OrganizationExtended) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationExtended) GetOrganizationCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.OrganizationCreatedAt
	}
	return nil
}

type UserProfileData struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Status             *string                 `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	OrganizationId     *string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	OrganizationStatus *string                 `protobuf:"bytes,3,opt,name=organization_status,json=organizationStatus,proto3,oneof" json:"organization_status,omitempty"`
	Organizations      []*OrganizationExtended `protobuf:"bytes,8,rep,name=organizations,proto3" json:"organizations,omitempty"`
	TelemetryConsent   *string                 `protobuf:"bytes,4,opt,name=telemetry_consent,json=telemetryConsent,proto3,oneof" json:"telemetry_consent,omitempty"`
	TelemetryConsentAt *timestamp.Timestamp    `protobuf:"bytes,5,opt,name=telemetry_consent_at,json=telemetryConsentAt,proto3" json:"telemetry_consent_at,omitempty"`
	UserConsent        *string                 `protobuf:"bytes,6,opt,name=user_consent,json=userConsent,proto3,oneof" json:"user_consent,omitempty"`
	UserConsentAt      *timestamp.Timestamp    `protobuf:"bytes,7,opt,name=user_consent_at,json=userConsentAt,proto3" json:"user_consent_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserProfileData) Reset() {
	*x = UserProfileData{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileData) ProtoMessage() {}

func (x *UserProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileData.ProtoReflect.Descriptor instead.
func (*UserProfileData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserProfileData) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UserProfileData) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *UserProfileData) GetOrganizationStatus() string {
	if x != nil && x.OrganizationStatus != nil {
		return *x.OrganizationStatus
	}
	return ""
}

func (x *UserProfileData) GetOrganizations() []*OrganizationExtended {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *UserProfileData) GetTelemetryConsent() string {
	if x != nil && x.TelemetryConsent != nil {
		return *x.TelemetryConsent
	}
	return ""
}

func (x *UserProfileData) GetTelemetryConsentAt() *timestamp.Timestamp {
	if x != nil {
		return x.TelemetryConsentAt
	}
	return nil
}

func (x *UserProfileData) GetUserConsent() string {
	if x != nil && x.UserConsent != nil {
		return *x.UserConsent
	}
	return ""
}

func (x *UserProfileData) GetUserConsentAt() *timestamp.Timestamp {
	if x != nil {
		return x.UserConsentAt
	}
	return nil
}

type ActiveUserData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName              string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName             string                 `protobuf:"bytes,3,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Email                  string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Status                 string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OrganizationId         string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationStatus     string                 `protobuf:"bytes,7,opt,name=organization_status,json=organizationStatus,proto3" json:"organization_status,omitempty"`
	Roles                  []*UserRole            `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"`
	LastSuccessfulLogin    *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=last_successful_login,json=lastSuccessfulLogin,proto3" json:"last_successful_login,omitempty"`
	CurrentSuccessfulLogin *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=current_successful_login,json=currentSuccessfulLogin,proto3" json:"current_successful_login,omitempty"`
	TelemetryConsent       *string                `protobuf:"bytes,11,opt,name=telemetry_consent,json=telemetryConsent,proto3,oneof" json:"telemetry_consent,omitempty"`
	UserConsent            *string                `protobuf:"bytes,12,opt,name=user_consent,json=userConsent,proto3,oneof" json:"user_consent,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ActiveUserData) Reset() {
	*x = ActiveUserData{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveUserData) ProtoMessage() {}

func (x *ActiveUserData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveUserData.ProtoReflect.Descriptor instead.
func (*ActiveUserData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *ActiveUserData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActiveUserData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ActiveUserData) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *ActiveUserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActiveUserData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActiveUserData) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ActiveUserData) GetOrganizationStatus() string {
	if x != nil {
		return x.OrganizationStatus
	}
	return ""
}

func (x *ActiveUserData) GetRoles() []*UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ActiveUserData) GetLastSuccessfulLogin() *timestamp.Timestamp {
	if x != nil {
		return x.LastSuccessfulLogin
	}
	return nil
}

func (x *ActiveUserData) GetCurrentSuccessfulLogin() *timestamp.Timestamp {
	if x != nil {
		return x.CurrentSuccessfulLogin
	}
	return nil
}

func (x *ActiveUserData) GetTelemetryConsent() string {
	if x != nil && x.TelemetryConsent != nil {
		return *x.TelemetryConsent
	}
	return ""
}

func (x *ActiveUserData) GetUserConsent() string {
	if x != nil && x.UserConsent != nil {
		return *x.UserConsent
	}
	return ""
}

type UserInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInvitationResponse) Reset() {
	*x = UserInvitationResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInvitationResponse) ProtoMessage() {}

func (x *UserInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInvitationResponse.ProtoReflect.Descriptor instead.
func (*UserInvitationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserInvitationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserPayload) Reset() {
	*x = UserPayload{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPayload) ProtoMessage() {}

func (x *UserPayload) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPayload.ProtoReflect.Descriptor instead.
func (*UserPayload) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserPayload) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RolePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePayload) Reset() {
	*x = RolePayload{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePayload) ProtoMessage() {}

func (x *RolePayload) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePayload.ProtoReflect.Descriptor instead.
func (*RolePayload) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *RolePayload) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolePayload) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type RolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RolePayload         `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesResponse) Reset() {
	*x = RolesResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesResponse) ProtoMessage() {}

func (x *RolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesResponse.ProtoReflect.Descriptor instead.
func (*RolesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *RolesResponse) GetRoles() []*RolePayload {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserRolePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserPayload           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRolePayload) Reset() {
	*x = UserRolePayload{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRolePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolePayload) ProtoMessage() {}

func (x *UserRolePayload) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolePayload.ProtoReflect.Descriptor instead.
func (*UserRolePayload) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserRolePayload) GetUser() *UserPayload {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserRolePayload) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserRolePayload) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetUsersRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FirstName              string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName             string                 `protobuf:"bytes,2,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Email                  string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ExternalId             string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Country                string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	LastSuccessfulLogin    *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=last_successful_login,json=lastSuccessfulLogin,proto3" json:"last_successful_login,omitempty"`
	CurrentSuccessfulLogin *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=current_successful_login,json=currentSuccessfulLogin,proto3" json:"current_successful_login,omitempty"`
	CreatedAtFrom          *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`
	CreatedAtTo            *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`
	ModifiedAtFrom         *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=modified_at_from,json=modifiedAtFrom,proto3" json:"modified_at_from,omitempty"`
	ModifiedAtTo           *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=modified_at_to,json=modifiedAtTo,proto3" json:"modified_at_to,omitempty"`
	UserConsentFrom        *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=user_consent_from,json=userConsentFrom,proto3" json:"user_consent_from,omitempty"`
	UserConsentTo          *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=user_consent_to,json=userConsentTo,proto3" json:"user_consent_to,omitempty"`
	Skip                   int32                  `protobuf:"varint,14,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                  int32                  `protobuf:"varint,15,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy                 string                 `protobuf:"bytes,16,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                      //attribute name
	SortDirection          string                 `protobuf:"bytes,17,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` //asc/desc
	Name                   string                 `protobuf:"bytes,18,opt,name=name,proto3" json:"name,omitempty"`                                        // user to search for first name OR second name OR email
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetUsersRequest) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *GetUsersRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUsersRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GetUsersRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetUsersRequest) GetLastSuccessfulLogin() *timestamp.Timestamp {
	if x != nil {
		return x.LastSuccessfulLogin
	}
	return nil
}

func (x *GetUsersRequest) GetCurrentSuccessfulLogin() *timestamp.Timestamp {
	if x != nil {
		return x.CurrentSuccessfulLogin
	}
	return nil
}

func (x *GetUsersRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *GetUsersRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

func (x *GetUsersRequest) GetModifiedAtFrom() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtFrom
	}
	return nil
}

func (x *GetUsersRequest) GetModifiedAtTo() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAtTo
	}
	return nil
}

func (x *GetUsersRequest) GetUserConsentFrom() *timestamp.Timestamp {
	if x != nil {
		return x.UserConsentFrom
	}
	return nil
}

func (x *GetUsersRequest) GetUserConsentTo() *timestamp.Timestamp {
	if x != nil {
		return x.UserConsentTo
	}
	return nil
}

func (x *GetUsersRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUsersRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetUsersRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *GetUsersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName              string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName             string                 `protobuf:"bytes,3,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Email                  string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ExternalId             string                 `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Country                string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	PhotoLocation          string                 `protobuf:"bytes,7,opt,name=photo_location,json=photoLocation,proto3" json:"photo_location,omitempty"`
	RegistrationToken      string                 `protobuf:"bytes,8,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	LastSuccessfulLogin    *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=last_successful_login,json=lastSuccessfulLogin,proto3" json:"last_successful_login,omitempty"`
	CurrentSuccessfulLogin *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=current_successful_login,json=currentSuccessfulLogin,proto3" json:"current_successful_login,omitempty"`
	CreatedAt              *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy              string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAt             *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ModifiedBy             string                 `protobuf:"bytes,14,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	TelemetryConsent       *string                `protobuf:"bytes,15,opt,name=telemetry_consent,json=telemetryConsent,proto3,oneof" json:"telemetry_consent,omitempty"`
	TelemetryConsentAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=telemetry_consent_at,json=telemetryConsentAt,proto3" json:"telemetry_consent_at,omitempty"`
	UserConsent            *string                `protobuf:"bytes,17,opt,name=user_consent,json=userConsent,proto3,oneof" json:"user_consent,omitempty"`
	UserConsentAt          *timestamp.Timestamp   `protobuf:"bytes,18,opt,name=user_consent_at,json=userConsentAt,proto3" json:"user_consent_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserResponse) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UserResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UserResponse) GetPhotoLocation() string {
	if x != nil {
		return x.PhotoLocation
	}
	return ""
}

func (x *UserResponse) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *UserResponse) GetLastSuccessfulLogin() *timestamp.Timestamp {
	if x != nil {
		return x.LastSuccessfulLogin
	}
	return nil
}

func (x *UserResponse) GetCurrentSuccessfulLogin() *timestamp.Timestamp {
	if x != nil {
		return x.CurrentSuccessfulLogin
	}
	return nil
}

func (x *UserResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UserResponse) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *UserResponse) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *UserResponse) GetTelemetryConsent() string {
	if x != nil && x.TelemetryConsent != nil {
		return *x.TelemetryConsent
	}
	return ""
}

func (x *UserResponse) GetTelemetryConsentAt() *timestamp.Timestamp {
	if x != nil {
		return x.TelemetryConsentAt
	}
	return nil
}

func (x *UserResponse) GetUserConsent() string {
	if x != nil && x.UserConsent != nil {
		return *x.UserConsent
	}
	return ""
}

func (x *UserResponse) GetUserConsentAt() *timestamp.Timestamp {
	if x != nil {
		return x.UserConsentAt
	}
	return nil
}

type ListGetUsersResponse struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	Users             []*UserResponse                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount        int32                          `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalMatchedCount int32                          `protobuf:"varint,3,opt,name=total_matched_count,json=totalMatchedCount,proto3" json:"total_matched_count,omitempty"`
	NextPage          *ListGetUsersResponse_NextPage `protobuf:"bytes,4,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListGetUsersResponse) Reset() {
	*x = ListGetUsersResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetUsersResponse) ProtoMessage() {}

func (x *ListGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetUsersResponse.ProtoReflect.Descriptor instead.
func (*ListGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *ListGetUsersResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListGetUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListGetUsersResponse) GetTotalMatchedCount() int32 {
	if x != nil {
		return x.TotalMatchedCount
	}
	return 0
}

func (x *ListGetUsersResponse) GetNextPage() *ListGetUsersResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

type ListUsersResponse_NextPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse_NextPage) Reset() {
	*x = ListUsersResponse_NextPage{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse_NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse_NextPage) ProtoMessage() {}

func (x *ListUsersResponse_NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse_NextPage.ProtoReflect.Descriptor instead.
func (*ListUsersResponse_NextPage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListUsersResponse_NextPage) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListUsersResponse_NextPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListGetUsersResponse_NextPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetUsersResponse_NextPage) Reset() {
	*x = ListGetUsersResponse_NextPage{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetUsersResponse_NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetUsersResponse_NextPage) ProtoMessage() {}

func (x *ListGetUsersResponse_NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetUsersResponse_NextPage.ProtoReflect.Descriptor instead.
func (*ListGetUsersResponse_NextPage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18, 0}
}

func (x *ListGetUsersResponse_NextPage) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListGetUsersResponse_NextPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\x11user_common.proto\"Q\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\"\n" +
	"\x10UserExtIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd8\a\n" +
	"\x0fFindUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x02 \x01(\tR\n" +
	"secondName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12W\n" +
	"\x1alast_successful_login_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x17lastSuccessfulLoginFrom\x12S\n" +
	"\x18last_successful_login_to\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15lastSuccessfulLoginTo\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12#\n" +
	"\rresource_type\x18\n" +
	" \x03(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\v \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fworkspace_id\x18\f \x01(\tR\vworkspaceId\x12'\n" +
	"\x0forganization_id\x18\r \x01(\tR\x0eorganizationId\x12B\n" +
	"\x0fcreated_at_from\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedAtFrom\x12>\n" +
	"\rcreated_at_to\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedAtTo\x12\x1d\n" +
	"\n" +
	"created_by\x18\x10 \x01(\tR\tcreatedBy\x12D\n" +
	"\x10modified_at_from\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0emodifiedAtFrom\x12@\n" +
	"\x0emodified_at_to\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedAtTo\x12\x1f\n" +
	"\vmodified_by\x18\x13 \x01(\tR\n" +
	"modifiedBy\x12\x12\n" +
	"\x04skip\x18\x14 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x15 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x16 \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\x17 \x01(\tR\rsortDirection\x12\x12\n" +
	"\x04name\x18\x18 \x01(\tR\x04name\"\x99\x02\n" +
	"\x11ListUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.user_common.UserDataR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12.\n" +
	"\x13total_matched_count\x18\x03 \x01(\x05R\x11totalMatchedCount\x12B\n" +
	"\tnext_page\x18\x04 \x01(\v2 .user.ListUsersResponse.NextPageH\x00R\bnextPage\x88\x01\x01\x1a4\n" +
	"\bNextPage\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_next_page\"i\n" +
	"\x10UserPhotoRequest\x122\n" +
	"\tuser_data\x18\x01 \x01(\v2\x13.user.UserIdRequestH\x00R\buserData\x12\x16\n" +
	"\x05photo\x18\x02 \x01(\fH\x00R\x05photoB\t\n" +
	"\arequest\"\x8a\x01\n" +
	"\x10UserRolesRequest\x124\n" +
	"\x05roles\x18\x01 \x03(\v2\x1e.user_common.UserRoleOperationR\x05roles\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\"|\n" +
	"\x13UserGetRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"@\n" +
	"\x11UserRolesResponse\x12+\n" +
	"\x05roles\x18\x01 \x03(\v2\x15.user_common.UserRoleR\x05roles\"\x92\x02\n" +
	"\x14OrganizationExtended\x12+\n" +
	"\x11organization_name\x18\x01 \x01(\tR\x10organizationName\x12\x1f\n" +
	"\vuser_status\x18\x02 \x01(\tR\n" +
	"userStatus\x12/\n" +
	"\x13organization_status\x18\x03 \x01(\tR\x12organizationStatus\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12R\n" +
	"\x17organization_created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x15organizationCreatedAt\"\x9e\x04\n" +
	"\x0fUserProfileData\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x88\x01\x01\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\tH\x01R\x0eorganizationId\x88\x01\x01\x124\n" +
	"\x13organization_status\x18\x03 \x01(\tH\x02R\x12organizationStatus\x88\x01\x01\x12@\n" +
	"\rorganizations\x18\b \x03(\v2\x1a.user.OrganizationExtendedR\rorganizations\x120\n" +
	"\x11telemetry_consent\x18\x04 \x01(\tH\x03R\x10telemetryConsent\x88\x01\x01\x12L\n" +
	"\x14telemetry_consent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12telemetryConsentAt\x12&\n" +
	"\fuser_consent\x18\x06 \x01(\tH\x04R\vuserConsent\x88\x01\x01\x12B\n" +
	"\x0fuser_consent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ruserConsentAtB\t\n" +
	"\a_statusB\x12\n" +
	"\x10_organization_idB\x16\n" +
	"\x14_organization_statusB\x14\n" +
	"\x12_telemetry_consentB\x0f\n" +
	"\r_user_consent\"\xbc\x04\n" +
	"\x0eActiveUserData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x03 \x01(\tR\n" +
	"secondName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x12/\n" +
	"\x13organization_status\x18\a \x01(\tR\x12organizationStatus\x12+\n" +
	"\x05roles\x18\b \x03(\v2\x15.user_common.UserRoleR\x05roles\x12N\n" +
	"\x15last_successful_login\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x13lastSuccessfulLogin\x12T\n" +
	"\x18current_successful_login\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x16currentSuccessfulLogin\x120\n" +
	"\x11telemetry_consent\x18\v \x01(\tH\x00R\x10telemetryConsent\x88\x01\x01\x12&\n" +
	"\fuser_consent\x18\f \x01(\tH\x01R\vuserConsent\x88\x01\x01B\x14\n" +
	"\x12_telemetry_consentB\x0f\n" +
	"\r_user_consent\"1\n" +
	"\x16UserInvitationResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\vUserPayload\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\vRolePayload\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"8\n" +
	"\rRolesResponse\x12'\n" +
	"\x05roles\x18\x01 \x03(\v2\x11.user.RolePayloadR\x05roles\"m\n" +
	"\x0fUserRolePayload\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user.UserPayloadR\x04user\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"\xde\x06\n" +
	"\x0fGetUsersRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x02 \x01(\tR\n" +
	"secondName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12N\n" +
	"\x15last_successful_login\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x13lastSuccessfulLogin\x12T\n" +
	"\x18current_successful_login\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x16currentSuccessfulLogin\x12B\n" +
	"\x0fcreated_at_from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedAtFrom\x12>\n" +
	"\rcreated_at_to\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedAtTo\x12D\n" +
	"\x10modified_at_from\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0emodifiedAtFrom\x12@\n" +
	"\x0emodified_at_to\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fmodifiedAtTo\x12F\n" +
	"\x11user_consent_from\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0fuserConsentFrom\x12B\n" +
	"\x0fuser_consent_to\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ruserConsentTo\x12\x12\n" +
	"\x04skip\x18\x0e \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x0f \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x10 \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\x11 \x01(\tR\rsortDirection\x12\x12\n" +
	"\x04name\x18\x12 \x01(\tR\x04name\"\xf6\x06\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x03 \x01(\tR\n" +
	"secondName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1f\n" +
	"\vexternal_id\x18\x05 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12%\n" +
	"\x0ephoto_location\x18\a \x01(\tR\rphotoLocation\x12-\n" +
	"\x12registration_token\x18\b \x01(\tR\x11registrationToken\x12N\n" +
	"\x15last_successful_login\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x13lastSuccessfulLogin\x12T\n" +
	"\x18current_successful_login\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x16currentSuccessfulLogin\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\x12;\n" +
	"\vmodified_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1f\n" +
	"\vmodified_by\x18\x0e \x01(\tR\n" +
	"modifiedBy\x120\n" +
	"\x11telemetry_consent\x18\x0f \x01(\tH\x00R\x10telemetryConsent\x88\x01\x01\x12L\n" +
	"\x14telemetry_consent_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x12telemetryConsentAt\x12&\n" +
	"\fuser_consent\x18\x11 \x01(\tH\x01R\vuserConsent\x88\x01\x01\x12B\n" +
	"\x0fuser_consent_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\ruserConsentAtB\x14\n" +
	"\x12_telemetry_consentB\x0f\n" +
	"\r_user_consent\"\x9c\x02\n" +
	"\x14ListGetUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.user.UserResponseR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12.\n" +
	"\x13total_matched_count\x18\x03 \x01(\x05R\x11totalMatchedCount\x12E\n" +
	"\tnext_page\x18\x04 \x01(\v2#.user.ListGetUsersResponse.NextPageH\x00R\bnextPage\x88\x01\x01\x1a4\n" +
	"\bNextPage\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_next_page2\xec\x11\n" +
	"\x04User\x12p\n" +
	"\x06create\x12\x15.user_common.UserData\x1a\x15.user_common.UserData\"8\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1/organizations/{organization_id}/users\x12u\n" +
	"\x06modify\x12\x15.user_common.UserData\x1a\x15.user_common.UserData\"=\x82\xd3\xe4\x93\x027:\x01*\x1a2/api/v1/organizations/{organization_id}/users/{id}\x12x\n" +
	"\x0fget_active_user\x12\x13.user.UserIdRequest\x1a\x14.user.ActiveUserData\":\x82\xd3\xe4\x93\x024\x122/api/v1/organizations/{organization_id}/activeUser\x12Z\n" +
	"\x10get_user_profile\x12\x16.google.protobuf.Empty\x1a\x15.user.UserProfileData\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/profile\x12x\n" +
	"\tget_by_id\x12\x13.user.UserIdRequest\x1a\x15.user_common.UserData\"?\x82\xd3\xe4\x93\x029\x127/api/v1/organizations/{organization_id}/users/{user_id}\x12q\n" +
	"\x12get_by_external_id\x12\x16.user.UserExtIdRequest\x1a\x15.user_common.UserData\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/organizations/users/external\x12m\n" +
	"\x04find\x12\x15.user.FindUserRequest\x1a\x17.user.ListUsersResponse\"5\x82\xd3\xe4\x93\x02/\x12-/api/v1/organizations/{organization_id}/users\x12:\n" +
	"\x06logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12v\n" +
	"\x06delete\x12\x13.user.UserIdRequest\x1a\x16.google.protobuf.Empty\"?\x82\xd3\xe4\x93\x029*7/api/v1/organizations/{organization_id}/users/{user_id}\x12\x9e\x01\n" +
	"\x0fsend_invitation\x12\".user_common.UserInvitationRequest\x1a\x1c.user.UserInvitationResponse\"I\x82\xd3\xe4\x93\x02C:\x01*\">/api/v1/organizations/{user.organization_id}/users/invitations\x12?\n" +
	"\tadd_photo\x12\x16.user.UserPhotoRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12\x83\x01\n" +
	"\fdelete_photo\x12\x13.user.UserIdRequest\x1a\x16.google.protobuf.Empty\"F\x82\xd3\xe4\x93\x02@*>/api/v1/organizations/{organization_id}/users/{user_id}/photos\x12\x80\x01\n" +
	"\tget_photo\x12\x13.user.UserIdRequest\x1a\x16.common.PreUrlResponse\"F\x82\xd3\xe4\x93\x02@\x12>/api/v1/organizations/{organization_id}/users/{user_id}/photos\x12\x96\x01\n" +
	"\tget_roles\x12\x19.user.UserGetRolesRequest\x1a\x17.user.UserRolesResponse\"U\x82\xd3\xe4\x93\x02O\x12M/api/v1/organizations/{organization_id}/users/{user_id}/roles/{resource_type}\x12\x85\x01\n" +
	"\tset_roles\x12\x16.user.UserRolesRequest\x1a\x16.google.protobuf.Empty\"H\x82\xd3\xe4\x93\x02B:\x01*\x1a=/api/v1/organizations/{organization_id}/users/{user_id}/roles\x12\x84\x01\n" +
	"\x0eget_user_roles\x12\x11.user.UserPayload\x1a\x13.user.RolesResponse\"J\x82\xd3\xe4\x93\x02D\x12B/api/v1/organizations/{organization_id}/membership/{user_id}/roles\x12\x95\x01\n" +
	"\vassign_role\x12\x15.user.UserRolePayload\x1a\x16.google.protobuf.Empty\"W\x82\xd3\xe4\x93\x02Q:\x01*\"L/api/v1/organizations/{user.organization_id}/membership/{user.user_id}/roles\x12\x92\x01\n" +
	"\vremove_role\x12\x15.user.UserRolePayload\x1a\x16.google.protobuf.Empty\"T\x82\xd3\xe4\x93\x02N*L/api/v1/organizations/{user.organization_id}/membership/{user.user_id}/roles\x12U\n" +
	"\tget_users\x12\x15.user.GetUsersRequest\x1a\x1a.user.ListGetUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/usersB\"Z geti.com/account_service_grpc/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_user_proto_goTypes = []any{
	(*UserIdRequest)(nil),                 // 0: user.UserIdRequest
	(*UserExtIdRequest)(nil),              // 1: user.UserExtIdRequest
	(*FindUserRequest)(nil),               // 2: user.FindUserRequest
	(*ListUsersResponse)(nil),             // 3: user.ListUsersResponse
	(*UserPhotoRequest)(nil),              // 4: user.UserPhotoRequest
	(*UserRolesRequest)(nil),              // 5: user.UserRolesRequest
	(*UserGetRolesRequest)(nil),           // 6: user.UserGetRolesRequest
	(*UserRolesResponse)(nil),             // 7: user.UserRolesResponse
	(*OrganizationExtended)(nil),          // 8: user.OrganizationExtended
	(*UserProfileData)(nil),               // 9: user.UserProfileData
	(*ActiveUserData)(nil),                // 10: user.ActiveUserData
	(*UserInvitationResponse)(nil),        // 11: user.UserInvitationResponse
	(*UserPayload)(nil),                   // 12: user.UserPayload
	(*RolePayload)(nil),                   // 13: user.RolePayload
	(*RolesResponse)(nil),                 // 14: user.RolesResponse
	(*UserRolePayload)(nil),               // 15: user.UserRolePayload
	(*GetUsersRequest)(nil),               // 16: user.GetUsersRequest
	(*UserResponse)(nil),                  // 17: user.UserResponse
	(*ListGetUsersResponse)(nil),          // 18: user.ListGetUsersResponse
	(*ListUsersResponse_NextPage)(nil),    // 19: user.ListUsersResponse.NextPage
	(*ListGetUsersResponse_NextPage)(nil), // 20: user.ListGetUsersResponse.NextPage
	(*timestamp.Timestamp)(nil),           // 21: google.protobuf.Timestamp
	(*UserData)(nil),                      // 22: user_common.UserData
	(*UserRoleOperation)(nil),             // 23: user_common.UserRoleOperation
	(*UserRole)(nil),                      // 24: user_common.UserRole
	(*empty.Empty)(nil),                   // 25: google.protobuf.Empty
	(*UserInvitationRequest)(nil),         // 26: user_common.UserInvitationRequest
	(*PreUrlResponse)(nil),                // 27: common.PreUrlResponse
}
var file_user_proto_depIdxs = []int32{
	21, // 0: user.FindUserRequest.last_successful_login_from:type_name -> google.protobuf.Timestamp
	21, // 1: user.FindUserRequest.last_successful_login_to:type_name -> google.protobuf.Timestamp
	21, // 2: user.FindUserRequest.created_at_from:type_name -> google.protobuf.Timestamp
	21, // 3: user.FindUserRequest.created_at_to:type_name -> google.protobuf.Timestamp
	21, // 4: user.FindUserRequest.modified_at_from:type_name -> google.protobuf.Timestamp
	21, // 5: user.FindUserRequest.modified_at_to:type_name -> google.protobuf.Timestamp
	22, // 6: user.ListUsersResponse.users:type_name -> user_common.UserData
	19, // 7: user.ListUsersResponse.next_page:type_name -> user.ListUsersResponse.NextPage
	0,  // 8: user.UserPhotoRequest.user_data:type_name -> user.UserIdRequest
	23, // 9: user.UserRolesRequest.roles:type_name -> user_common.UserRoleOperation
	24, // 10: user.UserRolesResponse.roles:type_name -> user_common.UserRole
	21, // 11: user.OrganizationExtended.organization_created_at:type_name -> google.protobuf.Timestamp
	8,  // 12: user.UserProfileData.organizations:type_name -> user.OrganizationExtended
	21, // 13: user.UserProfileData.telemetry_consent_at:type_name -> google.protobuf.Timestamp
	21, // 14: user.UserProfileData.user_consent_at:type_name -> google.protobuf.Timestamp
	24, // 15: user.ActiveUserData.roles:type_name -> user_common.UserRole
	21, // 16: user.ActiveUserData.last_successful_login:type_name -> google.protobuf.Timestamp
	21, // 17: user.ActiveUserData.current_successful_login:type_name -> google.protobuf.Timestamp
	13, // 18: user.RolesResponse.roles:type_name -> user.RolePayload
	12, // 19: user.UserRolePayload.user:type_name -> user.UserPayload
	21, // 20: user.GetUsersRequest.last_successful_login:type_name -> google.protobuf.Timestamp
	21, // 21: user.GetUsersRequest.current_successful_login:type_name -> google.protobuf.Timestamp
	21, // 22: user.GetUsersRequest.created_at_from:type_name -> google.protobuf.Timestamp
	21, // 23: user.GetUsersRequest.created_at_to:type_name -> google.protobuf.Timestamp
	21, // 24: user.GetUsersRequest.modified_at_from:type_name -> google.protobuf.Timestamp
	21, // 25: user.GetUsersRequest.modified_at_to:type_name -> google.protobuf.Timestamp
	21, // 26: user.GetUsersRequest.user_consent_from:type_name -> google.protobuf.Timestamp
	21, // 27: user.GetUsersRequest.user_consent_to:type_name -> google.protobuf.Timestamp
	21, // 28: user.UserResponse.last_successful_login:type_name -> google.protobuf.Timestamp
	21, // 29: user.UserResponse.current_successful_login:type_name -> google.protobuf.Timestamp
	21, // 30: user.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	21, // 31: user.UserResponse.modified_at:type_name -> google.protobuf.Timestamp
	21, // 32: user.UserResponse.telemetry_consent_at:type_name -> google.protobuf.Timestamp
	21, // 33: user.UserResponse.user_consent_at:type_name -> google.protobuf.Timestamp
	17, // 34: user.ListGetUsersResponse.users:type_name -> user.UserResponse
	20, // 35: user.ListGetUsersResponse.next_page:type_name -> user.ListGetUsersResponse.NextPage
	22, // 36: user.User.create:input_type -> user_common.UserData
	22, // 37: user.User.modify:input_type -> user_common.UserData
	0,  // 38: user.User.get_active_user:input_type -> user.UserIdRequest
	25, // 39: user.User.get_user_profile:input_type -> google.protobuf.Empty
	0,  // 40: user.User.get_by_id:input_type -> user.UserIdRequest
	1,  // 41: user.User.get_by_external_id:input_type -> user.UserExtIdRequest
	2,  // 42: user.User.find:input_type -> user.FindUserRequest
	25, // 43: user.User.logout:input_type -> google.protobuf.Empty
	0,  // 44: user.User.delete:input_type -> user.UserIdRequest
	26, // 45: user.User.send_invitation:input_type -> user_common.UserInvitationRequest
	4,  // 46: user.User.add_photo:input_type -> user.UserPhotoRequest
	0,  // 47: user.User.delete_photo:input_type -> user.UserIdRequest
	0,  // 48: user.User.get_photo:input_type -> user.UserIdRequest
	6,  // 49: user.User.get_roles:input_type -> user.UserGetRolesRequest
	5,  // 50: user.User.set_roles:input_type -> user.UserRolesRequest
	12, // 51: user.User.get_user_roles:input_type -> user.UserPayload
	15, // 52: user.User.assign_role:input_type -> user.UserRolePayload
	15, // 53: user.User.remove_role:input_type -> user.UserRolePayload
	16, // 54: user.User.get_users:input_type -> user.GetUsersRequest
	22, // 55: user.User.create:output_type -> user_common.UserData
	22, // 56: user.User.modify:output_type -> user_common.UserData
	10, // 57: user.User.get_active_user:output_type -> user.ActiveUserData
	9,  // 58: user.User.get_user_profile:output_type -> user.UserProfileData
	22, // 59: user.User.get_by_id:output_type -> user_common.UserData
	22, // 60: user.User.get_by_external_id:output_type -> user_common.UserData
	3,  // 61: user.User.find:output_type -> user.ListUsersResponse
	25, // 62: user.User.logout:output_type -> google.protobuf.Empty
	25, // 63: user.User.delete:output_type -> google.protobuf.Empty
	11, // 64: user.User.send_invitation:output_type -> user.UserInvitationResponse
	25, // 65: user.User.add_photo:output_type -> google.protobuf.Empty
	25, // 66: user.User.delete_photo:output_type -> google.protobuf.Empty
	27, // 67: user.User.get_photo:output_type -> common.PreUrlResponse
	7,  // 68: user.User.get_roles:output_type -> user.UserRolesResponse
	25, // 69: user.User.set_roles:output_type -> google.protobuf.Empty
	14, // 70: user.User.get_user_roles:output_type -> user.RolesResponse
	25, // 71: user.User.assign_role:output_type -> google.protobuf.Empty
	25, // 72: user.User.remove_role:output_type -> google.protobuf.Empty
	18, // 73: user.User.get_users:output_type -> user.ListGetUsersResponse
	55, // [55:74] is the sub-list for method output_type
	36, // [36:55] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_common_proto_init()
	file_user_common_proto_init()
	file_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_user_proto_msgTypes[4].OneofWrappers = []any{
		(*UserPhotoRequest_UserData)(nil),
		(*UserPhotoRequest_Photo)(nil),
	}
	file_user_proto_msgTypes[9].OneofWrappers = []any{}
	file_user_proto_msgTypes[10].OneofWrappers = []any{}
	file_user_proto_msgTypes[17].OneofWrappers = []any{}
	file_user_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
