image: 
  registry: docker.io
  repository: bitnami
  name: openldap:2.6.3-debian-11-r63
imagePullPolicy: IfNotPresent

debug: false

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 300Mi

global:
  storage_volume_claim_name_openldap: data-storage-volume-claim
  enable_master_node_selector: true
  ldap_service_user_secret_name: ''
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 300Mi

initResources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 100Mi

service:
  type: ClusterIP
  ports:
    ldap:
      port: 389
      targetport: 1389

serviceAccount:
  create: true

volumeSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN

ldapSecurityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  runAsUser: 10001
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - KILL
      - NET_BIND_SERVICE

config:
  impt_ldif: |-
    # Group definitions.
    dn: ou=Groups,dc=example,dc=org
    objectClass: organizationalUnit
    ou: Groups

    dn: cn=Admins,ou=Groups,dc=example,dc=org
    cn: Admins
    gidnumber: 500
    objectclass: posixGroup
    objectclass: top

    dn: cn=Users,ou=Groups,dc=example,dc=org
    cn: Users
    gidnumber: 501
    objectclass: posixGroup
    objectclass: top

    dn: cn=ServiceAccounts,ou=Groups,dc=example,dc=org
    cn: ServiceAccounts
    gidnumber: 502
    objectclass: posixGroup
    objectclass: top
  service_accounts_group_ldif: |-
    dn: cn=ServiceAccounts,ou=Groups,dc=example,dc=org
    cn: ServiceAccounts
    gidnumber: 502
    objectclass: posixGroup
    objectclass: top
  ppolicy_container_ldif: |-
    dn: ou=pwpolicy,dc=example,dc=org
    objectClass: organizationalUnit
    objectClass: top
    ou: pwpolicy
  ppolicy_rules_ldif: |-
    dn: cn=default,ou=pwpolicy,dc=example,dc=org
    objectClass: person
    objectClass: pwdPolicyChecker
    objectClass: pwdPolicy
    cn: pwpolicy
    sn: pwpolicy
    pwdAttribute: userPassword
    pwdLockout: TRUE
    pwdMaxFailure: 5
    pwdLockoutDuration: 600
  pbkdf2_ldif: |-
    dn: cn=module{0},cn=config
    objectClass: olcModuleList
    cn: module{0}
    olcModuleLoad: pw-pbkdf2
  ppolicy_module_ldif: |-
    dn: cn=module{1},cn=config
    objectClass: olcModuleList
    cn: module{1}
    olcModuleLoad: ppolicy
  ppolicy_overlay_ldif: |-
    dn: olcOverlay=ppolicy, olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcPPolicyConfig
    olcOverlay: ppolicy
    olcPPolicyDefault: cn=default,ou=pwpolicy,dc=example,dc=org
    olcPPolicyHashCleartext: TRUE
  db_max_size_ldif: |-
    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcDbMaxSize
    olcDbMaxSize: 52428800
