# INTEL CONFIDENTIAL
# 
# Copyright (C) 2025 Intel Corporation
# 
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by
# the express license under which they were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
# without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import job_update_service_pb2 as job__update__service__pb2


class JobUpdateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.job_update = channel.unary_unary(
                "/JobUpdateService/job_update",
                request_serializer=job__update__service__pb2.JobUpdateRequest.SerializeToString,
                response_deserializer=job__update__service__pb2.JobUpdateResponse.FromString,
                )


class JobUpdateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def job_update(self, request, context):
        """Sends a job update.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_JobUpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            "job_update": grpc.unary_unary_rpc_method_handler(
                    servicer.job_update,
                    request_deserializer=job__update__service__pb2.JobUpdateRequest.FromString,
                    response_serializer=job__update__service__pb2.JobUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            "JobUpdateService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobUpdateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def job_update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, "/JobUpdateService/job_update",
            job__update__service__pb2.JobUpdateRequest.SerializeToString,
            job__update__service__pb2.JobUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
