# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_update_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18job_update_service.proto"2\n\x05\x45rror\x12\x18\n\x04\x63ode\x18\x01 \x01(\x0e\x32\n.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t"\xa2\x03\n\x10JobUpdateRequest\x12\x19\n\x0c\x65xecution_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08metadata\x18\x02 \x01(\tH\x01\x88\x01\x01\x12)\n\x04\x63ost\x18\x03 \x01(\x0b\x32\x16.JobUpdateRequest.CostH\x02\x88\x01\x01\x12\'\n\x03gpu\x18\x04 \x01(\x0b\x32\x15.JobUpdateRequest.GpuH\x03\x88\x01\x01\x1a\x8c\x01\n\x04\x43ost\x12\x31\n\x08\x63onsumed\x18\x01 \x03(\x0b\x32\x1f.JobUpdateRequest.Cost.Consumed\x1aQ\n\x08\x43onsumed\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x16\n\x0e\x63onsuming_date\x18\x03 \x01(\x03\x12\x0f\n\x07service\x18\x04 \x01(\t\x1aJ\n\x03Gpu\x12,\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1c.JobUpdateRequest.Gpu.Action"\x15\n\x06\x41\x63tion\x12\x0b\n\x07RELEASE\x10\x00\x42\x0f\n\r_execution_idB\x0b\n\t_metadataB\x07\n\x05_costB\x06\n\x04_gpu"\x07\n\x05\x45mpty"O\n\x11JobUpdateResponse\x12\x17\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\x06.EmptyH\x00\x12\x17\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\x08\n\x06result*A\n\tErrorCode\x12\x17\n\x13\x45XECUTION_NOT_FOUND\x10\x00\x12\x1b\n\x17INVALID_METADATA_UPDATE\x10\x01\x32I\n\x10JobUpdateService\x12\x35\n\njob_update\x12\x11.JobUpdateRequest\x1a\x12.JobUpdateResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "job_update_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_ERRORCODE"]._serialized_start = 591
    _globals["_ERRORCODE"]._serialized_end = 656
    _globals["_ERROR"]._serialized_start = 28
    _globals["_ERROR"]._serialized_end = 78
    _globals["_JOBUPDATEREQUEST"]._serialized_start = 81
    _globals["_JOBUPDATEREQUEST"]._serialized_end = 499
    _globals["_JOBUPDATEREQUEST_COST"]._serialized_start = 236
    _globals["_JOBUPDATEREQUEST_COST"]._serialized_end = 376
    _globals["_JOBUPDATEREQUEST_COST_CONSUMED"]._serialized_start = 295
    _globals["_JOBUPDATEREQUEST_COST_CONSUMED"]._serialized_end = 376
    _globals["_JOBUPDATEREQUEST_GPU"]._serialized_start = 378
    _globals["_JOBUPDATEREQUEST_GPU"]._serialized_end = 452
    _globals["_JOBUPDATEREQUEST_GPU_ACTION"]._serialized_start = 431
    _globals["_JOBUPDATEREQUEST_GPU_ACTION"]._serialized_end = 452
    _globals["_EMPTY"]._serialized_start = 501
    _globals["_EMPTY"]._serialized_end = 508
    _globals["_JOBUPDATERESPONSE"]._serialized_start = 510
    _globals["_JOBUPDATERESPONSE"]._serialized_end = 589
    _globals["_JOBUPDATESERVICE"]._serialized_start = 658
    _globals["_JOBUPDATESERVICE"]._serialized_end = 731
# @@protoc_insertion_point(module_scope)
