// INTEL CONFIDENTIAL
//
// Copyright (C) 2023 Intel Corporation
//
// This software and the related documents are Intel copyrighted materials, and your use of them is governed by
// the express license under which they were provided to you ("License"). Unless the License provides otherwise,
// you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
// without Intel's prior written permission.
//
// This software and the related documents are provided as is, with no express or implied warranties,
// other than those that are expressly stated in the License.

// other than those that are expressly stated in the License.

import { SHAPE_TYPE_DTO } from '../../../../src/core/annotations/dtos/annotation.interface';
import { animalLabelId, deerLabelId } from '../../../mocks/detection-segmentation/mocks';
import { AnnotationDTOWithLabelProperties as AnnotationDTO } from '../../../utils/annotation';

export const annotations: AnnotationDTO[] = [
    {
        id: '635fd248c9d1aed75d00f89a',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 244, y: 106, width: 508, height: 436 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '635fd248c9d1aed75d00f90a',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 114, y: 112, width: 90, height: 108 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },

    {
        id: '398fb213-9d02-432d-9091-42fd760f7afd',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 870, y: 169, width: 69, height: 206 },
        labels: [
            {
                id: animalLabelId,
                probability: 1.0,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '6fa3f48f-6199-4ac1-9509-94e624efdd64',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 36, y: 113, width: 73, height: 54 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: 'f4e0a394-3930-4500-8009-6918125c397a',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 938, y: 332 },
                { x: 927, y: 311 },
                { x: 900, y: 309 },
                { x: 884, y: 261 },
                { x: 885, y: 236 },
                { x: 897, y: 208 },
                { x: 921, y: 184 },
                { x: 938, y: 182 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '0c9550e9-8a9d-4d54-98a3-bdb7a2562bea',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 59, y: 120 },
                { x: 92, y: 133 },
                { x: 103, y: 149 },
                { x: 103, y: 150 },
                { x: 89, y: 160 },
                { x: 80, y: 154 },
                { x: 50, y: 155 },
                { x: 39, y: 135 },
                { x: 46, y: 120 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '635fd248c9d1aed75d00f89c',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 157, y: 128 },
                { x: 170, y: 141 },
                { x: 177, y: 141 },
                { x: 188, y: 148 },
                { x: 193, y: 157 },
                { x: 195, y: 171 },
                { x: 192, y: 184 },
                { x: 183, y: 187 },
                { x: 166, y: 193 },
                { x: 155, y: 192 },
                { x: 146, y: 181 },
                { x: 140, y: 168 },
                { x: 134, y: 161 },
                { x: 132, y: 150 },
                { x: 124, y: 135 },
                { x: 123, y: 120 },
                { x: 130, y: 129 },
                { x: 153, y: 129 },
                { x: 153, y: 120 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 1.0,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '0b355c91-ae2c-4032-ad98-25f28a4239c2',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 666, y: 117 },
                { x: 699, y: 115 },
                { x: 722, y: 119 },
                { x: 732, y: 148 },
                { x: 712, y: 190 },
                { x: 719, y: 192 },
                { x: 746, y: 160 },
                { x: 741, y: 196 },
                { x: 713, y: 220 },
                { x: 712, y: 236 },
                { x: 701, y: 284 },
                { x: 652, y: 361 },
                { x: 614, y: 383 },
                { x: 599, y: 388 },
                { x: 583, y: 525 },
                { x: 563, y: 540 },
                { x: 557, y: 531 },
                { x: 551, y: 381 },
                { x: 489, y: 384 },
                { x: 430, y: 379 },
                { x: 412, y: 373 },
                { x: 358, y: 464 },
                { x: 369, y: 513 },
                { x: 325, y: 512 },
                { x: 311, y: 424 },
                { x: 358, y: 374 },
                { x: 348, y: 344 },
                { x: 324, y: 331 },
                { x: 323, y: 268 },
                { x: 401, y: 232 },
                { x: 555, y: 254 },
                { x: 583, y: 243 },
                { x: 640, y: 268 },
                { x: 650, y: 221 },
                { x: 617, y: 205 },
                { x: 604, y: 170 },
                { x: 650, y: 208 },
                { x: 660, y: 209 },
                { x: 660, y: 208 },
                { x: 659, y: 188 },
                { x: 638, y: 160 },
                { x: 631, y: 131 },
                { x: 650, y: 113 },
                { x: 650, y: 113 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: 'cf4ec9ee-2f3b-45f6-8cc1-72bdf9b5fea3',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 455, y: 154 },
                { x: 453, y: 183 },
                { x: 452, y: 184 },
                { x: 433, y: 187 },
                { x: 433, y: 188 },
                { x: 433, y: 172 },
                { x: 383, y: 186 },
                { x: 316, y: 183 },
                { x: 309, y: 173 },
                { x: 419, y: 147 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
];

export const predictions: AnnotationDTO[] = [
    {
        id: '635fd248c9d1aed75d00f89a',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 244, y: 106, width: 508, height: 436 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '635fd248c9d1aed75d00f90a',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 114, y: 112, width: 90, height: 108 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '398fb213-9d02-432d-9091-42fd760f7afd',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 870, y: 169, width: 69, height: 206 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '6fa3f48f-6199-4ac1-9509-94e624efdd64',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 36, y: 113, width: 73, height: 54 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '635fd248c9d1aed75d00f89c',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 157, y: 128 },
                { x: 170, y: 141 },
                { x: 177, y: 141 },
                { x: 188, y: 148 },
                { x: 193, y: 157 },
                { x: 195, y: 171 },
                { x: 192, y: 184 },
                { x: 183, y: 187 },
                { x: 166, y: 193 },
                { x: 155, y: 192 },
                { x: 146, y: 181 },
                { x: 140, y: 168 },
                { x: 134, y: 161 },
                { x: 132, y: 150 },
                { x: 124, y: 135 },
                { x: 123, y: 120 },
                { x: 130, y: 129 },
                { x: 153, y: 129 },
                { x: 153, y: 120 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 0.34418377533671984,
                source: { model_id: 'model-id', model_storage_id: 'model-storage-id', user_id: null },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '1b147990-83a2-436a-b6f5-7fc48a6c182b',
        shape: { type: SHAPE_TYPE_DTO.RECTANGLE, x: 294, y: 135, width: 161, height: 65 },
        labels: [
            {
                id: animalLabelId,
                probability: 1,
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '0c9550e9-8a9d-4d54-98a3-bdb7a2562bea',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 59, y: 120 },
                { x: 92, y: 133 },
                { x: 103, y: 149 },
                { x: 103, y: 150 },
                { x: 89, y: 160 },
                { x: 80, y: 154 },
                { x: 50, y: 155 },
                { x: 39, y: 135 },
                { x: 46, y: 120 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 0.9476663084795571,
                source: { model_id: 'model-id', model_storage_id: 'model-storage-id', user_id: null },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: 'cf4ec9ee-2f3b-45f6-8cc1-72bdf9b5fea3',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 455, y: 154 },
                { x: 453, y: 183 },
                { x: 452, y: 184 },
                { x: 433, y: 187 },
                { x: 433, y: 188 },
                { x: 433, y: 172 },
                { x: 383, y: 186 },
                { x: 316, y: 183 },
                { x: 309, y: 173 },
                { x: 419, y: 147 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 0.5420070001205546,
                source: { model_id: 'model-id', model_storage_id: 'model-storage-id', user_id: null },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: '0b355c91-ae2c-4032-ad98-25f28a4239c2',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 666, y: 117 },
                { x: 699, y: 115 },
                { x: 722, y: 119 },
                { x: 732, y: 148 },
                { x: 712, y: 190 },
                { x: 719, y: 192 },
                { x: 746, y: 160 },
                { x: 741, y: 196 },
                { x: 713, y: 220 },
                { x: 712, y: 236 },
                { x: 701, y: 284 },
                { x: 652, y: 361 },
                { x: 614, y: 383 },
                { x: 599, y: 388 },
                { x: 583, y: 525 },
                { x: 563, y: 540 },
                { x: 557, y: 531 },
                { x: 551, y: 381 },
                { x: 489, y: 384 },
                { x: 430, y: 379 },
                { x: 412, y: 373 },
                { x: 358, y: 464 },
                { x: 369, y: 513 },
                { x: 325, y: 512 },
                { x: 311, y: 424 },
                { x: 358, y: 374 },
                { x: 348, y: 344 },
                { x: 324, y: 331 },
                { x: 323, y: 268 },
                { x: 401, y: 232 },
                { x: 555, y: 254 },
                { x: 583, y: 243 },
                { x: 640, y: 268 },
                { x: 650, y: 221 },
                { x: 617, y: 205 },
                { x: 604, y: 170 },
                { x: 650, y: 208 },
                { x: 660, y: 209 },
                { x: 660, y: 208 },
                { x: 659, y: 188 },
                { x: 638, y: 160 },
                { x: 631, y: 131 },
                { x: 650, y: 113 },
                { x: 650, y: 113 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 0.5742295056239679,
                source: { model_id: 'model-id', model_storage_id: 'model-storage-id', user_id: null },
                hotkey: '',
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
    {
        id: 'f4e0a394-3930-4500-8009-6918125c397a',
        shape: {
            type: SHAPE_TYPE_DTO.POLYGON,
            points: [
                { x: 938, y: 332 },
                { x: 927, y: 311 },
                { x: 900, y: 309 },
                { x: 884, y: 261 },
                { x: 885, y: 236 },
                { x: 897, y: 208 },
                { x: 921, y: 184 },
                { x: 938, y: 182 },
            ],
        },
        labels: [
            {
                id: deerLabelId,
                probability: 0.4373651256116047,
                hotkey: '',
                source: { model_id: null, model_storage_id: null, user_id: 'admin@intel.com' },
                color: '',
                name: '',
            },
        ],
        labels_to_revisit: [],
    },
];
