// Copyright (C) 2022-2025 Intel Corporation
// LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

import { RESOURCE_TYPE, USER_ROLE } from '../../../core/users/users.interface';
import {
    OPERATION_NEW,
    OPERATION_OLD,
    OperationPermissionNew,
    OperationPermissionOld,
} from './has-permission.interface';

const ORGANIZATION_ADMIN_PERMISSION = {
    role: USER_ROLE.ORGANIZATION_ADMIN,
    resourceType: RESOURCE_TYPE.ORGANIZATION,
};

const WORKSPACE_ADMIN_PERMISSION = {
    role: USER_ROLE.WORKSPACE_ADMIN,
    resourceType: RESOURCE_TYPE.WORKSPACE,
};

const WORKSPACE_CONTRIBUTOR_PERMISSION = {
    role: USER_ROLE.WORKSPACE_CONTRIBUTOR,
    resourceType: RESOURCE_TYPE.WORKSPACE,
};

const PROJECT_ADMIN_PERMISSION = {
    role: USER_ROLE.PROJECT_MANAGER,
    resourceType: RESOURCE_TYPE.PROJECT,
};

const PROJECT_CONTRIBUTOR_PERMISSION = {
    role: USER_ROLE.PROJECT_CONTRIBUTOR,
    resourceType: RESOURCE_TYPE.PROJECT,
};

const ORGANIZATION_CONTRIBUTION_PERMISSION = {
    role: USER_ROLE.ORGANIZATION_CONTRIBUTOR,
    resourceType: RESOURCE_TYPE.ORGANIZATION,
};

export const OPERATION_PERMISSION_NEW: OperationPermissionNew = {
    [OPERATION_NEW.ADD_USER_TO_PROJECT]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_ADMIN_PERMISSION],
    [OPERATION_NEW.ADD_USER_TO_WORKSPACE]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_NEW.ADD_WORKSPACE]: [ORGANIZATION_ADMIN_PERMISSION, ORGANIZATION_CONTRIBUTION_PERMISSION],
    [OPERATION_NEW.INVITE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION_NEW.MANAGE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION_NEW.WORKSPACE_MANAGEMENT]: [WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_NEW.IMPORT_PROJECT]: [WORKSPACE_ADMIN_PERMISSION, WORKSPACE_CONTRIBUTOR_PERMISSION],

    [OPERATION_NEW.CAN_SEE_WORKSPACE]: [
        ORGANIZATION_ADMIN_PERMISSION,
        WORKSPACE_ADMIN_PERMISSION,
        WORKSPACE_CONTRIBUTOR_PERMISSION,
    ],
    [OPERATION_NEW.CAN_SEE_PROJECT]: [PROJECT_ADMIN_PERMISSION, PROJECT_CONTRIBUTOR_PERMISSION],
    [OPERATION_NEW.PROJECT_CREATION]: [WORKSPACE_ADMIN_PERMISSION, WORKSPACE_CONTRIBUTOR_PERMISSION],
    [OPERATION_NEW.PROJECT_DELETION]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_ADMIN_PERMISSION],
    [OPERATION_NEW.CAN_VIEW_CREDITS_USAGE]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_NEW.PROJECT_NAME_EDITION]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_ADMIN_PERMISSION],
    [OPERATION_NEW.USAGE_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_NEW.ANALYTICS_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
};

const canManageProject = [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION, PROJECT_ADMIN_PERMISSION];
const canCreateProject = [WORKSPACE_ADMIN_PERMISSION, WORKSPACE_CONTRIBUTOR_PERMISSION];

export const OPERATION_PERMISSION_OLD: OperationPermissionOld = {
    [OPERATION_OLD.INVITE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION_OLD.MANAGE_USER]: [ORGANIZATION_ADMIN_PERMISSION],
    [OPERATION_OLD.WORKSPACE_MANAGEMENT]: [WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_OLD.IMPORT_PROJECT]: [WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_OLD.ADD_USER_TO_PROJECT]: canManageProject,
    [OPERATION_OLD.PROJECT_CREATION]: canCreateProject,
    [OPERATION_OLD.PROJECT_DELETION]: canManageProject,
    [OPERATION_OLD.CAN_VIEW_CREDITS_USAGE]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_OLD.PROJECT_NAME_EDITION]: [WORKSPACE_ADMIN_PERMISSION, PROJECT_ADMIN_PERMISSION],
    [OPERATION_OLD.USAGE_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
    [OPERATION_OLD.ANALYTICS_TAB]: [ORGANIZATION_ADMIN_PERMISSION, WORKSPACE_ADMIN_PERMISSION],
};
