# Default values for dex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of Pods to launch.
replicaCount: 1

image:
  # -- Repository to pull the container image from.
  registry: ghcr.io
  repository: dexidp
  name: dex:v2.41.1
  # -- Image [pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  pullPolicy: IfNotPresent

# -- Provide a name in place of the chart name for `app:` labels.
nameOverride: ""

# -- Provide a name to substitute for the full names of resources.
fullnameOverride: "impt-dex"

https:
  # -- Enable the HTTPS endpoint.
  enabled: false

grpc:
  # -- Enable the gRPC endpoint.
  # Read more in the [documentation](https://dexidp.io/docs/api/).
  enabled: false

# -- Application configuration.
# See the [official documentation](https://dexidp.io/docs/).
config: {}

isSMTPDefined: False

# -- Additional storage [volumes](https://kubernetes.io/docs/concepts/storage/volumes/) of a Pod.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#volumes) for details.
volumes: []

# -- Additional [volume mounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/) of a container.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#volumes) for details.
volumeMounts: []

# -- Configure a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) or a [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables) as environment variable sources for a Pod.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#environment-variables) for details.
envFrom: []

# -- Pass environment variables directly to a Pod.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#environment-variables) for details.
env: {}

serviceAccount:
  # -- Whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

rbac:
  # -- Specifies whether RBAC resources should be created.
  # If disabled, the operator is responsible for creating the necessary resources based on the templates.
  create: true

# -- Custom annotations for a Pod.
podAnnotations: {}

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#security-context) for details.
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

volumeSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

service:
  # -- Annotations to add to the Service.
  annotations: {}

  # -- Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
  type: ClusterIP

  ports:
    http:
      # -- HTTP service port
      port: 5556

      # -- (int) HTTP node port (when applicable)
      nodePort:

    grpc:
      # -- gRPC service port
      port: 5557

      # -- (int) gRPC node port (when applicable)
      nodePort:

# -- Container resource [requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#resources) for details.
# @default -- No requests or limits.
resources:
  limits:
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 256Mi

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Autoscaling configuration (see [values.yaml](values.yaml) for details).
# @default -- Disabled by default.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- [Node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) configuration.
nodeSelector: {}

# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for node taints.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#scheduling) for details.
tolerations: []

# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) configuration.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#scheduling) for details.
affinity: {}

global:
  security_headers: ''
  stripped_headers: ''
  storage_volume_claim_name_dex: ''
  enable_master_node_selector: true
  ldap_service_user_secret_name: ''

initResources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 100Mi
