exclude_dirs: ["*/tests/*"]
tests:
  [
    "B301",
    "B302",
    "B303",
    "B304",
    "B305",
    "B306",
    "B308",
    "B310",
    "B311",
    "B312",
    "B313",
    "B314",
    "B315",
    "B316",
    "B317",
    "B318",
    "B319",
    "B321",
    "B323",
    "B324",
    "B401",
    "B402",
    "B403",
    "B405",
    "B406",
    "B407",
    "B408",
    "B409",
    "B411",
    "B412",
    "B413",
    "B602",
    "B603"
  ]
