platform/services/credit:
  - platform/services/credit/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/credit_system/**
  - grpc_interfaces/account_service/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
platform/services/observability:
  - platform/services/observability/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
platform/services/onboarding:
  - platform/services/onboarding/**
  - libs/telemetry_tools/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/credit_system/**
  - grpc_interfaces/account_service/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
platform/services/notifier:
  - platform/services/notifier/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
platform/services/user_directory:
  - platform/services/user_directory/**
  - libs/telemetry_tools/**
  - libs/spicedb_tools/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/account_service/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
platform/services/account:
  - platform/services/account/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/account_service/**
  - grpc_interfaces/credit_system/**
  - Makefile.shared-go
  - Makefile.shared
  - builder-images/go-builder/Dockerfile
  - .github/workflows/component.yml
# IAI Services
interactive_ai/services/auto_train:
  - interactive_ai/services/auto_train/**
  - interactive_ai/libs/sc_sdk/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/feature_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/dataset_ie:
  - interactive_ai/services/dataset_ie/**
  - interactive_ai/libs/sc_sdk/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/job_submission/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/feature_tools/**
  - libs/kafka_tools/**
  - libs/fastapi_tools/**
  - Makefile.shared-python-uv
  - builder-images/python-builder/Dockerfile
  - Makefile.shared
  - .github/workflows/component.yml
interactive_ai/services/director:
  - interactive_ai/services/director/**
  - interactive_ai/libs/sc_sdk/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/job_submission/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/feature_tools/**
  - libs/kafka_tools/**
  - libs/fastapi_tools/**
  - libs/spicedb_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/inference_gateway:
  - interactive_ai/services/inference_gateway/**
  - interactive_ai/libs/go_sdk/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/model_mesh/**
  - grpc_interfaces/model_registration/**
  - grpc_interfaces/predict/**
  - Makefile.shared-go
  - Makefile.shared
  - builder-images/go-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/jobs:
  - interactive_ai/services/jobs/**
  - interactive_ai/libs/sc_sdk/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/credit_system/**
  - grpc_interfaces/job_submission/**
  - grpc_interfaces/job_update/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/kafka_tools/**
  - libs/spicedb_tools/**
  - libs/k8s_tools/**
  - libs/fastapi_tools/**
  - libs/feature_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/media:
  - interactive_ai/services/media/**
  - interactive_ai/libs/go_sdk/**
  - Makefile.shared-go
  - Makefile.shared
  - builder-images/go-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/mlflow_geti_store:
  - interactive_ai/services/mlflow_geti_store/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - .github/workflows/component.yml
interactive_ai/services/model_registration:
  - interactive_ai/services/model_registration/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/model_registration/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/project_ie:
  - interactive_ai/services/project_ie/**
  - interactive_ai/libs/sc_sdk/**
  - grpc_interfaces/pyproject.toml
  - grpc_interfaces/job_submission/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/feature_tools/**
  - libs/fastapi_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/resource:
  - interactive_ai/services/resource/**
  - interactive_ai/libs/sc_sdk/**
  - interactive_ai/libs/media_utils/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/feature_tools/**
  - libs/kafka_tools/**
  - libs/fastapi_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/services/visual_prompt:
  - interactive_ai/services/visual_prompt/**
  - interactive_ai/libs/sc_sdk/**
  - interactive_ai/libs/media_utils/**
  - libs/types/**
  - libs/telemetry_tools/**
  - libs/feature_tools/**
  - libs/kafka_tools/**
  - libs/fastapi_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - builder-images/python-builder/Dockerfile
  - .github/workflows/component.yml
interactive_ai/migration_job:
  - interactive_ai/migration_job/**
  - interactive_ai/data_migration/**
  - libs/telemetry_tools/**
  - Makefile.shared-python-uv
  - Makefile.shared
  - .github/workflows/component.yml
grpc_interfaces:
  - grpc_interfaces/**
  - libs/types/**

# Web Ui
web_ui:
  - web_ui/**
