version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"