# shared libraries
libs/fastapi_tools:
  - libs/fastapi_tools/**
  - libs/types/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/feature_tools:
  - libs/feature_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/grpc_interfaces:
  - libs/grpc_interfaces/**
  - libs/types/**
  - .github/libs-path-filters.yml
libs/k8s_tools:
  - libs/k8s_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/kafka_tools:
  - libs/kafka_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/spicedb_tools:
  - libs/spicedb_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/telemetry_tools:
  - libs/telemetry_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/types:
  - libs/types/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/configuration_tools:
  - libs/types/**
  - libs/Makefile**
  - libs/configuration_tools/**
  - .github/libs-path-filters.yml

# # libraries for interactive_ai
interactive_ai/libs/iai_core_go:
  - interactive_ai/libs/iai_core_go/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
interactive_ai/libs/media_utils:
  - interactive_ai/libs/media_utils/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
interactive_ai/libs/iai_core_py:
  - interactive_ai/libs/iai_core_py/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
interactive_ai/supported_models/:
  - interactive_ai/supported_models/**
  - interactive_ai/libs/supported_algorithm/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
