# shared libraries
libs/fastapi_tools:
  - libs/fastapi_tools/**
  - libs/types/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/feature_tools:
  - libs/feature_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/k8s_tools:
  - libs/k8s_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/kafka_tools:
  - libs/kafka_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
libs/spicedb_tools:
  - libs/spicedb_tools/**
  - libs/Makefile**
  - .github/libs-path-filters.yml
# Commented out libraries are failing tests and block PR from merging
# libs/telemetry_tools:
#   - libs/telemetry_tools/**
#   - libs/Makefile**
#   - .github/libs-path-filters.yml
# libs/types:
#   - libs/types/**
#   - libs/Makefile**
#   - .github/libs-path-filters.yml

# # libraries for interactive_ai
# interactive_ai/libs/go_sdk:
#   - interactive_ai/libs/go_sdk/**
#   - libs/Makefile**
#   - .github/libs-path-filters.yml
# interactive_ai/libs/media_utils:
#   - interactive_ai/libs/media_utils/**
#   - libs/Makefile**
#   - .github/libs-path-filters.yml
# interactive_ai/libs/sc_sdk:
#   - interactive_ai/libs/sc_sdk/**
#   - libs/Makefile**
#   - .github/libs-path-filters.yml
