include ../../../Makefile.shared-go

DOCKER_BUILD_CONTEXT := --build-context go_sdk=$(CWD)/interactive_ai/libs/go_sdk \
						--build-context modelmesh=$(CWD)/libs/grpc_interfaces/grpc_interfaces/model_mesh/go/pb \
						--build-context modelregistration=$(CWD)/libs/grpc_interfaces/grpc_interfaces/model_registration/go/pb \
						--build-context predict=$(CWD)/libs/grpc_interfaces/grpc_interfaces/predict/go/pb
