# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""add training_device column

Revision ID: 5ad4c6c3c077
Revises: 2d2b0c9a5c2c
Create Date: 2026-08-14 10:25:19.042018

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ad4c6c3c077"
down_revision: str | Sequence[str] | None = "2d2b0c9a5c2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_revisions", sa.Column("training_device", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_revisions", "training_device")
    # ### end Alembic commands ###
