# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
include ../../../Makefile.shared-python

COMPONENT_NAME = installer

DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \
 						--build-context geti_controller_chart=../geti_controller/.build
