include ../../Makefile.shared-workflows

COMPONENT_NAME       := project-ie-job

DOCKER_BUILD_CONTEXT := --build-context common=../common \
						--build-context libs=../../../../libs \
						--build-context sc_sdk=../../../../interactive_ai/libs/sc_sdk \
						--build-context media_utils=../../../../interactive_ai/libs/media_utils \
						--build-context data_migration=../../../../interactive_ai/data_migration \
						--build-context grpc_interfaces=../../../../grpc_interfaces \
						--build-context supported_models=../../../interactive_ai/supported_models \

test-component: venv
	@echo "test-component not available"
