include ../../Makefile.shared-workflows

COMPONENT_NAME       := project-ie-job

DOCKER_BUILD_CONTEXT := --build-context common=../common \
						--build-context libs=../../../../libs \
						--build-context sc_sdk=../../../../interactive_ai/libs/sc_sdk \
						--build-context media_utils=../../../../interactive_ai/libs/media_utils \
						--build-context data_migration=../../../../interactive_ai/data_migration \

test-component: venv
	@echo "test-component not available"
