# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

CWD = $(abspath $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST))))))
include $(CWD)/../../Makefile.shared

build-image:
	@echo "Building docker image for: ${BUILDER_IMAGE_NAME}"
	@echo ${DOCKER_EXTRA_ARGS}
	@docker build \
		${DOCKER_EXTRA_ARGS} \
		-t ${BUILDER_IMAGE_NAME}:${BUILDER_TAG} \
		-f ./Dockerfile .
