"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2022-2025 Intel Corporation
LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
"""
import builtins
import sys

import google.protobuf.descriptor
import google.protobuf.message

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class IDTokenSubject(google.protobuf.message.Message):
    """IDTokenSubject represents both the userID and connID which is returned
    as the "sub" claim in the ID Token.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    CONN_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    conn_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        conn_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["conn_id", b"conn_id", "user_id", b"user_id"]) -> None: ...

global___IDTokenSubject = IDTokenSubject
