#  INTEL CONFIDENTIAL
#
#  Copyright (C) 2023 Intel Corporation
#
#  This software and the related documents are Intel copyrighted materials, and your use of them is governed by
#  the express license under which they were provided to you ("License"). Unless the License provides otherwise,
#  you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
#  without Intel's prior written permission.
#
#  This software and the related documents are provided as is, with no express or implied warranties,
#  other than those that are expressly stated in the License.

# To meet Intel crypto compliance,
# ECDSA P-521 for the CA and P-384 for the leafs are recommended.
# Use 5y for the CA and 1y for the leafs.

# Unfortunately, Istio (Envoy) supports only P-256 ECDSA certificates,
# see https://github.com/envoyproxy/envoy/issues/10855

{{- $previous := lookup "v1" "Secret" .Release.Namespace "custom-tls" -}}
{{- if not $previous }}
  {{- if and .Values.tls.key_file .Values.tls.cert_file }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: custom-tls
  namespace: {{ include "gateway.namespace" . }}
data:
  tls.key: {{ .Values.tls.key_file | quote }}
  tls.crt: {{ .Values.tls.cert_file | quote }}
  {{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-tls
  namespace: {{ include "gateway.namespace" . }}
spec:
  secretName: custom-tls
  duration: 4380h0m0s
  renewBefore: 24h0m0s
  dnsNames:
    - Intel Geti
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: ClusterIssuer
    group: cert-manager.io
  {{- end }}
{{- else }}
# do nothing
{{- end }}
