#  INTEL CONFIDENTIAL
#
#  Copyright (C) 2023 Intel Corporation
#
#  This software and the related documents are Intel copyrighted materials, and your use of them is governed by
#  the express license under which they were provided to you ("License"). Unless the License provides otherwise,
#  you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
#  without Intel's prior written permission.
#
#  This software and the related documents are provided as is, with no express or implied warranties,
#  other than those that are expressly stated in the License.

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: platform-allow-api-keys-access
  namespace: {{ include "gateway.namespace" . }}
spec:
  selector:
    matchLabels:
      istio: gateway
  action: ALLOW
  rules:
    - when:
      - key: request.headers[X-Api-Key]
        values: [ "geti_pat_*" ]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: platform-allow-anonymous-auth-policy
  namespace: {{ include "gateway.namespace" . }}
spec:
  selector:
    matchLabels:
      istio: gateway
  action: ALLOW
  {{- with .Values.anonymous_auth_policy.rules }}
  rules:
    {{ toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-external-token-auth-policy
  namespace: {{ include "gateway.namespace" . }}
spec:
  selector:
    matchLabels:
      istio: gateway
  action: ALLOW
  {{- with .Values.external_token_auth_policy.rules }}
  rules:
    {{ toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: platform-external-jwt-verifier
  namespace: {{ include "gateway.namespace" . }}
spec:
  selector:
    matchLabels:
      istio: gateway
  jwtRules:
  - forwardOriginalToken: true
    issuer: {{ .Values.jwtRules.issuer }}
    jwksUri: {{ .Values.jwtRules.jwksUri }}
    audiences: {{ .Values.jwtRules.audiences }}
