-- Copyright (C) 2022-2025 Intel Corporation
-- LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

CREATE TABLE organization (
    id VARCHAR(36) NOT NULL,
    name TEXT NOT NULL,
    country VARCHAR(3) NOT NULL,
    location TEXT,
    type VARCHAR(3) NOT NULL,
    cell_id TEXT NOT NULL,
    status VARCHAR(3) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(36) NOT NULL,
    modified_at TIMESTAMP,
    modified_by VARCHAR(36),
    PRIMARY KEY(id)
);

CREATE TABLE organization_status_history (
    id SERIAL PRIMARY KEY,
    status VARCHAR(3) NOT NULL,
    organization_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(36) NOT NULL,
    FOREIGN KEY(organization_id) REFERENCES organization(id) ON DELETE CASCADE
);

CREATE TABLE workspace (
    id VARCHAR(36) NOT NULL,
    name TEXT NOT NULL,
    organization_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(36) NOT NULL,
    modified_at TIMESTAMP,
    modified_by VARCHAR(36),
    PRIMARY KEY(id),
    FOREIGN KEY(organization_id) REFERENCES organization(id)
);

CREATE TABLE "user" (
    id VARCHAR(36) PRIMARY KEY,
    first_name TEXT NOT NULL,
    second_name TEXT NOT NULL,
    email TEXT NOT NULL,
    external_id TEXT,
    photo_location TEXT,
    country VARCHAR(3) NOT NULL,
    registration_token TEXT,
    last_successful_login TIMESTAMP,
    created_at TIMESTAMP,
    created_by VARCHAR(36) NOT NULL,
    modified_at TIMESTAMP,
    modified_by VARCHAR(36)
);

CREATE TABLE user_status (
    id SERIAL PRIMARY KEY,
    status VARCHAR(3) NOT NULL,
    organization_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP,
    created_by VARCHAR(36) NOT NULL,
    modified_at TIMESTAMP,
    modified_by VARCHAR(36),
    FOREIGN KEY(organization_id) REFERENCES organization(id),
    FOREIGN KEY(user_id) REFERENCES "user"(id)
);

CREATE TABLE domain (
    id SERIAL PRIMARY KEY,
    domain_code VARCHAR(30) NOT NULL,
    domain_name TEXT NOT NULL,
    code VARCHAR(3) NOT NULL,
    value VARCHAR(60) NOT NULL,
    meaning TEXT NOT NULL,
    valid BOOLEAN NOT NULL,
    UNIQUE (domain_code, code)
);

INSERT INTO domain (domain_code, domain_name, code, value, meaning, valid) VALUES
('USER_STATUSES', 'available status of a user', 'RGS', 'REGISTERED', 'user was registered and is waiting for activation', true),
('USER_STATUSES', 'available status of a user', 'ACT', 'ACTIVE', 'user is active', true),
('USER_STATUSES', 'available status of a user', 'SSP', 'SUSPENDED', 'user is suspended', false),
('USER_STATUSES', 'available status of a user', 'DEL', 'DELETED', 'user was deleted', false);

INSERT INTO domain (domain_code, domain_name, code, value, meaning, valid) VALUES
('ORGANIZATION_TYPES', 'available types of an organization', 'B2B', 'B2B', 'Business To Business', true),
('ORGANIZATION_TYPES', 'available types of an organization', 'B2C', 'B2C', 'Business To Client', true);

INSERT INTO domain (domain_code, domain_name, code, value, meaning, valid) VALUES
('ORGANIZATION_STATUSES', 'available status of an organization', 'ACT', 'ACTIVE', 'organization is active', true),
('ORGANIZATION_STATUSES', 'available status of an organization', 'SSP', 'SUSPENDED', 'organization is suspended', false),
('ORGANIZATION_STATUSES', 'available status of an organization', 'DEL', 'DELETED', 'organization was deleted', false);

INSERT INTO domain (domain_code, domain_name, code, value, meaning, valid) VALUES
('ROLE_OPERATIONS', 'list of operations that might be performed on user’s roles definitions', 'ADD', 'ADD', 'add a new role to a user', true),
('ROLE_OPERATIONS', 'list of operations that might be performed on user’s roles definitions', 'DEL', 'DELETE', 'removes a certain user’s role', false);

INSERT INTO domain (domain_code, domain_name, code, value, meaning, valid) VALUES
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AFG', 'Afghanistan', 'Afghanistan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ALA', 'Åland Islands', 'Åland Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ALB', 'Albania', 'Albania', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'DZA', 'Algeria', 'Algeria', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ASM', 'American Samoa', 'American Samoa', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AND', 'Andorra', 'Andorra', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AGO', 'Angola', 'Angola', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AIA', 'Anguilla', 'Anguilla', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ATA', 'Antarctica', 'Antarctica', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ATG', 'Antigua and Barbuda', 'Antigua and Barbuda', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ARG', 'Argentina', 'Argentina', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ARM', 'Armenia', 'Armenia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ABW', 'Aruba', 'Aruba', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AUS', 'Australia', 'Australia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AUT', 'Austria', 'Austria', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'AZE', 'Azerbaijan', 'Azerbaijan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BHS', 'Bahamas', 'Bahamas', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BHR', 'Bahrain', 'Bahrain', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BGD', 'Bangladesh', 'Bangladesh', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BRB', 'Barbados', 'Barbados', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BLR', 'Belarus', 'Belarus', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BEL', 'Belgium', 'Belgium', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BLZ', 'Belize', 'Belize', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BEN', 'Benin', 'Benin', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BMU', 'Bermuda', 'Bermuda', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BTN', 'Bhutan', 'Bhutan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BOL', 'Bolivia', 'Bolivia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BIH', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BWA', 'Botswana', 'Botswana', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BVT', 'Bouvet Island', 'Bouvet Island', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BRA', 'Brazil', 'Brazil', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BRN', 'Brunei Darussalam', 'Brunei Darussalam', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BGR', 'Bulgaria', 'Bulgaria', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BFA', 'Burkina Faso', 'Burkina Faso', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BDI', 'Burundi', 'Burundi', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CPV', 'Cape Verde', 'Cape Verde', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KHM', 'Cambodia', 'Cambodia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CMR', 'Cameroon', 'Cameroon', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CAN', 'Canada', 'Canada', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CYM', 'Cayman Islands', 'Cayman Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CAF', 'Central African Republic', 'Central African Republic', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TCD', 'Chad', 'Chad', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CHL', 'Chile', 'Chile', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CHN', 'China', 'China', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CXR', 'Christmas Island', 'Christmas Island', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CCK', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'COL', 'Colombia', 'Colombia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'COM', 'Comoros', 'Comoros', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'COG', 'Congo', 'Congo', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'COD', 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'COK', 'Cook Islands', 'Cook Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CRI', 'Costa Rica', 'Costa Rica', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CIV', 'Côte d''Ivoire', 'Côte d''Ivoire', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'HRV', 'Croatia', 'Croatia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CUB', 'Cuba', 'Cuba', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CUW', 'Curaçao', 'Curaçao', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CYP', 'Cyprus', 'Cyprus', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CZE', 'Czechia', 'Czechia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'DNK', 'Denmark', 'Denmark', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'DJI', 'Djibouti', 'Djibouti', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'DMA', 'Dominica', 'Dominica', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'DOM', 'Dominican Republic', 'Dominican Republic', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ECU', 'Ecuador', 'Ecuador', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'EGY', 'Egypt', 'Egypt', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SLV', 'El Salvador', 'El Salvador', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinea', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ERI', 'Eritrea', 'Eritrea', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'EST', 'Estonia', 'Estonia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SWZ', 'Eswatini', 'Eswatini', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ETH', 'Ethiopia', 'Ethiopia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'FLK', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'FRO', 'Faroe Islands', 'Faroe Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'FJI', 'Fiji', 'Fiji', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'FIN', 'Finland', 'Finland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'FRA', 'France', 'France', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GUF', 'French Guiana', 'French Guiana', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PYF', 'French Polynesia', 'French Polynesia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ATF', 'French Southern Territories', 'French Southern Territories', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GAB', 'Gabon', 'Gabon', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GMB', 'Gambia', 'Gambia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GEO', 'Georgia', 'Georgia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'DEU', 'Germany', 'Germany', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GHA', 'Ghana', 'Ghana', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GIB', 'Gibraltar', 'Gibraltar', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GRC', 'Greece', 'Greece', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GRL', 'Greenland', 'Greenland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GRD', 'Grenada', 'Grenada', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GLP', 'Guadeloupe', 'Guadeloupe', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GUM', 'Guam', 'Guam', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GTM', 'Guatemala', 'Guatemala', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GGY', 'Guernsey', 'Guernsey', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GIN', 'Guinea', 'Guinea', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GNB', 'Guinea-Bissau', 'Guinea-Bissau', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GUY', 'Guyana', 'Guyana', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'HTI', 'Haiti', 'Haiti', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VAT', 'Holy See', 'Holy See', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'HND', 'Honduras', 'Honduras', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'HKG', 'Hong Kong', 'Hong Kong', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'HUN', 'Hungary', 'Hungary', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ISL', 'Iceland', 'Iceland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IND', 'India', 'India', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IDN', 'Indonesia', 'Indonesia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IRN', 'Iran (Islamic Republic of)', 'Iran (Islamic Republic of)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IRQ', 'Iraq', 'Iraq', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IRL', 'Ireland', 'Ireland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'IMN', 'Isle of Man', 'Isle of Man', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ISR', 'Israel', 'Israel', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ITA', 'Italy', 'Italy', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'JAM', 'Jamaica', 'Jamaica', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'JPN', 'Japan', 'Japan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'JEY', 'Jersey', 'Jersey', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'JOR', 'Jordan', 'Jordan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KAZ', 'Kazakhstan', 'Kazakhstan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KEN', 'Kenya', 'Kenya', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KIR', 'Kiribati', 'Kiribati', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PRK', 'Korea (Democratic People''s Republic of)', 'Korea (Democratic People''s Republic of)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KOR', 'Korea, Republic of', 'Korea, Republic of', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KWT', 'Kuwait', 'Kuwait', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KGZ', 'Kyrgyzstan', 'Kyrgyzstan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LAO', 'Lao People''s Democratic Republic', 'Lao People''s Democratic Republic', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LVA', 'Latvia', 'Latvia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LBN', 'Lebanon', 'Lebanon', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LSO', 'Lesotho', 'Lesotho', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LBR', 'Liberia', 'Liberia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LBY', 'Libya', 'Libya', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LIE', 'Liechtenstein', 'Liechtenstein', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LTU', 'Lithuania', 'Lithuania', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LUX', 'Luxembourg', 'Luxembourg', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MAC', 'Macao', 'Macao', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MKD', 'North Macedonia', 'North Macedonia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MDG', 'Madagascar', 'Madagascar', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MWI', 'Malawi', 'Malawi', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MYS', 'Malaysia', 'Malaysia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MDV', 'Maldives', 'Maldives', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MLI', 'Mali', 'Mali', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MLT', 'Malta', 'Malta', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MHL', 'Marshall Islands', 'Marshall Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MTQ', 'Martinique', 'Martinique', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MRT', 'Mauritania', 'Mauritania', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MUS', 'Mauritius', 'Mauritius', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MYT', 'Mayotte', 'Mayotte', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MEX', 'Mexico', 'Mexico', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'FSM', 'Micronesia (Federated States of)', 'Micronesia (Federated States of)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MDA', 'Moldova, Republic of', 'Moldova, Republic of', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MCO', 'Monaco', 'Monaco', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MNG', 'Mongolia', 'Mongolia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MNE', 'Montenegro', 'Montenegro', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MSR', 'Montserrat', 'Montserrat', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MAR', 'Morocco', 'Morocco', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MOZ', 'Mozambique', 'Mozambique', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MMR', 'Myanmar', 'Myanmar', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NAM', 'Namibia', 'Namibia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NRU', 'Nauru', 'Nauru', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NPL', 'Nepal', 'Nepal', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NLD', 'Netherlands', 'Netherlands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NCL', 'New Caledonia', 'New Caledonia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NZL', 'New Zealand', 'New Zealand', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NIC', 'Nicaragua', 'Nicaragua', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NER', 'Niger', 'Niger', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NGA', 'Nigeria', 'Nigeria', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NIU', 'Niue', 'Niue', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NFK', 'Norfolk Island', 'Norfolk Island', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MNP', 'Northern Mariana Islands', 'Northern Mariana Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'NOR', 'Norway', 'Norway', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'OMN', 'Oman', 'Oman', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PAK', 'Pakistan', 'Pakistan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PLW', 'Palau', 'Palau', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PSE', 'Palestine, State of', 'Palestine, State of', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PAN', 'Panama', 'Panama', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PNG', 'Papua New Guinea', 'Papua New Guinea', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PRY', 'Paraguay', 'Paraguay', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PER', 'Peru', 'Peru', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PHL', 'Philippines', 'Philippines', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PCN', 'Pitcairn', 'Pitcairn', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'POL', 'Poland', 'Poland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PRT', 'Portugal', 'Portugal', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'PRI', 'Puerto Rico', 'Puerto Rico', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'QAT', 'Qatar', 'Qatar', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'REU', 'Réunion', 'Réunion', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ROU', 'Romania', 'Romania', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'RUS', 'Russian Federation', 'Russian Federation', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'RWA', 'Rwanda', 'Rwanda', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'BLM', 'Saint Barthélemy', 'Saint Barthélemy', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'KNA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LCA', 'Saint Lucia', 'Saint Lucia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'MAF', 'Saint Martin (French part)', 'Saint Martin (French part)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SPM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'WSM', 'Samoa', 'Samoa', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SMR', 'San Marino', 'San Marino', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'STP', 'Sao Tome and Principe', 'Sao Tome and Principe', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SAU', 'Saudi Arabia', 'Saudi Arabia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SEN', 'Senegal', 'Senegal', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SRB', 'Serbia', 'Serbia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SYC', 'Seychelles', 'Seychelles', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SLE', 'Sierra Leone', 'Sierra Leone', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SGP', 'Singapore', 'Singapore', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SVK', 'Slovakia', 'Slovakia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SVN', 'Slovenia', 'Slovenia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SLB', 'Solomon Islands', 'Solomon Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SOM', 'Somalia', 'Somalia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ZAF', 'South Africa', 'South Africa', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SSD', 'South Sudan', 'South Sudan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ESP', 'Spain', 'Spain', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'LKA', 'Sri Lanka', 'Sri Lanka', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SDN', 'Sudan', 'Sudan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SUR', 'Suriname', 'Suriname', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SWE', 'Sweden', 'Sweden', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'CHE', 'Switzerland', 'Switzerland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'SYR', 'Syrian Arab Republic', 'Syrian Arab Republic', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TWN', 'Taiwan, Province of China', 'Taiwan, Province of China', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TJK', 'Tajikistan', 'Tajikistan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TZA', 'Tanzania, United Republic of', 'Tanzania, United Republic of', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'THA', 'Thailand', 'Thailand', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TLS', 'Timor-Leste', 'Timor-Leste', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TGO', 'Togo', 'Togo', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TKL', 'Tokelau', 'Tokelau', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TON', 'Tonga', 'Tonga', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TUN', 'Tunisia', 'Tunisia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TUR', 'Turkey', 'Turkey', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TKM', 'Turkmenistan', 'Turkmenistan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'TUV', 'Tuvalu', 'Tuvalu', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'UGA', 'Uganda', 'Uganda', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'UKR', 'Ukraine', 'Ukraine', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ARE', 'United Arab Emirates', 'United Arab Emirates', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'GBR', 'United Kingdom of Great Britain and Northern Ireland', 'United Kingdom of Great Britain and Northern Ireland', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'USA', 'United States of America', 'United States of America', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'URY', 'Uruguay', 'Uruguay', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'UZB', 'Uzbekistan', 'Uzbekistan', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VUT', 'Vanuatu', 'Vanuatu', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuela (Bolivarian Republic of)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VNM', 'Viet Nam', 'Viet Nam', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VGB', 'Virgin Islands (British)', 'Virgin Islands (British)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'VIR', 'Virgin Islands (U.S.)', 'Virgin Islands (U.S.)', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'WLF', 'Wallis and Futuna', 'Wallis and Futuna', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ESH', 'Western Sahara', 'Western Sahara', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'YEM', 'Yemen', 'Yemen', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ZMB', 'Zambia', 'Zambia', true),
('COUNTRY', 'Country and its code according to ISO 3166 norm', 'ZWE', 'Zimbabwe', 'Zimbabwe', true);
