// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

import { ReactNode } from 'react';

import { screen, waitForElementToBeRemoved } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { render } from 'test-utils/render';

import { toast } from './toast.component';

const TriggerToast = ({ id, message }: { id?: string; message: ReactNode }) => (
    <button onClick={() => toast({ id, type: 'success', message })}>Show toast</button>
);

describe('toast', () => {
    it('closes a toast whose id was generated by sonner', async () => {
        render(<TriggerToast message={<span>Model training started successfully.</span>} />);

        await userEvent.click(screen.getByRole('button', { name: 'Show toast' }));

        expect(await screen.findByLabelText('toast')).toBeVisible();

        await userEvent.click(screen.getByRole('button', { name: 'Close toast' }));

        await waitForElementToBeRemoved(() => screen.queryByLabelText('toast'));
    });

    it('closes a toast with an explicit id', async () => {
        render(<TriggerToast id={'custom-toast-id'} message={'Quantization job started.'} />);

        await userEvent.click(screen.getByRole('button', { name: 'Show toast' }));

        expect(await screen.findByLabelText('toast')).toBeVisible();

        await userEvent.click(screen.getByRole('button', { name: 'Close toast' }));

        await waitForElementToBeRemoved(() => screen.queryByLabelText('toast'));
    });
});
