# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

{{- if .Values.global.istio_ambient_mesh }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
spec:
  parentRefs:
    - name: {{ .Values.global.istio_gateway_name }}
      kind: Gateway
      namespace: {{ .Values.global.istio_ingress_namespace }}
#  hostnames:
#    - "*.intel.com"  # only for SaaS
  rules:
    - matches:
        - path:
            type: RegularExpression
            value: /api/v([^/]*)/organizations/([^/]*)/status$
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/(predictions|train|optimize|settings|datasets/active|configuration)(/|$)(.*)
        - path:
            type: RegularExpression
            value: /api/v([^/]*)/(organizations/([^/]*)/workspaces/([^/]*)/projects/([^/]*)/)?status$
        - path:
            type: RegularExpression
            value: /api/v([^/]*)/(organizations/([^/]*)/workspaces/([^/]*)/projects/([^/]*)/)?incremental_learning_status$
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/tests($|/([^/]*)$)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/predict(/status)?
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*):train
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/model_groups/(.*)/models/(.*)optimize
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/.*/supported_algorithms
      backendRefs:
        - name: {{ .Release.Namespace }}-{{ .Chart.Name }}
          port: {{ .Values.service.ports.director.port }}
{{- end}}
