#  INTEL CONFIDENTIAL
#
#  Copyright (C) 2025 Intel Corporation
#
#  This software and the related documents are Intel copyrighted materials, and your use of them is governed by
#  the express license under which they were provided to you ("License"). Unless the License provides otherwise,
#  you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
#  without Intel's prior written permission.
#
#  This software and the related documents are provided as is, with no express or implied warranties,
#  other than those that are expressly stated in the License.

{{- if .Values.global.istio_ambient_mesh }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
spec:
  parentRefs:
    - name: {{ .Values.global.istio_gateway_name }}
      kind: Gateway
      namespace: {{ .Values.global.istio_ingress_namespace }}
#  hostnames:
#    - "*.intel.com"  # only for SaaS
  rules:
    - matches:
        - path:
            type: RegularExpression
            value: /api/v([^/]*)/organizations/([^/]*)/status$
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/(predictions|train|optimize|settings|datasets/active|configuration)(/|$)(.*)
        - path:
            type: RegularExpression
            value: /api/v([^/]*)/(organizations/([^/]*)/workspaces/([^/]*)/projects/([^/]*)/)?status$
        - path:
            type: RegularExpression
            value: /api/v([^/]*)/(organizations/([^/]*)/workspaces/([^/]*)/projects/([^/]*)/)?incremental_learning_status$
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/tests($|/([^/]*)$)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/predict(/status)?
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*):train
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/model_groups/(.*)/models/(.*)optimize
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/.*/supported_algorithms
      backendRefs:
        - name: {{ .Release.Namespace }}-{{ .Chart.Name }}
          port: {{ .Values.service.ports.director.port }}
{{- end}}
