id: instance-segmentation-eomt-large-640
name: EoMT-Large-640
license: MIT
pretrained_weights:
  source: huggingface
  repo_id: tue-mps/coco_instance_eomt_large_640
  revision: a43666870d47a7010bfea2c4554f7ca829714558
description: "EoMT-Large repurposes a DINOv2 ViT-L encoder for efficient instance segmentation without a task-specific decoder."
stats:
  gigaflops: 669
  trainable_parameters: 316.641361
  benchmark_metrics:
    coco_map_50_95: 45.2
capabilities:
  xai: false
  tiling: false
hyperparameters:
  training:
    learning_rate: 0.0001
    weight_decay: 0.05
    input_size_width: 640
    input_size_height: 640
