id: instance-segmentation-mask2former-swin-l
name: Mask2Former-Swin-L
license: CC BY-NC 4.0
pretrained_weights:
  source: huggingface
  repo_id: facebook/mask2former-swin-large-coco-instance
  revision: d8f2bced294e26108e73d48bb7a7094c9bc7c71d
description: "Mask2Former with a Swin-L backbone predicts instance masks using masked attention and multi-scale features."
stats:
  gigaflops: 1919.1
  trainable_parameters: 215.525061
  benchmark_metrics:
    coco_map_50_95: 50.1
capabilities:
  xai: false
  tiling: false
hyperparameters:
  training:
    learning_rate: 0.00005
    weight_decay: 0.05
