quiet: False
disable-version-string: True
with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "mock/{{.InterfaceDirRelative}}"
packages:
  media_microservice/service:
    config:
      all: True
  media_microservice/usecase:
    config:
      all: True
