all: false
dir: "{{.InterfaceDir}}"
filename: mocks.go
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
template: testify
packages:
  media/app/service:
    config:
      all: True
  media/app/usecase:
    config:
      all: True
