# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-go

DOCKER_BUILD_CONTEXT := --build-context iai_core=$(CWD)/interactive_ai/libs/iai_core_go
