# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-go

DOCKER_BUILD_CONTEXT := --build-context go_sdk=$(CWD)/interactive_ai/libs/go_sdk
