#  INTEL CONFIDENTIAL
#
#  Copyright (C) 2023 Intel Corporation
#
#  This software and the related documents are Intel copyrighted materials, and your use of them is governed by
#  the express license under which they were provided to you ("License"). Unless the License provides otherwise,
#  you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
#  without Intel's prior written permission.
#
#  This software and the related documents are provided as is, with no express or implied warranties,
#  other than those that are expressly stated in the License.

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-gateway
  namespace: {{ include "gateway.namespace" . }}
spec:
  duration: 4380h0m0s
  renewBefore: 24h0m0s
  secretName: geti-jwt-secret
  dnsNames:
    - istio-gateway
    - istio-gateway.{{ include "gateway.namespace" . }}.svc.cluster
  privateKey:
    algorithm: RSA
    size: 4096
    encoding: PKCS8
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuerRef.name }}
