# Default values for modelmesh-serving.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  enable_local_image_pull_secret: false 
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc
  kubectl:
    registry: docker.io
    repository: bitnami
    name: kubectl:1.31.0

feature_flags_data: {}

replicaCount: 1

controller:
  image: 
    registry: docker.io
    repository: kserve
    name: modelmesh-controller:v0.12.0

modelmesh: 
  image:
    registry: docker.io
    repository: kserve
    name: modelmesh
    tag: v0.12.0

restProxyImage: kserve/rest-proxy
restProxyImageTag: v0.12.0

runtimeadapter:
  image:
    registry: docker.io
    repository: kserve
    name: modelmesh-runtime-adapter
    tag: v0.12.0

modelRegistration:
  namespace: impt
  serviceAccount: impt-modelregistration

controllerResources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    memory: 512Mi

autoscalerEnabled: false
autoscalerResources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 256Mi

s3_endpoint_url: "http://impt-seaweed-fs.impt.svc.cluster.local:8333"
s3_default_bucket: modelmesh
s3_region: eu-central-1

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

certificate:
  secret_name: modelmesh-webhook-server-cert
  issuerRef:
    name: ca-issuer
