# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

TEST_PHOTO_FILEPATH = "data/photo.png"

DEFAULT_MAX_FIELD_SIZE = 200
DEFAULT_SHORT_FIELD_SIZE = 3
DEFAULT_MAX_EMAIL_SIZE = 64
