apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "auth-proxy.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "auth-proxy.name" . }}
  {{- if or .Values.global.running_on_vm (eq .Values.global.installation_profile "lite") }}
  minReplicas: 1
  maxReplicas: 1
  {{- else }}
  minReplicas: 2
  maxReplicas: 20
  {{- end }}
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: {{ .Chart.Name }}
        target:
          type: Utilization
          averageUtilization: 70
    - type: ContainerResource
      containerResource:
        name: memory
        container: {{ .Chart.Name }}
        target:
          type: Utilization
          averageUtilization: 70
