# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  duration: 4380h0m0s
  renewBefore: 24h0m0s
  secretName: {{ .Values.certificate.secretName }}
  dnsNames:
    - auth-proxy
  privateKey:
    algorithm: RSA
    size: 4096
    encoding: PKCS8
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuerRef.name }}
