apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth-proxy.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "auth-proxy.labels" . | nindent 6 }}
  minAvailable: 1
