---
apiVersion: batch/v1
kind: Job
metadata:
  name: "init-job-{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ .Chart.Name }}
spec:
  backoffLimit: 3
  template:
    metadata:
      {{- if not .Values.global.istio_ambient_mesh }}
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      {{- end }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}-{{ .Chart.Name }}
      restartPolicy: Never
      initContainers:
        - name: init-mongodb
          image: "{{ .Values.global.busybox.registry }}/{{ if .Values.global.busybox.repository }}{{ .Values.global.busybox.repository }}/{{ end }}{{ .Values.global.busybox.name }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: [ 'sh', '-c', "until nc -w 5 -z {{ .Release.Namespace }}-mongodb 27017; do echo wait...; sleep 2; done;" ]
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.initResources | nindent 12 }}     
      containers:
        - name: "mongodb-user"
          image: "{{ .Values.global.registry_address }}/{{ .Values.global.docker_namespace }}/migration-job:{{ .Values.global.tag | default .Chart.AppVersion }}"
          command: [ "/bin/sh", "-c" ]
          args:
            - >-
              mongodb_create_service_user;
              retVal=$?;
              {{- if not .Values.global.istio_ambient_mesh }}
              curl -XPOST 127.0.0.1:15020/quitquitquit;
              {{- end }}
              exit $retVal
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
          env:
            - name: DATABASE_ADDRESS
              value: mongodb://{{ .Release.Namespace }}-mongodb:27017/
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Namespace }}-mongodb"
                  key: "mongodb-username"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Namespace }}-mongodb"
                  key: "mongodb-password"
            - name: DATABASE_USERNAME_SERVICE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Namespace }}-mongodb"
                  key: "{{ .Chart.Name }}-mongodb-username"
            - name: DATABASE_PASSWORD_SERVICE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Namespace }}-mongodb"
                  key: "{{ .Chart.Name }}-mongodb-password"
            - name: SERVICE_USER_ALL_DB_ROLES
              value: "readWriteAnyDatabase"
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
