title: Metadata of train job
type: object
description: Additional information associated with the train job
properties:
  task:
    type: object
    description: Information about the task associated with the job, if any
    properties:
      name:
        type: string
        description: Name of the task
      model_template_id:
        type: string
        description: Identifier of the model template used by the task
      model_architecture:
        type: string
        description: Neural network architecture used for the model
      dataset_storage_id:
        $ref: "../../mongo_id.yaml"
      task_id:
        $ref: "../../mongo_id.yaml"
  project:
    type: object
    description: Information about the project associated with the job
    properties:
      id:
        $ref: "../../mongo_id.yaml"
      name:
        type: string
        description: Name of the project
  trained_model:
    type: object
    description: Information about the trained model
    properties:
      model_storage_id:
        $ref: "../../mongo_id.yaml"
      model_id:
        $ref: "../../mongo_id.yaml"
      model_activated:
        type: boolean
        description: Whether the model became the active one after training
