---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opa.name" . }}
  namespace: {{ .Values.namespace.opa }}
  labels:
    {{- include "opa.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
