enabled:
  migration_job: true
  auto_train: true
  dataset_ie: true
  director: true
  inference_gateway: true
  jobs: true
  media: true
  mlflow_geti_store: true
  model_registration: true
  project_ie: true
  resource: true
  visual_prompt: true
  account: true
  auth_proxy: true
  credit: false
  initial_user: true
  notifier: false
  observability: true
  onboarding: false
  platform_cleaner: true
  user_directory: true
  weight_uploader: true
  web_ui: true
  configuration: true
  jobs_execution_namespace: true
  modelmesh_serving: true
  opa_bundle: true
  telemetry_compression: true
