{{- if or (.Values.serviceAccount.create) (.Values.presets.kubeletMetrics.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
