apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "onboarding-service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "onboarding-service.labels" . | nindent 6 }}
  minAvailable: 1
