apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "onboarding-service.name" . }}
  labels: {{- include "onboarding-service.labels" . | nindent 4 }}
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "onboarding-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.onboarding_svc.port }}
      targetPort: {{ .Values.onboarding_svc.target_port }}
      protocol: TCP
      appProtocol: http
