apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ include "onboarding-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onboarding-service.labels" . | nindent 4 }}
