{{- if .Values.common.flyteNamespaceTemplate.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "flyte.namespace" . }}
annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "1"
spec:
  finalizers:
  - kubernetes
{{- end }}
