{{- $keys := dict }}
{{- range $service := .Values.services }}
{{- $service_name := $service.name }}
{{- $access_key := $service.access_key }}
{{- $secret_key := $service.secret_key }}
{{- $service_access_key := default (randAlphaNum 20) $access_key }}
{{- $service_secret_key := default (randAlphaNum 40) $secret_key }}
{{- $_ := set $keys (printf "%s_access_key" $service_name) $service_access_key }}
{{- $_ := set $keys (printf "%s_secret_key" $service_name) $service_secret_key }}
{{- end }}

{{- $namespaceList := list .Release.Namespace (include "flyteworkflow.namespace" .) }}
{{- range $namespace := $namespaceList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seaweed-fs.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    {{- include "seaweed-fs.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $service := $.Values.services }}
  {{- $service_name := $service.name }}
  {{ $service_name }}_access_key: {{ index $keys (printf "%s_access_key" $service_name) }}
  {{ $service_name }}_secret_key: {{ index $keys (printf "%s_secret_key" $service_name) }}
  {{- end }}
  weed.json: |
    {
      "identities": [
        {{- $services := $.Values.services -}}
        {{- range $index, $identity := $services }}
        {
          "name": "{{ $identity.name }}",
          "credentials": [
            {
              "accessKey": "{{ index $keys (printf "%s_access_key" $identity.name) }}",
              "secretKey": "{{ index $keys (printf "%s_secret_key" $identity.name) }}"
            }
          ],
          "actions": {{ $identity.actions | toJson }}
        }{{ if not (eq $index (sub (len $services) 1)) }},{{ end }}
        {{- end }}
      ]
    }
---
{{- end }}
