{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}
  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-kafka-proxy
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
