image: jobs-ms
imagePullPolicy: IfNotPresent
replicas: 1

serviceAccount:
  create: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

initResources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 100Mi

resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    memory: 500Mi

service:
  type: ClusterIP
  ports:
    grpc: 50051

global:
  logging_config_dir: ''
  storage_volume_claim_name_jobs: data-storage-volume-claim
  docker_namespace: geti
  workflow_versions: v1
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc
  kubectl:
    registry: docker.io
    repository: bitnami
    name: kubectl:1.31.0
  debian:
    registry: docker.io
    repository: bitnami
    name: bitnami-shell:11-debian-11-r136

jobs_templates_dir: /mnt/jobs_templates
jobs_templates_file: jobs_templates.yaml
