{{- if eq (default "standard" .Values.global.installation_profile) "standard" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  minReplicas: 1
  {{- if .Values.global.running_on_vm }}
  maxReplicas: 1
  {{- else }}
  maxReplicas: 20
  {{- end }}
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: {{ .Chart.Name }}
        target:
          type: Utilization
          averageUtilization: 70
    - type: ContainerResource
      containerResource:
        name: memory
        container: {{ .Chart.Name }}
        target:
          type: Utilization
          averageUtilization: 80
{{- end }}