---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seaweed-fs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-fs.labels" . | nindent 4 }}
data:
  filer.toml: |
    [leveldb3]
    enabled = true
    dir = "/data/filerldb3"
