---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seaweed-fs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweed-fs.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
