apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jobs-scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "jobs-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jobs-scheduler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}-{{ .Chart.Name }}
      initContainers:
        # [mTLS STRICT] The kubectl-wait init container is used to wait for the init job that is related to this specific component.
        # This is a workaround to address the issue that arises when using Istio mTLS strict mode and init containers
        # that do not have the Istio proxy sidecar
        - name: "kubectl-wait"
          image: "{{ .Values.global.kubectl.registry }}/{{ if .Values.global.kubectl.repository }}{{ .Values.global.kubectl.repository }}/{{ end }}{{ .Values.global.kubectl.name }}"
          command: [ "/bin/bash", "-c" ]
          args:
            - >-
              kubectl wait jobs
              --timeout=1200s
              --for=condition=complete
              --namespace {{ .Release.Namespace }}
              init-job-{{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.initResources | nindent 12 }}
        - name: init-kafka
          image: "{{ .Values.global.busybox.registry }}/{{ if .Values.global.busybox.repository }}{{ .Values.global.busybox.repository }}/{{ end }}{{ .Values.global.busybox.name }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ['sh', '-c', 'until nc -w 5 -z {{ .Release.Namespace }}-kafka 9092; do echo wait...; sleep 2; done;']
          resources:
            {{ toYaml .Values.initResources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: &containerName {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.ports.grpc }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.ports.grpc }}
            periodSeconds: 2
            initialDelaySeconds: 2
            timeoutSeconds: 2
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.ports.grpc }}
            periodSeconds: 2
            initialDelaySeconds: 2
            timeoutSeconds: 2
            failureThreshold: 20
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.global.registry_address }}/{{ .Values.global.docker_namespace }}/{{ .Values.image }}:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - python
            - scheduler/main.py
          env:
            - name: SCHEDULER_SCHEDULING_LOOP_INTERVAL
              value: "1"
            - name: SCHEDULER_SCHEDULING_LOOP_WORKERS
              value: "2"
            - name: SCHEDULER_REVERT_SCHEDULING_LOOP_INTERVAL
              value: "1"
            - name: SCHEDULER_REVERT_SCHEDULING_LOOP_WORKERS
              value: "1"
            - name: SCHEDULER_CANCELLATION_LOOP_INTERVAL
              value: "1"
            - name: SCHEDULER_CANCELLATION_LOOP_WORKERS
              value: "2"
            - name: SCHEDULER_RESETTING_LOOP_INTERVAL
              value: "10"
            - name: SCHEDULER_RESETTING_LOOP_WORKERS
              value: "1"
            - name: SCHEDULER_DELETION_LOOP_INTERVAL
              value: "1"
            - name: SCHEDULER_DELETION_LOOP_WORKERS
              value: "1"
            - name: SCHEDULER_RECOVERY_LOOP_INTERVAL
              value: "60"
            - name: SCHEDULER_RECOVERY_LOOP_WORKERS
              value: "1"
            - name: SCHEDULER_RECOVERY_BATCH_SIZE
              value: "50"
            - name: JOB_TRAIN_FLYTE_WORKFLOW_NAME
              value: job.workflows.train_workflow.train_workflow
            - name: JOB_OPTIMIZE_POT_FLYTE_WORKFLOW_NAME
              value: job.workflows.optimize_workflow.optimize_workflow_pot
            - name: JOB_TEST_FLYTE_WORKFLOW_NAME
              value: job.workflows.model_test_workflow.model_test_workflow
            - name: JOB_EXPORT_PROJECT_FLYTE_WORKFLOW_NAME
              value: job.workflows.export_project_workflow.export_project_workflow
            - name: JOB_IMPORT_PROJECT_FLYTE_WORKFLOW_NAME
              value: job.workflows.import_project_workflow.import_project_workflow
            - name: JOB_EXPORT_DATASET_FLYTE_WORKFLOW_NAME
              value: job.workflows.export_workflow.export_dataset_workflow
            - name: JOB_PREPARE_IMPORT_TO_NEW_PROJECT_FLYTE_WORKFLOW_NAME
              value: job.workflows.import_workflows.prepare_import_new_project_workflow
            - name: JOB_PREPARE_IMPORT_TO_NEW_PROJECT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_PERFORM_IMPORT_TO_NEW_PROJECT_FLYTE_WORKFLOW_NAME
              value: job.workflows.import_workflows.create_project_from_dataset_workflow
            - name: JOB_PERFORM_IMPORT_TO_NEW_PROJECT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_PREPARE_IMPORT_TO_EXISTING_PROJECT_FLYTE_WORKFLOW_NAME
              value: job.workflows.import_workflows.prepare_import_existing_project_workflow
            - name: JOB_PREPARE_IMPORT_TO_EXISTING_PROJECT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_PERFORM_IMPORT_TO_EXISTING_PROJECT_FLYTE_WORKFLOW_NAME
              value: job.workflows.import_workflows.import_dataset_to_project_workflow
            - name: JOB_PERFORM_IMPORT_TO_EXISTING_PROJECT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_TRAIN_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_TEST_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_OPTIMIZE_POT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_EXPORT_DATASET_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_EXPORT_PROJECT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: JOB_IMPORT_PROJECT_FLYTE_WORKFLOW_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: workflow_versions
            - name: FLYTE_URL
              value: flyteadmin.flyte.svc.cluster.local:81
            - name: FLYTE_PROJECT
              value: impt-jobs
            - name: FLYTE_DOMAIN
              value: production
            - name: DATABASE_ADDRESS
              value: mongodb://{{ .Release.Namespace }}-mongodb:27017/
            - name: CREDITS_SERVICE
              value: credit-system.impt:5556
            {{- if .Values.global.enable_mongodb_credentials }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-mongodb
                  key: {{ .Chart.Name }}-mongodb-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-mongodb
                  key: {{ .Chart.Name }}-mongodb-password
            {{- end }}
            - name: SPICEDB_LOG_PATH
              value: {{ .Values.spicedb_log_file_path }}
            - name: SPICEDB_ADDRESS
              value: {{ .Release.Namespace }}-spice-db:50051
            - name: SPICEDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "spice-db.secretName" . }}
                  key: SPICEDB_GRPC_PRESHARED_KEY
            - name: SPICEDB_CREDENTIALS
              value: "token_and_ca"
            - name: SPICEDB_SSL_CERTIFICATES_DIR
              value: "/etc/tls-secrets"
            - name: KAFKA_ADDRESS
              value: {{ .Release.Namespace }}-kafka
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-kafka-jaas-{{ .Chart.Name }}
                  key: user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-kafka-jaas-{{ .Chart.Name }}
                  key: password
            - name: KAFKA_TOPIC_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: kafka_topic_prefix
            - name: ENABLE_TRACING
              value: "true"
            - name: ENABLE_METRICS
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: jobs-scheduler
            - name: OTLP_TRACES_RECEIVER
              value: "{{ .Release.Namespace }}-opentelemetry-collector.{{ .Release.Namespace }}:4317"
            - name: OTLP_METRICS_RECEIVER
              value: "{{ .Release.Namespace }}-opentelemetry-collector.{{ .Release.Namespace }}:4317"
            - name: OTLP_TRACES_PROTOCOL
              value: grpc
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_CONTAINER_NAME
              value: *containerName
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.instance.id=$(K8S_POD_NAME),k8s.pod.uid=$(K8S_POD_UID),k8s.container.name=$(K8S_CONTAINER_NAME)
            - name: MONGODB_CREDENTIALS_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name:  {{ .Release.Namespace }}-configuration
                  key: mongodb_credentials_provider
            - name: JOBS_TEMPLATES_DIR
              value: {{ .Values.jobs_templates_dir }}
            - name: JOBS_TEMPLATES_FILE
              value: {{ .Values.jobs_templates_file }}
            {{- if .Values.global.enable_object_storage }}
            - name: S3_CREDENTIALS_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Namespace }}-configuration
                  key: s3_credentials_provider
            - name: "S3_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Namespace }}-seaweed-fs"
                  key: "jobs_scheduler_secret_key"
            - name: "S3_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Namespace }}-seaweed-fs"
                  key: "jobs_scheduler_access_key"
            {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: temp
            - name: tls-secrets
              mountPath: "/etc/tls-secrets"
              readOnly: true
            - mountPath: {{ .Values.global.logging_config_dir }}
              name: config
              readOnly: true
            - mountPath: {{ .Values.jobs_templates_dir }}
              name: jobs-templates
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ .Release.Namespace }}-feature-flags
      volumes:
        - name: temp
          emptyDir: {}
        - name: tls-secrets
          secret:
            secretName: {{ include "spice-db.tlsSecretName" . }}
            items:
              - key: ca.crt
                path: ca.crt
        - name: config
          configMap:
            name: {{ .Release.Namespace }}-logging-config
        - name: jobs-templates
          configMap:
            name: {{ .Release.Namespace }}-jobs-templates
