apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spice-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
  {{- include "spice-db.labels" . | nindent 6 }}
  minAvailable: 1
