---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: {{ include "spice-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spice-db.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list" ]
