---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "spice-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spice-db.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spice-db.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    - name: "grpc"
      port: {{ .Values.ports.grpc }}
      protocol: "TCP"
      targetPort: {{ .Values.ports.grpc }}
      appProtocol: "https"
    - name: "http"
      port: {{ .Values.ports.http }}
      protocol: "TCP"
      targetPort: {{ .Values.ports.http }}
