---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: {{ include "spice-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spice-db.labels" . | nindent 4 }}
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
