---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: {{ include "spice-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spice-db.labels" . | nindent 4 }}
subjects:
  - kind: "ServiceAccount"
    name: {{ include "spice-db.fullname" . }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: {{ include "spice-db.fullname" . }}
