{{- $spicedb_grpc_preshared_key := randAlphaNum 12 | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spice-db.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spice-db.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace (include "spice-db.secretName" .) -}}
  {{- if $previous }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ $previous.data.SPICEDB_GRPC_PRESHARED_KEY }}
  {{ else }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ $spicedb_grpc_preshared_key }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spice-db.secretName" . }}
  namespace: {{ include "flyteworkflow.namespace" . }}
  labels:
    {{- include "spice-db.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace (include "spice-db.secretName" .) -}}
  {{- if $previous }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ $previous.data.SPICEDB_GRPC_PRESHARED_KEY }}
  {{ else }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ $spicedb_grpc_preshared_key }}
  {{- end }}