---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-ms
  labels:
    app: {{ .Chart.Name }}-ms
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - watch
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduler
  labels:
    app: {{ .Chart.Name }}-scheduler
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - watch
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduling-policy
  labels:
    app: {{ .Chart.Name }}-scheduling-policy
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
