---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-ms
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-ms
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-ms
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}-ms
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-scheduler
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduler
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduling-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-scheduling-policy
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduling-policy
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduling-policy
    namespace: {{ .Release.Namespace }}
