{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-ms
  labels:
    {{- include "jobs-ms.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduler
  labels:
    {{- include "jobs-scheduler.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}-scheduling-policy
  labels:
    {{- include "jobs-scheduling-policy.labels" . | nindent 4 }}
{{- end }}
