apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flyteworkflow.name" . }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - nodes
    - pods
  verbs:
    - get
    - list
