apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flyteworkflow.name" . }}
  namespace: {{ include "flyteworkflow.namespace" . }}
  labels:
    project: {{ include "flyteworkflow.name" . }}
    domain: {{ include "flyteworkflow.domain" . }}
