#!/bin/bash

# INTEL CONFIDENTIAL
#
# Copyright (C) 2024 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by
# the express license under which they were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
# without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

# Primary container's process ID file
PRIMARY_PID_FILE=$1

# Sidecar container's process ID file
SIDECAR_PID_FILE=$2

mlflow server -h 0.0.0.0 --backend-store-uri geti:// --artifacts-destination geti:// -w 2 --gunicorn-opts="--pid=$SIDECAR_PID_FILE" &
PID=$!

for i in $(seq 0 10); do
  if [ -f "$SIDECAR_PID_FILE" ]; then
    SIDECAR_PID=$(cat "$SIDECAR_PID_FILE")
    break
  fi
  sleep 1
done

check_liveliness $PRIMARY_PID_FILE $SIDECAR_PID &
wait $PID
