# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
"""Sphinx configuration for the getitrack documentation.

The API reference is generated from the source by sphinx-autoapi; the guide
pages are Markdown rendered by myst-parser. Docstrings follow the Google
convention, parsed by napoleon.
"""

from __future__ import annotations

import re
from pathlib import Path

_INIT = Path(__file__).resolve().parent.parent / "src" / "getitrack" / "__init__.py"
_VERSION_MATCH = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', _INIT.read_text())

project = "getitrack"
author = "OpenVINO Training Extensions Contributors"
release = _VERSION_MATCH.group(1) if _VERSION_MATCH else "0.0.0"
version = release

extensions = [
    "autoapi.extension",
    "myst_parser",
    "sphinx.ext.napoleon",
    "sphinx_copybutton",
    "sphinx_design",
]

# Markdown guide pages plus reStructuredText generated by autoapi.
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
root_doc = "index"
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Google-style docstrings.
napoleon_google_docstring = True
napoleon_numpy_docstring = False
# Render "Attributes:" as :ivar: field lists rather than standalone attribute
# directives, so they do not collide with the members autoapi already documents.
napoleon_use_ivar = True

# Auto-generated API reference from the package source (static parsing).
autoapi_type = "python"
autoapi_dirs = ["../src/getitrack"]
autoapi_root = "autoapi"
autoapi_ignore = ["*/tests/*", "*/__pycache__/*"]
autoapi_options = ["members", "undoc-members", "show-inheritance", "show-module-summary"]
autoapi_member_order = "groupwise"
autoapi_python_class_content = "class"
autoapi_add_toctree_entry = False  # The index toctree references autoapi/getitrack/index explicitly.

myst_enable_extensions = ["colon_fence"]

html_theme = "furo"
html_title = "getitrack"
