apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "account-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "account-service.labels" . | nindent 6 }}
  minAvailable: 1
