apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ include "account-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "account-service.labels" . | nindent 4 }}
