apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.grpc }}
      protocol: TCP
      name: grpc
      appProtocol: grpc
    - port: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http
      appProtocol: http
  selector:
    {{- include "account-service.selectorLabels" . | nindent 4 }}
