id: image-classification-dinov3-convnext-tiny
name: DINOv3 ConvNeXt-Tiny
license: https://github.com/facebookresearch/dinov3/blob/main/LICENSE.md
pretrained_weights:
  source: huggingface
  repo_id: timm/convnext_tiny.dinov3_lvd1689m
  revision: 39c7bb32f83c11bbb13cb23058f8852a4dac88ed
description: "DINOv3 ConvNeXt-Tiny is a compact convolutional feature model distilled on LVD-1689M with the DINOv3 method."
stats:
  gigaflops: 8.91
  trainable_parameters: 28.589128
  benchmark_metrics: {}
capabilities:
  xai: false
  tiling: false
hyperparameters:
  training:
    learning_rate: 0.0001
    weight_decay: 0.0001
    input_size_width: 224
    input_size_height: 224
    max_epochs: 90
    batch_size: 64
    early_stopping:
      patience: 10
    scheduler:
      type: cosine_annealing
      warmup:
        enable: true
        epochs: 10
