id: image-classification-dinov3-convnext-small
name: DINOv3 ConvNeXt-Small
license: DINOv3 License
pretrained_weights:
  source: huggingface
  repo_id: timm/convnext_small.dinov3_lvd1689m
  revision: 9a0c319ae4531d36df6ef11fc253fdc4b503628a
description: "DINOv3 ConvNeXt-Small is a convolutional feature model distilled on LVD-1689M with the DINOv3 method."
stats:
  gigaflops: 17.37
  trainable_parameters: 50.223688
  benchmark_metrics: {}
capabilities:
  xai: false
  tiling: false
hyperparameters:
  training:
    learning_rate: 0.0001
    weight_decay: 0.0001
