apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flyteadmin.name" . }}-init-job
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
{{- if .Values.global.enable_local_image_pull_secret  }}
{{- with .Values.flyteadmin.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "flyteadmin.name" . }}-init-job
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "flyteadmin.name" . }}-init-job-binding
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flyteadmin.name" . }}-init-job
subjects:
- kind: ServiceAccount
  name: {{ template "flyteadmin.name" . }}-init-job
  namespace: {{ template "flyte.namespace" . }}
