quiet: False
disable-version-string: True
with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "mock/{{.InterfaceDirRelative}}"
packages:
  geti.com/modelregistration:
    interfaces:
      ModelRegistrationClient:
        config:
