name: Generate Build Version
description: Generate Build Version

inputs:
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
outputs:
  build_version:
    description: "Build version"
    value: ${{ steps.prepare-build-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Prepare build version
      id: prepare-build-version
      shell: bash
      env:
        CHECKOUT_REF: ${{ inputs.ref }}
      run: |
        echo "github.ref_name => ${{ github.ref_name }}"
        echo "github.ref => ${{ github.ref }}"
        echo "inputs.ref => ${{ inputs.ref }}"
        
        base_version=$(<VERSION)
        ref_sanitized=${CHECKOUT_REF//\//-}
        tag="${base_version}-${ref_sanitized}"

        # If not a tag build, append the short SHA
        if [[ "$CHECKOUT_REF" != refs/tags/* ]]; then
          tag+="-$(git rev-parse --short HEAD)"
        fi
        echo "version=$tag"
        echo "version=$tag" >> "$GITHUB_OUTPUT"
