kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "cert-manager-istio-csr.labels" . | nindent 4 }}
  name: {{ include "cert-manager-istio-csr.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs: ["get", "list", "create", "update", "watch"]
- apiGroups:
  - ""
  resources:
  - "namespaces"
  {{- if .Values.app.server.caTrustedNodeAccounts }}
  - "pods"
  {{- end }}
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
{{- if eq (toString .Values.app.tls.istiodCertificateEnable) "dynamic" }}
- apiGroups:
  - "cert-manager.io"
  resources:
  - "certificates"
  verbs:
  - "list"
  - "get"
  - "watch"
{{- end }}
