apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
metadata:
  labels:
    {{- include "cert-manager-istio-csr.labels" . | nindent 4 }}
  name: {{ include "cert-manager-istio-csr.name" . }}
  namespace: {{ .Release.Namespace }}
