---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project-ie.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}
    namespace: {{ .Release.Namespace }}
