---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modelregistration
  namespace: {{.Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelregistration
subjects:
  - kind: ServiceAccount
    name: {{ .Values.modelRegistration.serviceAccount }}
    namespace: {{ .Values.modelRegistration.namespace }}
