---
image: jobs
imagePullPolicy: IfNotPresent

serviceAccount:
  create: true

volumeSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

audit_logs_mount_path: "audit_logs"
spicedb_log_file_path: "/audit_logs/spicedb.log"

jobs_templates_dir: /mnt/jobs_templates
jobs_templates_file: jobs_templates.yaml

microservice:
  initResources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

  standardResources:
    requests:
      cpu: 400m
      memory: 500Mi
    limits:
      memory: 500Mi

  liteResources:
    requests:
      cpu: 400m
      memory: 200Mi
    limits:
      memory: 500Mi

  service:
    type: ClusterIP
    ports:
      grpc: 50051
      http: 8000

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

  ingress:
    endpoints:
      - /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/jobs(/|$)(.*)

scheduler:
  replicas: 1

  initResources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

  standardeResources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      memory: 500Mi

  liteResources:
    requests:
      cpu: 300m
      memory: 200Mi
    limits:
      memory: 500Mi

  service:
    type: ClusterIP
    ports:
      grpc: 50051

scheduling_policy:
  replicas: 1

  initResources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

  standardResources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      memory: 500Mi

  liteResources:
    requests:
      cpu: 300m
      memory: 200Mi
    limits:
      memory: 500Mi

policies:
  - name: MAX_TRAIN_JOBS_RUNNING_PER_ORGANIZATION
    value: "gpu"
  - name: MAX_OPTIMIZE_POT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_TEST_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PREPARE_IMPORT_TO_NEW_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PERFORM_IMPORT_TO_NEW_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PREPARE_IMPORT_TO_EXISTING_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PERFORM_IMPORT_TO_EXISTING_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_EXPORT_DATASET_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_EXPORT_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_IMPORT_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"

global:
  logging_config_dir: ''
  storage_volume_claim_name_jobs: ''
  docker_namespace: geti
  security_headers: ''
  stripped_headers: ''
  cors_policy:
    enabled: false
    allowed_origins: []
    allowed_headers: []
    allowed_methods: []
    max_age: 86400s
    allow_credentials: false
  workflow_versions: v1
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc
  kubectl:
    registry: docker.io
    repository: bitnami
    name: kubectl:1.31.0
  debian:
    registry: docker.io
    repository: bitnami
    name: bitnami-shell:11-debian-11-r136
