---
{{- if .Values.autoscalerEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modelmesh-autoscaler-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
    verbs:
      - get
      - list
{{- end }}
