---
enabled:
  dcgm-exporter: true
  dex: true
  etcd: true
  kafka-provisioning: true
  kafka-proxy: true
  kafka: true
  mongodb: true
  opa: true
  openldap: true
  opentelemetry-collector: true
  postgresql: true
  seaweed-fs: true
  spice-db: true
  xpu-manager: true

global:
  registry_address: "registry.toolbox.iotg.sclab.intel.com"
  istio_ambient_mesh: false
  istio_gateway_name: "istio-gateway"
  istio_ingress_namespace: "istio-system"
  logging_config_dir: "/mnt/logging_config"
  logs_dir: "/mnt/logs"
  ldap_service_user_secret_name: "impt-ldap-service-user"
  waypoint:
    name: istio-waypoint
    namespace: impt
  security_headers: |
    X-Frame-Options: "DENY"
    Content-Security-Policy: "frame-ancestors 'none'; default-src 'self'; media-src 'self' https://docs.geti.intel.com/on-prem/2.6/; connect-src 'self' data: https://consumerdev.intel.com/ https://login.microsoftonline.com/; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' blob:; img-src 'self' data:; frame-src 'none'; object-src 'none'; form-action 'self'; worker-src 'self' blob:"
    cross-origin-embedder-policy: require-corp
    cross-origin-opener-policy: same-origin
    X-Content-Type-Options: "nosniff"
  stripped_headers: |
    - "X-Envoy-Decorator-Operation"
  enable_local_image_pull_secret: false
  enable_object_storage: true
  s3_endpoint: impt-seaweed-fs.impt:8333
  docker_namespace: impp
  forceNamespace:
    flyte: flyte
  debian: 
    registry: docker.io
    repository: bitnami
    name: bitnami-shell:11-debian-11-r136
  kubectl: 
    registry: docker.io
    repository: bitnami
    name: kubectl:1.31.0
  credit_system_enabled: false
  seaweed_fs_enabled: true
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc
  telemetry_retention_geti: 30
  telemetry_retention_k8s: 10
  enable_mongodb_credentials: true
  cors_policy:
    enabled: true
    allowed_origins:
      - exact: "https://docs.geti.intel.com"
    allowed_headers:
      - Authorization
      - Content-Type
      - tus-resumable
      - upload-length
      - upload-length
      - x-geti-csrf-protection
      - cookie
      - x-api-key
    allowed_methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
    max_age: 86400s
    allow_credentials: true
