# Copyright (C) 2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: geti-flyte-crds
version: 2.10.1
description: Flyte CRDs for Intel® Geti™

helmRegistry: ghcr-geti-oci
chartName: flyte-crds
chartVersion: 2.10.1

profiles:
  - name: default
    valuesFileName: empty-values.yaml
