apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cert.name }}
  namespace: {{ include "flyteworkflow.namespace" . }}
spec:
  secretName: {{ .Values.cert.secretName }}
  duration: {{ .Values.cert.duration }}
  renewBefore: {{ .Values.cert.renewBefore }}
  privateKey:
    algorithm: {{ .Values.cert.algorithm }}
    size: {{ .Values.cert.size }}
  issuerRef:
    name: {{ .Values.cert.ca_name }}
    kind: ClusterIssuer
    group: cert-manager.io
  # dummy dnsName as cert is used for signing purposes
  dnsNames:
    - localhost
