---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-training-config
  namespace: {{ include "flyteworkflow.namespace" . }}
data:
  # Default Docker image name of primary container used for model training/hpo/optimize
  default_trainer_image_name: "{{ .Values.training.default_trainer_image_name }}"
  # Default Docker image version (tag) of primary container used for model training/hpo/optimize
  default_trainer_version: "{{ .Values.training.default_trainer_version }}"
  # Docker image name of MLFlow sidecar container used for model training/hpo/optimize
  mlflow_sidecar_image_name: "{{ .Values.training.mlflow_sidecar_image_name }}"
