include ../../Makefile.shared-python

test: test-component

test-unit: venv
	@echo "test-unit not available"

test-component: venv
	uv run pytest --disable-warnings -v

test-integration: venv
	@echo "test-integration not available"