include ../../Makefile.shared-python

test: test-component

test-unit: venv-dev
	@echo "test-unit not available"

test-component: venv-dev
	uv run pytest --disable-warnings -v

test-integration: venv-dev
	@echo "test-integration not available"