// Copyright (C) 2022-2025 Intel Corporation
// LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: membership_status.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStatusRequest) Reset() {
	*x = UserStatusRequest{}
	mi := &file_membership_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusRequest) ProtoMessage() {}

func (x *UserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusRequest.ProtoReflect.Descriptor instead.
func (*UserStatusRequest) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{0}
}

func (x *UserStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatusRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserStatusRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type UserStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	mi := &file_membership_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserStatusResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatusResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UserStatusResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MembershipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstName      string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName     string                 `protobuf:"bytes,2,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	SortBy         string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDirection  string                 `protobuf:"bytes,9,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` //asc/desc
	Skip           int32                  `protobuf:"varint,10,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit          int32                  `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MembershipRequest) Reset() {
	*x = MembershipRequest{}
	mi := &file_membership_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipRequest) ProtoMessage() {}

func (x *MembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipRequest.ProtoReflect.Descriptor instead.
func (*MembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{2}
}

func (x *MembershipRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MembershipRequest) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *MembershipRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MembershipRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MembershipRequest) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MembershipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MembershipRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *MembershipRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *MembershipRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *MembershipRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *MembershipRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipResponse) Reset() {
	*x = MembershipResponse{}
	mi := &file_membership_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipResponse) ProtoMessage() {}

func (x *MembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipResponse.ProtoReflect.Descriptor instead.
func (*MembershipResponse) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{3}
}

func (x *MembershipResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MembershipResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MembershipResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MembershipResponse) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *MembershipResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MembershipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MembershipResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListMembershipResponse struct {
	state             protoimpl.MessageState           `protogen:"open.v1"`
	Memberships       []*MembershipResponse            `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	TotalCount        int32                            `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalMatchedCount int32                            `protobuf:"varint,3,opt,name=total_matched_count,json=totalMatchedCount,proto3" json:"total_matched_count,omitempty"`
	NextPage          *ListMembershipResponse_NextPage `protobuf:"bytes,4,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListMembershipResponse) Reset() {
	*x = ListMembershipResponse{}
	mi := &file_membership_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipResponse) ProtoMessage() {}

func (x *ListMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipResponse.ProtoReflect.Descriptor instead.
func (*ListMembershipResponse) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{4}
}

func (x *ListMembershipResponse) GetMemberships() []*MembershipResponse {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *ListMembershipResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMembershipResponse) GetTotalMatchedCount() int32 {
	if x != nil {
		return x.TotalMatchedCount
	}
	return 0
}

func (x *ListMembershipResponse) GetNextPage() *ListMembershipResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

type MembershipStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MembershipStatusResponse) Reset() {
	*x = MembershipStatusResponse{}
	mi := &file_membership_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatusResponse) ProtoMessage() {}

func (x *MembershipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatusResponse.ProtoReflect.Descriptor instead.
func (*MembershipStatusResponse) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{5}
}

func (x *MembershipStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MembershipStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MembershipStatusResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *MembershipStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MembershipStatusResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *MembershipStatusResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MembershipStatusPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipStatusPayload) Reset() {
	*x = MembershipStatusPayload{}
	mi := &file_membership_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatusPayload) ProtoMessage() {}

func (x *MembershipStatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatusPayload.ProtoReflect.Descriptor instead.
func (*MembershipStatusPayload) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{6}
}

func (x *MembershipStatusPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MembershipStatusRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Payload        *MembershipStatusPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	UserId         string                   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                   `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedBy      string                   `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MembershipStatusRequest) Reset() {
	*x = MembershipStatusRequest{}
	mi := &file_membership_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatusRequest) ProtoMessage() {}

func (x *MembershipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatusRequest.ProtoReflect.Descriptor instead.
func (*MembershipStatusRequest) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{7}
}

func (x *MembershipStatusRequest) GetPayload() *MembershipStatusPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MembershipStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MembershipStatusRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *MembershipStatusRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type UserMembershipRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	SortBy           string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDirection    string                 `protobuf:"bytes,4,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` //asc/desc
	Skip             int32                  `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit            int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserMembershipRequest) Reset() {
	*x = UserMembershipRequest{}
	mi := &file_membership_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMembershipRequest) ProtoMessage() {}

func (x *UserMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMembershipRequest.ProtoReflect.Descriptor instead.
func (*UserMembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{8}
}

func (x *UserMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMembershipRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserMembershipRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *UserMembershipRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *UserMembershipRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *UserMembershipRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserMembershipResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,3,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserMembershipResponse) Reset() {
	*x = UserMembershipResponse{}
	mi := &file_membership_status_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMembershipResponse) ProtoMessage() {}

func (x *UserMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMembershipResponse.ProtoReflect.Descriptor instead.
func (*UserMembershipResponse) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{9}
}

func (x *UserMembershipResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserMembershipResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserMembershipResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserMembershipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserMembershipResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUserMembershipResponse struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	Memberships       []*UserMembershipResponse            `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	TotalCount        int32                                `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalMatchedCount int32                                `protobuf:"varint,3,opt,name=total_matched_count,json=totalMatchedCount,proto3" json:"total_matched_count,omitempty"`
	NextPage          *ListUserMembershipResponse_NextPage `protobuf:"bytes,4,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListUserMembershipResponse) Reset() {
	*x = ListUserMembershipResponse{}
	mi := &file_membership_status_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserMembershipResponse) ProtoMessage() {}

func (x *ListUserMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserMembershipResponse.ProtoReflect.Descriptor instead.
func (*ListUserMembershipResponse) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserMembershipResponse) GetMemberships() []*UserMembershipResponse {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *ListUserMembershipResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUserMembershipResponse) GetTotalMatchedCount() int32 {
	if x != nil {
		return x.TotalMatchedCount
	}
	return 0
}

func (x *ListUserMembershipResponse) GetNextPage() *ListUserMembershipResponse_NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

type DeleteMembershipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteMembershipRequest) Reset() {
	*x = DeleteMembershipRequest{}
	mi := &file_membership_status_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipRequest) ProtoMessage() {}

func (x *DeleteMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipRequest.ProtoReflect.Descriptor instead.
func (*DeleteMembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteMembershipRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListMembershipResponse_NextPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipResponse_NextPage) Reset() {
	*x = ListMembershipResponse_NextPage{}
	mi := &file_membership_status_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipResponse_NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipResponse_NextPage) ProtoMessage() {}

func (x *ListMembershipResponse_NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipResponse_NextPage.ProtoReflect.Descriptor instead.
func (*ListMembershipResponse_NextPage) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListMembershipResponse_NextPage) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListMembershipResponse_NextPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUserMembershipResponse_NextPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserMembershipResponse_NextPage) Reset() {
	*x = ListUserMembershipResponse_NextPage{}
	mi := &file_membership_status_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserMembershipResponse_NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserMembershipResponse_NextPage) ProtoMessage() {}

func (x *ListUserMembershipResponse_NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_membership_status_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserMembershipResponse_NextPage.ProtoReflect.Descriptor instead.
func (*ListUserMembershipResponse_NextPage) Descriptor() ([]byte, []int) {
	return file_membership_status_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ListUserMembershipResponse_NextPage) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListUserMembershipResponse_NextPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_membership_status_proto protoreflect.FileDescriptor

const file_membership_status_proto_rawDesc = "" +
	"\n" +
	"\x17membership_status.proto\x12\x11user_status_proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\x11UserStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\"\xd8\x01\n" +
	"\x12UserStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe3\x02\n" +
	"\x11MembershipRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x02 \x01(\tR\n" +
	"secondName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\t \x01(\tR\rsortDirection\x12\x12\n" +
	"\x04skip\x18\n" +
	" \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\v \x01(\x05R\x05limit\"\xe6\x01\n" +
	"\x12MembershipResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x04 \x01(\tR\n" +
	"secondName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcc\x02\n" +
	"\x16ListMembershipResponse\x12G\n" +
	"\vmemberships\x18\x01 \x03(\v2%.user_status_proto.MembershipResponseR\vmemberships\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12.\n" +
	"\x13total_matched_count\x18\x03 \x01(\x05R\x11totalMatchedCount\x12T\n" +
	"\tnext_page\x18\x04 \x01(\v22.user_status_proto.ListMembershipResponse.NextPageH\x00R\bnextPage\x88\x01\x01\x1a4\n" +
	"\bNextPage\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_next_page\"\xde\x01\n" +
	"\x18MembershipStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"1\n" +
	"\x17MembershipStatusPayload\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc0\x01\n" +
	"\x17MembershipStatusRequest\x12D\n" +
	"\apayload\x18\x01 \x01(\v2*.user_status_proto.MembershipStatusPayloadR\apayload\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\"\xc7\x01\n" +
	"\x15UserMembershipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12%\n" +
	"\x0esort_direction\x18\x04 \x01(\tR\rsortDirection\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xd1\x01\n" +
	"\x16UserMembershipResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\x03 \x01(\tR\x10organizationName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd8\x02\n" +
	"\x1aListUserMembershipResponse\x12K\n" +
	"\vmemberships\x18\x01 \x03(\v2).user_status_proto.UserMembershipResponseR\vmemberships\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12.\n" +
	"\x13total_matched_count\x18\x03 \x01(\x05R\x11totalMatchedCount\x12X\n" +
	"\tnext_page\x18\x04 \x01(\v26.user_status_proto.ListUserMembershipResponse.NextPageH\x00R\bnextPage\x88\x01\x01\x1a4\n" +
	"\bNextPage\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_next_page\"[\n" +
	"\x17DeleteMembershipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId2\xb1\x01\n" +
	"\n" +
	"UserStatus\x12\xa2\x01\n" +
	"\x06change\x12$.user_status_proto.UserStatusRequest\x1a%.user_status_proto.UserStatusResponse\"K\x82\xd3\xe4\x93\x02E:\x01*\x1a@/api/v1/organizations/{organization_id}/users/{user_id}/statuses2\x9f\x05\n" +
	"\n" +
	"Membership\x12\x9e\x01\n" +
	"\x0eGetMemberships\x12$.user_status_proto.MembershipRequest\x1a).user_status_proto.ListMembershipResponse\";\x82\xd3\xe4\x93\x025\x123/api/v1/organizations/{organization_id}/memberships\x12\xb1\x01\n" +
	"\x06Modify\x12*.user_status_proto.MembershipStatusRequest\x1a+.user_status_proto.MembershipStatusResponse\"N\x82\xd3\xe4\x93\x02H:\apayload\x1a=/api/v1/organizations/{organization_id}/memberships/{user_id}\x12\x9a\x01\n" +
	"\x12GetUserMemberships\x12(.user_status_proto.UserMembershipRequest\x1a-.user_status_proto.ListUserMembershipResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/users/{user_id}/memberships\x12\x9e\x01\n" +
	"\x11DeleteMemberships\x12*.user_status_proto.DeleteMembershipRequest\x1a\x16.google.protobuf.Empty\"E\x82\xd3\xe4\x93\x02?*=/api/v1/organizations/{organization_id}/memberships/{user_id}B\"Z geti.com/account_service_grpc/pbb\x06proto3"

var (
	file_membership_status_proto_rawDescOnce sync.Once
	file_membership_status_proto_rawDescData []byte
)

func file_membership_status_proto_rawDescGZIP() []byte {
	file_membership_status_proto_rawDescOnce.Do(func() {
		file_membership_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membership_status_proto_rawDesc), len(file_membership_status_proto_rawDesc)))
	})
	return file_membership_status_proto_rawDescData
}

var file_membership_status_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_membership_status_proto_goTypes = []any{
	(*UserStatusRequest)(nil),                   // 0: user_status_proto.UserStatusRequest
	(*UserStatusResponse)(nil),                  // 1: user_status_proto.UserStatusResponse
	(*MembershipRequest)(nil),                   // 2: user_status_proto.MembershipRequest
	(*MembershipResponse)(nil),                  // 3: user_status_proto.MembershipResponse
	(*ListMembershipResponse)(nil),              // 4: user_status_proto.ListMembershipResponse
	(*MembershipStatusResponse)(nil),            // 5: user_status_proto.MembershipStatusResponse
	(*MembershipStatusPayload)(nil),             // 6: user_status_proto.MembershipStatusPayload
	(*MembershipStatusRequest)(nil),             // 7: user_status_proto.MembershipStatusRequest
	(*UserMembershipRequest)(nil),               // 8: user_status_proto.UserMembershipRequest
	(*UserMembershipResponse)(nil),              // 9: user_status_proto.UserMembershipResponse
	(*ListUserMembershipResponse)(nil),          // 10: user_status_proto.ListUserMembershipResponse
	(*DeleteMembershipRequest)(nil),             // 11: user_status_proto.DeleteMembershipRequest
	(*ListMembershipResponse_NextPage)(nil),     // 12: user_status_proto.ListMembershipResponse.NextPage
	(*ListUserMembershipResponse_NextPage)(nil), // 13: user_status_proto.ListUserMembershipResponse.NextPage
	(*timestamp.Timestamp)(nil),                 // 14: google.protobuf.Timestamp
	(*empty.Empty)(nil),                         // 15: google.protobuf.Empty
}
var file_membership_status_proto_depIdxs = []int32{
	14, // 0: user_status_proto.UserStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: user_status_proto.MembershipRequest.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: user_status_proto.MembershipResponse.created_at:type_name -> google.protobuf.Timestamp
	3,  // 3: user_status_proto.ListMembershipResponse.memberships:type_name -> user_status_proto.MembershipResponse
	12, // 4: user_status_proto.ListMembershipResponse.next_page:type_name -> user_status_proto.ListMembershipResponse.NextPage
	14, // 5: user_status_proto.MembershipStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: user_status_proto.MembershipStatusRequest.payload:type_name -> user_status_proto.MembershipStatusPayload
	14, // 7: user_status_proto.UserMembershipResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 8: user_status_proto.ListUserMembershipResponse.memberships:type_name -> user_status_proto.UserMembershipResponse
	13, // 9: user_status_proto.ListUserMembershipResponse.next_page:type_name -> user_status_proto.ListUserMembershipResponse.NextPage
	0,  // 10: user_status_proto.UserStatus.change:input_type -> user_status_proto.UserStatusRequest
	2,  // 11: user_status_proto.Membership.GetMemberships:input_type -> user_status_proto.MembershipRequest
	7,  // 12: user_status_proto.Membership.Modify:input_type -> user_status_proto.MembershipStatusRequest
	8,  // 13: user_status_proto.Membership.GetUserMemberships:input_type -> user_status_proto.UserMembershipRequest
	11, // 14: user_status_proto.Membership.DeleteMemberships:input_type -> user_status_proto.DeleteMembershipRequest
	1,  // 15: user_status_proto.UserStatus.change:output_type -> user_status_proto.UserStatusResponse
	4,  // 16: user_status_proto.Membership.GetMemberships:output_type -> user_status_proto.ListMembershipResponse
	5,  // 17: user_status_proto.Membership.Modify:output_type -> user_status_proto.MembershipStatusResponse
	10, // 18: user_status_proto.Membership.GetUserMemberships:output_type -> user_status_proto.ListUserMembershipResponse
	15, // 19: user_status_proto.Membership.DeleteMemberships:output_type -> google.protobuf.Empty
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_membership_status_proto_init() }
func file_membership_status_proto_init() {
	if File_membership_status_proto != nil {
		return
	}
	file_membership_status_proto_msgTypes[4].OneofWrappers = []any{}
	file_membership_status_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membership_status_proto_rawDesc), len(file_membership_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_membership_status_proto_goTypes,
		DependencyIndexes: file_membership_status_proto_depIdxs,
		MessageInfos:      file_membership_status_proto_msgTypes,
	}.Build()
	File_membership_status_proto = out.File
	file_membership_status_proto_goTypes = nil
	file_membership_status_proto_depIdxs = nil
}
