{{- if .Values.secrets.adminOauthClientCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flyte-secret-auth
  namespace: {{ template "flyte.namespace" . }}
type: Opaque
stringData:
  client_secret: {{ randAlphaNum 12 | quote }}
{{- end }}
