include ../../../Makefile.shared-python

DOCKER_BUILD_CONTEXT := --build-context schemas=../api \
						--build-context libs=../../../libs \
						--build-context iai_core=../../../interactive_ai/libs/iai_core_py \
						--build-context grpc_interfaces=../../../grpc_interfaces \
						--build-context supported_models=../../../interactive_ai/supported_models \
