# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

{{- if .Values.global.istio_ambient_mesh }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
spec:
  parentRefs:
    - name: {{ .Values.global.istio_gateway_name }}
      kind: Gateway
      namespace: {{ .Values.global.istio_ingress_namespace }}
#  hostnames:
#    - "*.intel.com"  # only for SaaS
  rules:
    - matches:
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/([^/]*)/datasets/uploads/resumable(/|$)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/([^/]*)/datasets/uploads/resumable/(.*)(/|$)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)(prepare-for-import|import-from-dataset|prepare-for-export)(/|$)(.*)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/datasets/(.*):prepare-for-export(.*)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/datasets/(.*)/exports(/|$)(.*)
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/(.*)/projects/(.*)/datasets/(.*)/exports(/|$)(.*)(/|$)download
        - path:
            type: RegularExpression
            value: /api/v(.*)/organizations/([^/]*)/workspaces/([^/]*)/datasets/uploads(/|$)
      backendRefs:
        - name: {{ .Release.Namespace }}-{{ .Chart.Name }}
          port: {{ .Values.service.port }}
{{- end}}
