---
{{- if .Values.autoscalerEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modelmesh-autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modelmesh-serving.labels" . | nindent 4 }}
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
{{- end }}
