apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configuration.secretName}}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  login: "{{ .Values.configuration.login }}"
  passwordHash: "{{ .Values.configuration.passwordHash }}"
  dataFolder: "{{ .Values.configuration.dataFolder }}"
  tlsCert: "{{ .Values.configuration.tlsCert }}"
  tlsKey: "{{ .Values.configuration.tlsKey }}"
