apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ include "geti-controller.name" . }}
  labels:
    {{- include "geti-controller.labels" . | nindent 4 }}
