apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
    {{- include "visual-prompt.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-visual-prompt
      port: {{ .Values.service.port }}
      protocol: TCP
      appProtocol: http
  selector:
    {{- include "visual-prompt.selectorLabels" . | nindent 4 }}
