# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11user_common.proto\x12\x0buser_common\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x06\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x13\n\x0bsecond_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x17\n\x0forganization_id\x18\x08 \x01(\t\x12\x1b\n\x13organization_status\x18\t \x01(\t\x12$\n\x05roles\x18\n \x03(\x0b\x32\x15.user_common.UserRole\x12\x39\n\x15last_successful_login\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12<\n\x18\x63urrent_successful_login\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x0e \x01(\t\x12/\n\x0bmodified_at\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bmodified_by\x18\x10 \x01(\t\x12\x1e\n\x11telemetry_consent\x18\x11 \x01(\tH\x00\x88\x01\x01\x12\x38\n\x14telemetry_consent_at\x18\x12 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x0cuser_consent\x18\x13 \x01(\tH\x01\x88\x01\x01\x12\x33\n\x0fuser_consent_at\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rpresigned_url\x18\x15 \x01(\t\x12\x34\n\x10last_logout_date\x18\x16 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x14\n\x12_telemetry_consentB\x0f\n\r_user_consent\"D\n\x08UserRole\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x13\n\x0bresource_id\x18\x03 \x01(\t\"K\n\x11UserRoleOperation\x12#\n\x04role\x18\x01 \x01(\x0b\x32\x15.user_common.UserRole\x12\x11\n\toperation\x18\x02 \x01(\t\"k\n\x15UserInvitationRequest\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.user_common.UserData\x12-\n\x05roles\x18\x02 \x03(\x0b\x32\x1e.user_common.UserRoleOperationB\"Z geti.com/account_service_grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z geti.com/account_service_grpc/pb'
  _globals['_USERDATA']._serialized_start=68
  _globals['_USERDATA']._serialized_end=837
  _globals['_USERROLE']._serialized_start=839
  _globals['_USERROLE']._serialized_end=907
  _globals['_USERROLEOPERATION']._serialized_start=909
  _globals['_USERROLEOPERATION']._serialized_end=984
  _globals['_USERINVITATIONREQUEST']._serialized_start=986
  _globals['_USERINVITATIONREQUEST']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
