---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-feature-flags
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.feature_flags_data }}
{{ .Values.feature_flags_data | toYaml | indent 2 }}
  feature-flags.json: |
{{- include "configuration.featureFlagsJson" . | nindent 4 }}
{{- end }}
