---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-directory.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-directory.labels" . | nindent 4 }}
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "user-directory.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.port }}
      protocol: TCP
      appProtocol: http
