# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-go

DOCKER_BUILD_CONTEXT := --build-context account_service_client=$(CWD)/libs/grpc_interfaces/grpc_interfaces/account_service/go
