apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "initial-user.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "initial-user.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
