apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "initial-user.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "initial-user.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "initial-user.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "initial-user.name" . }}
    namespace: {{ .Release.Namespace }}
