include ../../../Makefile.shared-python-uv

DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \
						--build-context sc_sdk=../../../interactive_ai/libs/sc_sdk \
						--build-context grpc_interfaces=../../../grpc_interfaces \
