image: jobs-ms
imagePullPolicy: IfNotPresent
replicas: 1

serviceAccount:
  create: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

initResources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 100Mi

resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    memory: 500Mi

policies:
  - name: MAX_TRAIN_JOBS_RUNNING_PER_ORGANIZATION
    value: "gpu"
  - name: MAX_OPTIMIZE_POT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_TEST_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PREPARE_IMPORT_TO_NEW_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PERFORM_IMPORT_TO_NEW_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PREPARE_IMPORT_TO_EXISTING_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_PERFORM_IMPORT_TO_EXISTING_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_EXPORT_DATASET_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_EXPORT_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"
  - name: MAX_IMPORT_PROJECT_JOBS_RUNNING_PER_ORGANIZATION
    value: "1"

global:
  logging_config_dir: ''
  storage_volume_claim_name_jobs: data-storage-volume-claim
  docker_namespace: geti
  workflow_versions: v1
  busybox:
    registry: quay.io
    repository: prometheus
    name: busybox:glibc
  kubectl:
    registry: docker.io
    repository: bitnami
    name: kubectl:1.31.0
