# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

{{- if .Values.global.istio_ambient_mesh }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
spec:
  parentRefs:
    - name: {{ .Values.global.istio_gateway_name }}
      kind: Gateway
      namespace: {{ .Values.global.istio_ingress_namespace }}
#  hostnames:
#    - "*.intel.com"  # only for SaaS
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /robots.txt
        - path:
            type: PathPrefix
            value: /registration
        - path:
            type: PathPrefix
            value: /user_email_form.html
        - path:
            type: RegularExpression
            value: /.*
      backendRefs:
        - name: {{ .Values.ui_app_name }}
          port: {{ .Values.ui_port }}
    - matches:
        - path:
            type: PathPrefix
            value: /personal-access-token
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ .Values.ui_app_name }}
          port: {{ .Values.ui_port }}
{{- end}}
