apiVersion: v1
kind: ConfigMap
metadata:
  name: web-ui-deployment-config
  namespace: {{ .Release.Namespace }}
data:
  geti-deployment: |
    {
        "servingMode": "on-prem",
        "auth": {
            "type": "dex",
            "authority": "/dex",
            "clientId": "web_ui"
        },
        "docsUrl": "https://docs.geti.intel.com/",
        "dataPlaneUrl": null,
        "controlPlaneUrl": null,
        {{- if .Values.global.install_telemetry_stack }}
        "telemetryStack": "true"
        {{- else }}
        "telemetryStack": "false"
        {{- end }}
    }
  admin-deployment: |
    {
        "servingMode": "on-prem",
        "auth": {
            "type": "dex",
            "authority": "/dex",
            "clientId": "web_ui"
        },
        "docsUrl": "https://docs.geti.intel.com/",
        "dataPlaneUrl": null,
        "controlPlaneUrl": null
    }
