name: 'Set Variables'
description: 'Resolves build context variables'
inputs:
  publish_binaries:
    description: "Enable publishing binaries"
    type: boolean
    default: true
  ref:
    description: 'Reference (branch/tag/SHA) for manual workflow dispatch'
    required: false
    default: ''
outputs:
  build_all:
    description: 'Indicates whether all components should be rebuilt'
    value: ${{ steps.set-vars.outputs.build_all }}

  publish_binaries:
    description: 'Indicates whether binaries should be published'
    value: ${{ steps.set-vars.outputs.publish_binaries }}

  checkout_ref:
    description: 'The source Git ref to be used for checkout'
    value: ${{ steps.set-vars.outputs.checkout_ref }}

runs:
  using: 'composite'
  steps:
    - name: Prepare variables
      id: set-vars
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF: ${{ github.ref }}
        DISPATCH_PUB: ${{ inputs.publish_binaries }}
        DISPATCH_REF: ${{ inputs.ref }}
      run: |
        # BUILD_ALL: true on manual dispatch or any tag
        if [[ "$EVENT_NAME" == "workflow_dispatch" || "$GITHUB_REF" == refs/tags/* ]]; then
          build_all=true
        else
          build_all=false
        fi

        # PUBLISH_BINARIES: only if manual & publish=true, or on any tag
        if [[ ( "$EVENT_NAME" == "workflow_dispatch" && "$DISPATCH_PUB" == "true" ) || "$GITHUB_REF" == refs/tags/* ]]; then
          publish_binaries=true
        else
          publish_binaries=false
        fi

        # CHECKOUT_REF: use manual input if provided, else real ref
        if [[ "$EVENT_NAME" == "workflow_dispatch" && -n "$DISPATCH_REF" ]]; then
          checkout_ref="$DISPATCH_REF"
        else
          checkout_ref="$GITHUB_REF"
        fi
        
        echo "build_all=$build_all"               >> $GITHUB_OUTPUT
        echo "publish_binaries=$publish_binaries" >> $GITHUB_OUTPUT
        echo "checkout_ref=$checkout_ref"         >> $GITHUB_OUTPUT
        
        echo "build_all=$build_all"
        echo "publish_binaries=$publish_binaries"
        echo "checkout_ref=$checkout_ref"
