# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../libs/Makefile.shared-go-libs

test-integration:
	@echo "integration tests not enabled yet" ## Enabled after CVS-165018 is implemented
