name: Change Detection
description: Extends standard change detection by optionally returning all components, supporting full platform rebuilds for periodic runs, manual triggers, or release candidate preparation.

inputs:
  path_filter:
    description: 'Path to the components path-filter file'
    required: true
  get_all:
    description: 'If set to true, returns all components defined in the path filter file, regardless of detected changes'
    type: boolean
    required: true
runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
      with:
        files_yaml_from_source_file: "${{ inputs.path_filter }}"

    - name: Get changed components
      id: components-list
      shell: bash
      env:
        CHANGED_KEYS: ${{ steps.changed-files.outputs.changed_keys }}
      run: |
        if [[ ${{ inputs.get_all }} == "true" ]]; then
          paths=$(yq -r '... comments=""' "${{ inputs.path_filter }}" | yq -r 'keys[]')
          paths_list=$(printf '%s\n' "${paths[@]}" | jq -R . | jq -sc .)
        else
          paths_list=$(python3 -c "print('$CHANGED_KEYS'.split())")
        fi

        echo "::group::paths list"
        echo $paths_list
        echo "::endgroup::"

        echo "paths-list=$paths_list" >> "$GITHUB_OUTPUT"
