---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "migration-job.labels" . | nindent 4 }}
