backend: huggingface
task: SEMANTIC_SEGMENTATION

model:
  class_path: getitune.backend.huggingface.models.semantic_segmentation.HFSemanticSegModel
  init_args:
    checkpoint: nvidia/segformer-b0-finetuned-ade-512-512
    pretrained: true
    input_size:
      - 512
      - 512
    mean:
      - 0.485
      - 0.456
      - 0.406
    std:
      - 0.229
      - 0.224
      - 0.225

engine:
  device: auto

training:
  max_epochs: 100
  batch: 8
  learning_rate: 0.0001
  precision: bf16-mixed
  patience: 10

data: ../_base_/data/semantic_segmentation.yaml

overrides:
  data:
    input_size:
      - 512
      - 512
