"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
INTEL CONFIDENTIAL

Copyright (C) 2024 Intel Corporation

This software and the related documents are Intel copyrighted materials, and
your use of them is governed by the express license under which they were
provided to you ("License"). Unless the License provides otherwise, you may
not use, modify, copy, publish, distribute, disclose or transmit this
software or the related documents without Intel's prior written permission.

This software and the related documents are provided as is, with no express
or implied warranties, other than those that are expressly stated in the
License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MODEL_ALREADY_REGISTERED: _ErrorCode.ValueType  # 0
    UNSUPPORTED_MODEL_TYPE: _ErrorCode.ValueType  # 1
    INVALID_MODEL_ZIP_PACKAGE: _ErrorCode.ValueType  # 2
    INTERNAL_ERROR: _ErrorCode.ValueType  # 3
    NOT_IMPLEMENTED: _ErrorCode.ValueType  # 4

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper): ...

MODEL_ALREADY_REGISTERED: ErrorCode.ValueType  # 0
UNSUPPORTED_MODEL_TYPE: ErrorCode.ValueType  # 1
INVALID_MODEL_ZIP_PACKAGE: ErrorCode.ValueType  # 2
INTERNAL_ERROR: ErrorCode.ValueType  # 3
NOT_IMPLEMENTED: ErrorCode.ValueType  # 4
global___ErrorCode = ErrorCode

@typing.final
class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    code: global___ErrorCode.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        code: global___ErrorCode.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "message", b"message"]) -> None: ...

global___Error = Error

@typing.final
class Model(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    WORKSPACE_ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    MODEL_GROUP_ID_FIELD_NUMBER: builtins.int
    MODEL_ID_FIELD_NUMBER: builtins.int
    OPTIMIZED_MODEL_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    USE_ELLIPSE_FIELD_NUMBER: builtins.int
    organization_id: builtins.str
    workspace_id: builtins.str
    project_id: builtins.str
    model_group_id: builtins.str
    model_id: builtins.str
    optimized_model_id: builtins.str
    task_id: builtins.str
    use_ellipse: builtins.bool
    def __init__(
        self,
        *,
        organization_id: builtins.str = ...,
        workspace_id: builtins.str = ...,
        project_id: builtins.str = ...,
        model_group_id: builtins.str = ...,
        model_id: builtins.str = ...,
        optimized_model_id: builtins.str = ...,
        task_id: builtins.str = ...,
        use_ellipse: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["model_group_id", b"model_group_id", "model_id", b"model_id", "optimized_model_id", b"optimized_model_id", "organization_id", b"organization_id", "project_id", b"project_id", "task_id", b"task_id", "use_ellipse", b"use_ellipse", "workspace_id", b"workspace_id"]) -> None: ...

global___Model = Model

@typing.final
class Connection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_ID_FIELD_NUMBER: builtins.int
    TO_ID_FIELD_NUMBER: builtins.int
    from_id: builtins.str
    to_id: builtins.str
    def __init__(
        self,
        *,
        from_id: builtins.str = ...,
        to_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from_id", b"from_id", "to_id", b"to_id"]) -> None: ...

global___Connection = Connection

@typing.final
class Label(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    IS_ANOMALOUS_FIELD_NUMBER: builtins.int
    IS_EMPTY_FIELD_NUMBER: builtins.int
    GROUP_FIELD_NUMBER: builtins.int
    PARENT_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    is_anomalous: builtins.bool
    is_empty: builtins.bool
    group: builtins.str
    parent_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        is_anomalous: builtins.bool = ...,
        is_empty: builtins.bool = ...,
        group: builtins.str = ...,
        parent_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["group", b"group", "id", b"id", "is_anomalous", b"is_anomalous", "is_empty", b"is_empty", "name", b"name", "parent_id", b"parent_id"]) -> None: ...

global___Label = Label

@typing.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    id: builtins.str
    title: builtins.str
    task_type: builtins.str
    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Label]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        title: builtins.str = ...,
        task_type: builtins.str = ...,
        labels: collections.abc.Iterable[global___Label] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "labels", b"labels", "task_type", b"task_type", "title", b"title"]) -> None: ...

global___Task = Task

@typing.final
class Pipeline(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASKS_FIELD_NUMBER: builtins.int
    CONNECTIONS_FIELD_NUMBER: builtins.int
    @property
    def tasks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Task]: ...
    @property
    def connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Connection]: ...
    def __init__(
        self,
        *,
        tasks: collections.abc.Iterable[global___Task] | None = ...,
        connections: collections.abc.Iterable[global___Connection] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connections", b"connections", "tasks", b"tasks"]) -> None: ...

global___Pipeline = Pipeline

@typing.final
class Project(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PIPELINE_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    @property
    def pipeline(self) -> global___Pipeline: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        pipeline: global___Pipeline | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pipeline", b"pipeline"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name", "pipeline", b"pipeline"]) -> None: ...

global___Project = Project

@typing.final
class RegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    OVERRIDE_FIELD_NUMBER: builtins.int
    name: builtins.str
    override: builtins.bool
    @property
    def project(self) -> global___Project: ...
    @property
    def model(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Model]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        project: global___Project | None = ...,
        model: collections.abc.Iterable[global___Model] | None = ...,
        override: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["model", b"model", "name", b"name", "override", b"override", "project", b"project"]) -> None: ...

global___RegisterRequest = RegisterRequest

@typing.final
class ActiveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___ActiveRequest = ActiveRequest

@typing.final
class DeregisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeregisterRequest = DeregisterRequest

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    status: builtins.str
    @property
    def error(self) -> global___Error: ...
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        error: global___Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_error", b"_error", "error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_error", b"_error", "error", b"error", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...

global___StatusResponse = StatusResponse

@typing.final
class ListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListRequest = ListRequest

@typing.final
class ListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PIPELINES_FIELD_NUMBER: builtins.int
    @property
    def pipelines(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        pipelines: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pipelines", b"pipelines"]) -> None: ...

global___ListResponse = ListResponse

@typing.final
class RecoverRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___RecoverRequest = RecoverRequest

@typing.final
class RecoverResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

global___RecoverResponse = RecoverResponse

@typing.final
class PurgeProjectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_ID_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    def __init__(
        self,
        *,
        project_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["project_id", b"project_id"]) -> None: ...

global___PurgeProjectRequest = PurgeProjectRequest

@typing.final
class PurgeProjectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

global___PurgeProjectResponse = PurgeProjectResponse

@typing.final
class Chunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUFFER_FIELD_NUMBER: builtins.int
    buffer: builtins.bytes
    def __init__(
        self,
        *,
        buffer: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["buffer", b"buffer"]) -> None: ...

global___Chunk = Chunk

@typing.final
class DownloadGraphRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_FIELD_NUMBER: builtins.int
    MODELS_FIELD_NUMBER: builtins.int
    @property
    def project(self) -> global___Project: ...
    @property
    def models(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Model]: ...
    def __init__(
        self,
        *,
        project: global___Project | None = ...,
        models: collections.abc.Iterable[global___Model] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["models", b"models", "project", b"project"]) -> None: ...

global___DownloadGraphRequest = DownloadGraphRequest
