apiVersion: v1
kind: Service
metadata:
  name: {{ include "credit-system.name" . }}
  labels:
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
    {{- include "credit-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.https }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "credit-system.selectorLabels" . | nindent 4 }}
