include ../../Makefile.shared-workflows

build-image:
	@echo "Nothing to do - ${COMPONENT_NAME} does not have an image to build"

push-image:
	@echo "Nothing to do - ${COMPONENT_NAME} does not have an image to push"

test-component: venv
	@echo "test-component not available"
