# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organization_status.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import organization_pb2 as organization__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19organization_status.proto\x12\x13organization_status\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12organization.proto\"X\n\x19OrganizationStatusRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x17\n\x0forganization_id\x18\x02 \x01(\t\x12\x12\n\ncreated_by\x18\x03 \x01(\t\"\x95\x01\n\x1aOrganizationStatusResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x05 \x01(\t\"e\n ListOrganizationStatusesResponse\x12\x41\n\x08statuses\x18\x01 \x03(\x0b\x32/.organization_status.OrganizationStatusResponse2\xef\x01\n\x12OrganizationStatus\x12k\n\x06\x63hange\x12..organization_status.OrganizationStatusRequest\x1a/.organization_status.OrganizationStatusResponse\"\x00\x12l\n\x0cget_statuses\x12#.organization.OrganizationIdRequest\x1a\x35.organization_status.ListOrganizationStatusesResponse\"\x00\x42\"Z geti.com/account_service_grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'organization_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z geti.com/account_service_grpc/pb'
  _globals['_ORGANIZATIONSTATUSREQUEST']._serialized_start=103
  _globals['_ORGANIZATIONSTATUSREQUEST']._serialized_end=191
  _globals['_ORGANIZATIONSTATUSRESPONSE']._serialized_start=194
  _globals['_ORGANIZATIONSTATUSRESPONSE']._serialized_end=343
  _globals['_LISTORGANIZATIONSTATUSESRESPONSE']._serialized_start=345
  _globals['_LISTORGANIZATIONSTATUSESRESPONSE']._serialized_end=446
  _globals['_ORGANIZATIONSTATUS']._serialized_start=449
  _globals['_ORGANIZATIONSTATUS']._serialized_end=688
# @@protoc_insertion_point(module_scope)
