apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace (include "openldap.secretName" .) -}}
  {{- if $previous }}
  username: {{ $previous.data.username }}
  password: {{ $previous.data.password }}
  readonly_username: {{ $previous.data.readonly_username }}
  readonly_password: {{ $previous.data.readonly_password }}
  config_username: {{ $previous.data.config_username }}
  config_password: {{ $previous.data.config_password }}
  {{ else }}
  username: {{ default (randAlpha 6) | b64enc | quote }}
  password: {{ default (randAlphaNum 12) | b64enc | quote }}
  readonly_username: {{ .Values.ldap_readonly_user | default (randAlpha 6) | b64enc | quote }}
  readonly_password: {{ .Values.ldap_readonly_password | default (randAlphaNum 12) | b64enc | quote }}
  config_username: {{ .Values.ldap_config_user | default (randAlpha 6) | b64enc | quote }}
  config_password: {{ .Values.ldap_config_password | default (randAlphaNum 12) | b64enc | quote }}
  {{- end }}
