# See https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-tls-certificate
  namespace: {{ .Release.Namespace }}
spec:
  duration: {{ .Values.tls.ca.duration }}
  renewBefore: {{ .Values.tls.ca.renewBefore }}
  isCA: true
  secretName: {{ .Values.tls.ca.secret_name }}
  commonName: {{ .Values.tls.ca.secret_name }}
  privateKey:
    algorithm: {{ .Values.tls.algorithm }}
    size: {{ .Values.tls.ca.size }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.ca.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Values.tls.ca.secret_name }}
