// Code generated by mockery. DO NOT EDIT.

package service

import (
	image "image"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCropper is an autogenerated mock type for the Cropper type
type MockCropper struct {
	mock.Mock
}

type MockCropper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCropper) EXPECT() *MockCropper_Expecter {
	return &MockCropper_Expecter{mock: &_m.Mock}
}

// CropImage provides a mock function with given fields: reader, tWidth, tHeight
func (_m *MockCropper) CropImage(reader io.Reader, tWidth uint, tHeight uint) (image.Image, error) {
	ret := _m.Called(reader, tWidth, tHeight)

	if len(ret) == 0 {
		panic("no return value specified for CropImage")
	}

	var r0 image.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader, uint, uint) (image.Image, error)); ok {
		return rf(reader, tWidth, tHeight)
	}
	if rf, ok := ret.Get(0).(func(io.Reader, uint, uint) image.Image); ok {
		r0 = rf(reader, tWidth, tHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader, uint, uint) error); ok {
		r1 = rf(reader, tWidth, tHeight)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCropper_CropImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CropImage'
type MockCropper_CropImage_Call struct {
	*mock.Call
}

// CropImage is a helper method to define mock.On call
//   - reader io.Reader
//   - tWidth uint
//   - tHeight uint
func (_e *MockCropper_Expecter) CropImage(reader interface{}, tWidth interface{}, tHeight interface{}) *MockCropper_CropImage_Call {
	return &MockCropper_CropImage_Call{Call: _e.mock.On("CropImage", reader, tWidth, tHeight)}
}

func (_c *MockCropper_CropImage_Call) Run(run func(reader io.Reader, tWidth uint, tHeight uint)) *MockCropper_CropImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockCropper_CropImage_Call) Return(_a0 image.Image, _a1 error) *MockCropper_CropImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCropper_CropImage_Call) RunAndReturn(run func(io.Reader, uint, uint) (image.Image, error)) *MockCropper_CropImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCropper creates a new instance of MockCropper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCropper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCropper {
	mock := &MockCropper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
