---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.enable_local_image_pull_secret }}
imagePullSecrets:
  - name: regcred
{{- end }}
metadata:
  name: weight-uploader
  namespace: {{ .Release.Namespace }}
  labels:
    "app": "weight-uploader"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weight-uploader
  namespace: {{ .Release.Namespace }}
  labels:
    "app": "weight-uploader"
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weight-uploader
  namespace: {{ .Release.Namespace }}
  labels:
    "app": "weight-uploader"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weight-uploader
subjects:
  - kind: ServiceAccount
    name: weight-uploader
    namespace: {{ .Release.Namespace }}
