{{- $configMap := (lookup "v1" "ConfigMap" .Release.Namespace "impt-configuration") }}
{{- $proxy_enabled := index $configMap.data "proxy_enabled" }}
{{- if eq $proxy_enabled "true" }}
{{- $httpProxy := index $configMap.data "http_proxy" }}
{{- $httpsProxy := index $configMap.data "https_proxy" }}
{{- $httpHost := (split ":" ((urlParse $httpProxy).host))._0 }}
{{- $httpsHost := (split ":" ((urlParse $httpsProxy).host))._0 }}
{{- $httpPort := (default "80" ((split ":" ((urlParse $httpProxy).host))._1)) }}
{{- $httpsPort := (default "80" ((split ":" ((urlParse $httpsProxy).host))._1)) }}
{{- $httpProxy := index $configMap.data "http_proxy" }}
{{- $httpsProxy := index $configMap.data "https_proxy" }}
{{- $httpHost := (split ":" ((urlParse $httpProxy).host))._0 }}
{{- $httpsHost := (split ":" ((urlParse $httpsProxy).host))._0 }}
{{- $httpPort := (default "80" ((split ":" ((urlParse $httpProxy).host))._1)) }}
{{- $httpsPort := (default "80" ((split ":" ((urlParse $httpsProxy).host))._1)) }}

{{ if .Capabilities.APIVersions.Has "networking.istio.io/v1/ServiceEntry"}}
apiVersion: networking.istio.io/v1
{{ else }}
apiVersion: networking.istio.io/v1beta1
{{ end }}
kind: ServiceEntry
metadata:
  name: proxy-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $httpHost }}
  {{- if ne $httpHost $httpsHost }}
  - {{ $httpsHost }}
  {{- end }}
  ports:
  - number: {{ $httpPort }}
    name: http-proxy
    protocol: tcp
  {{- if ne $httpPort $httpsPort }}
  - number: {{ $httpsPort }}
    name: https-proxy
    protocol: tcp
  {{- end }}
  resolution: DNS
  location: MESH_EXTERNAL
{{- end }}
