# Copyright (C) 2022-2025 Intel Corporation
# LIMITED EDGE SOFTWARE DISTRIBUTION LICENSE

include ../../../Makefile.shared-python-uv

DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \
						--build-context grpc_interfaces=../../../grpc_interfaces
