{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  {{- if .Values.global.running_on_vm }}
  minReplicas: 1
  maxReplicas: 1
  {{- else }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- end }}
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Chart.Name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ .Chart.Name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
