apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  labels:
    {{- include "jobs-ms.labels" . | nindent 4 }}
    {{- if .Values.global.istio_ambient_mesh }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.ports.grpc }}
      protocol: TCP
  selector:
    {{- include "jobs-ms.selectorLabels" . | nindent 4 }}
