include ../../../Makefile.shared-python

DOCKER_BUILD_CONTEXT := --build-context libs=../../../libs \
						--build-context sc_sdk=../../../interactive_ai/libs/sc_sdk \
						--build-context media_utils=../../../interactive_ai/libs/media_utils \
						--build-context supported_models=../../../interactive_ai/supported_models \
