apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.service.ports.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
