{{- $secretName := printf "%s-%s" .Release.Namespace .Values.kafka.secretName }}
{{- $clientUsers := .Values.kafka.clientUsers }}
{{- if .Values.global.credit_system_enabled }}
  {{- $clientUsers = append $clientUsers .Values.kafka.creditSystemUser }}
{{- end }}
{{- $clientPasswords := .Values.kafka.clientPasswords }}
{{- if not $clientPasswords }}
  {{- $clientPasswords = list }}
{{- range $clientUsers }}
  {{- $clientPasswords = append $clientPasswords (randAlphaNum 10) }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ $previous := lookup "v1" "Secret" .Release.Namespace $secretName }}
  client-users: {{ join "," $clientUsers | b64enc | quote }}
  client-passwords: {{ join "," $clientPasswords | b64enc | quote }}
  system-user-password: {{ index $clientPasswords 0 | b64enc | quote }}
  {{- if $previous }}
  inter-broker-user: {{ index $previous.data "inter-broker-user" }}
  inter-broker-password: {{ index $previous.data "inter-broker-password" }}
  {{ else }}
  inter-broker-user: {{ randAlphaNum 10 | b64enc | quote }}
  inter-broker-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}

{{- range $i, $e := until (len $clientUsers) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}-{{ index $clientUsers $i }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  user: {{ index $clientUsers $i | b64enc | quote }}
  password: {{ index $clientPasswords $i | b64enc | quote }}

{{- if eq (index $clientUsers $i) "flyte" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}-{{ index $clientUsers $i }}
  namespace: {{ include "flyteworkflow.namespace" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  user: {{ index $clientUsers $i | b64enc | quote }}
  password: {{ index $clientPasswords $i | b64enc | quote }}
{{- end }}

{{- end }}
