---
enabled:
  dcgm-exporter: true
  dex: true
  etcd: true
  kafka-provisioning: true
  kafka-proxy: true
  kafka: true
  mongodb: true
  opa: true
  openldap: true
  opentelemetry-collector: true
  postgresql: true
  seaweed-fs: true
  spice-db: true
  xpu-manager: true

global:
  istio_ambient_mesh: false
  istio_gateway_name: "istio-gateway"
  istio_ingress_namespace: "istio-system"
  ldap_service_user_secret_name: "impt-ldap-service-user"
  credit_system_enabled: false
  enable_local_image_pull_secret: false
  tag: 2.10.1
  docker_namespace: geti
  security_headers: |
    X-Frame-Options: "DENY"
    Content-Security-Policy: "frame-ancestors 'none'; default-src 'self'; media-src 'self' https://docs.geti.intel.com/on-prem/2.6/; connect-src 'self' data: https://consumerdev.intel.com/ https://login.microsoftonline.com/; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' blob:; img-src 'self' data:; frame-src 'none'; object-src 'none'; form-action 'self'; worker-src 'self' blob:"
    cross-origin-embedder-policy: require-corp
    cross-origin-opener-policy: same-origin
    X-Content-Type-Options: "nosniff"
  stripped_headers: |
    - "X-Envoy-Decorator-Operation"
  cors_policy:
    enabled: true
    allowed_origins:
      - exact: "https://docs.geti.intel.com"
    allowed_headers:
      - Authorization
      - Content-Type
      - tus-resumable
      - upload-length
      - upload-length
      - x-geti-csrf-protection
      - cookie
      - x-api-key
    allowed_methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
    max_age: 86400s
    allow_credentials: true

opentelemetry-collector:
  config:
    receivers:
      k8s_events:
        namespaces:
        - "impt"
        - "opa-istio"
        - "istio-system"
