name: Components workflow

on:
  workflow_call:
    inputs:
      component-dir:
        description: "Dir in root directory"
        type: string
        required: true
      image-tag:
        description: "Docker image tag"
        type: string
        required: true
    secrets:
      AWS_ROLE:
        required: true
      AWS_REGION:
        required: true
      REGISTRY:
        required: true
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to checkout"
        required: true
        default: "main"
      component-dir:
        description: "Path to the component (relative to the root of the repository)"
        required: true

permissions: {} # No permissions by default on workflow level

env:
  COMPONENT_DIR: ${{ inputs.component-dir }}

jobs:
  component-check:
    name: Component workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 30
    env:
      TAG: ${{ inputs.image-tag || github.sha }}
      REGISTRY: ${{ secrets.REGISTRY }}
      PYTHON_BUILDER_IMAGE: builder-images/python-builder:v0.1
      GO_BUILDER_IMAGE: builder-images/go-builder:v0.1
    steps:
      - name: Free space on runner (delete unnecessary tools)
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.branch || '' }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: Github
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Check if Python/Go project
        id: check-python-go
        run: |
          if [ -f "${COMPONENT_DIR}/setup.py" ] || [ -f "${COMPONENT_DIR}/pyproject.toml" ]; then
            echo "BUILDER_IMAGE=${REGISTRY}/${PYTHON_BUILDER_IMAGE}" >> $GITHUB_ENV
          elif [ -f "${COMPONENT_DIR}/go.mod" ]; then
            echo "BUILDER_IMAGE=${REGISTRY}/${GO_BUILDER_IMAGE}" >> $GITHUB_ENV
          else
            echo "BUILDER_IMAGE=builder_image_not_set" >> $GITHUB_ENV
          fi

      - name: Static code analysis
        run: make builder -C "${COMPONENT_DIR}" static-code-analysis

      - name: Unit testing
        run: make builder -C "${COMPONENT_DIR}" test-unit

      - name: Integration testing
        run: |
          if [[ "${COMPONENT_DIR}" == "interactive_ai/workflows/geti_domain/project_ie" ]]; then
            make -C "${COMPONENT_DIR}" test-integration
          else
            make builder -C "${COMPONENT_DIR}" test-integration
          fi

      - name: Build image
        id: build-image
        run: |
          OUTPUT=$(make -C "${COMPONENT_DIR}" build-image)
          if echo "$OUTPUT" | grep -q "Skipping"; then
            echo "SKIP_IMAGE=true" >> $GITHUB_OUTPUT
          fi

      - name: Push image
        if: steps.build-image.outputs.SKIP_IMAGE != 'true'
        run: make -C "${COMPONENT_DIR}" push-image

      - name: Lint chart
        if: steps.build-image.outputs.SKIP_IMAGE != 'true'
        run: make -C "${COMPONENT_DIR}" lint-chart

      - name: Publish chart
        if: steps.build-image.outputs.SKIP_IMAGE != 'true'
        run: make -C "${COMPONENT_DIR}" publish-chart
