name: Run daily e2e tests
run-name: Run daily e2e tests
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      geti_host:
        type: string
        required: true
        description: Address of the Geti host where to run the tests (e.g. "https://10.20.30.40")
      playwright_tag:
        type: string
        required: false
        description: Run a subset of the UI tests (Playwright) defined by the tag. Defaults to "@daily"
      bdd_tag:
        type: string
        required: false
        description: Run a subset of the backend tests (BDD) defined by the tag. Defaults to "@smoke". Pass "all" to run all tests
      bdd_feature:
        type: string
        required: false
        description: Run a subset of tests defined by a feature. Defaults to all features
      disable_playwright:
        type: boolean
        required: true
        default: false
        description: Disable Playwright tests
      disable_bdd:
        type: boolean
        required: true
        default: false
        description: Disable BDD tests

jobs:
  run-daily-e2e-microservices-tests:
    if: "${{ ! inputs.disable_bdd && ! cancelled() }}"
    uses: ./.github/workflows/bdd-e2e.yml
    secrets: inherit
    with:
      geti_host: ${{ inputs.geti_host || 'https://10.211.120.131' }}
      tag: ${{ inputs.bdd_tag || '@smoke' }}
      feature: ${{ inputs.bdd_feature }}
