name: "Pull Request Labeler"
on:
  # The labeler doesn't checkout/execute any contributed code, so it should be safe.
  - pull_request_target # zizmor: ignore[dangerous-triggers]

permissions: {} # No permissions by default on workflow level

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
