name: Libraries - tests and stylechecks

on:
  workflow_call:
    inputs:
      component-dir:
        description: 'Dir in root directory'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'
      component-dir:
        description: 'Path to the component (relative to the root of the repository)'
        required: true

permissions: {} # No permissions by default on workflow level

env:
  COMPONENT_DIR: ${{ inputs.component-dir  }}

jobs:
  component-tests:
    name: Component workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.branch || '' }}

      - name: Install missing dependencies
        run: |
          sudo -E apt update
          sudo -E apt install -y ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1

      - name: Setup GO
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: '1.23'

      - name: Static code analysis
        run: make -C "${COMPONENT_DIR}" static-code-analysis

      - name: Tests
        run: make -C "${COMPONENT_DIR}" tests
