name: Renovate
on:
  schedule:
    # on Wednesday and Sunday
    - cron: "37 3 * * 3,0"

  # allow to manually trigger this workflow
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run Renovate in dry-run mode (no PR)"
        required: false
        default: false
        type: boolean

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Get token
        id: get-github-app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f5c3383cb7cbf7711d8b66b809375b2d5f4e2d1d # v42.0.2
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.get-github-app-token.outputs.token }}"
        env:
          LOG_LEVEL: ${{ github.event_name == 'workflow_dispatch' && 'debug' || 'info' }}
          # Dry run if the event is workflow_dispatch AND the dry-run input is true
          RENOVATE_DRY_RUN: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true') && 'full' || null }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
