# Renovate configuration validator
#
# This workflow validates changes proposed into Renovate configuration file
# (.github/renovate.json5) and prevents non-valid configuration to be used by Renovate.
#
# Required Secrets:
# - None
#
# Automatically triggered on:
# - Pull requests to .github/renovate.json5.
#

name: Validate Renovate configuration

on:
  pull_request:
    paths:
      - ".github/renovate.json5"

permissions: {} # No permissions by default

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout configuration
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:44.14.3@sha256:b6bcb741cbdd5e3675f9903a639ba43a74eb9665a0b850ac018acf0b32b59c11
          docker run --rm --entrypoint "renovate-config-validator" \
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
          ${RENOVATE_IMAGE} "/renovate.json5"
