name: Security Scans

on:
  schedule:
    # Run security checks every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - release**

permissions: {}

jobs:
  zizmor-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/anomalib/.github/actions/security/zizmor@6e3a6594a1d8867c045bb032e6c10f8673ff025a
        with:
          scan-scope: "all"
          severity-level: "LOW"
          confidence-level: "LOW"
          fail-on-findings: false # reports only

  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Bandit scan
        uses: open-edge-platform/anomalib/.github/actions/security/bandit@6e3a6594a1d8867c045bb032e6c10f8673ff025a
        with:
          scan-scope: "all"
          severity-level: "LOW"
          confidence-level: "LOW"
          config_file: ".github/bandit_config.yml"
          fail-on-findings: false # reports only

  # TODO: unify approach and migrate to reusable workflows/composite actions
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Trivy vulnerability scanner in config mode
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          scan-type: "config"
          scan-ref: "."
          format: sarif
          trivy-config: ".github/trivy_config.yml"
          output: "trivy-results.sarif"
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: "trivy-results.sarif"
