name: Web UI checks

on:
  workflow_call:
    inputs:
      image-tag:
        description: "Docker image tag"
        type: string
        required: true
      push:
        description: "Enable pushing Docker images and Helm charts"
        type:  boolean
        default: false
      ref:
        description: 'The branch, tag or SHA to checkout'
        type: string
        default: ""
    secrets:
      AWS_ROLE:
        required: true
      AWS_REGION:
        required: true
      REGISTRY:
        required: true

permissions: {} # No permissions by default on workflow level

jobs:
  build:
    name: Build UI
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        id: setup-node
        with:
          node-version-file: web_ui/.nvmrc

      - name: Install dependencies
        working-directory: "web_ui"
        run: npm ci

      - name: Build UI
        working-directory: "web_ui"
        run: npm run build:all-routes

      - name: Compress build
        working-directory: "web_ui"
        run: tar -czf build.tar.gz build

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: webui-build
          path: "web_ui/build.tar.gz"

  lint:
    name: Eslint checks
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        id: setup-node
        with:
          node-version-file: web_ui/.nvmrc

      - name: Install dependencies
        working-directory: "web_ui"
        run: npm ci

      - name: Prettier
        working-directory: "web_ui"
        run: npm run format:check

      - name: Eslint
        working-directory: "web_ui"
        run: npm run lint

      - name: Eslint cyclic imports
        working-directory: "web_ui"
        run: npm run cyclic-deps-check

      - name: Typescript
        working-directory: "web_ui"
        run: npm run type-check

  unit-tests:
    name: Jest tests (${{ matrix.shard }}/${{ matrix.shardTotal }})
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        shardTotal: [5]
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        id: setup-node
        with:
          node-version-file: web_ui/.nvmrc

      - name: Install dependencies
        working-directory: "web_ui"
        run: npm ci

      - name: UI Unit tests
        working-directory: "web_ui"
        run: npm run test:unit -- --silent --maxWorkers=2 --shard=${{ matrix.shard }}/${{ matrix.shardTotal }}

  playwright-tests:
    name: Playwright Tests (${{ matrix.shard }}/${{ matrix.shardTotal }})
    needs: build
    permissions:
      contents: read # to checkout code
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        shardTotal: [5]
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        id: setup-node
        with:
          node-version-file: web_ui/.nvmrc

      - name: Install dependencies
        working-directory: "web_ui"
        run: npm ci

      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: webui-build
          path: "web_ui"

      - name: Unpack build
        working-directory: "web_ui"
        run: tar -xzf build.tar.gz

      - name: Run Playwright tests
        working-directory: "web_ui"
        run: npm run test:component -- --project "chromium" --project "chromium mini viewport" --shard=${{ matrix.shard }}/${{ matrix.shardTotal }}

      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: always()
        with:
          name: playwright-blob-reports-${{ matrix.shard }}
          path: web_ui/blob-report
          retention-days: 1

  merge-playwright-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: always()
    needs: [playwright-tests]
    permissions:
      contents: read # to checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || '' }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        id: setup-node
        with:
          node-version-file: web_ui/.nvmrc

      - name: Install dependencies
        working-directory: "web_ui"
        run: npm ci

      - name: Download playwright blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          pattern: playwright-blob-reports-*
          path: web_ui/playwright-blob-reports
          merge-multiple: true

      - name: Merge into HTML Report
        working-directory: "web_ui"
        run: npx playwright merge-reports --reporter html ./playwright-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: playwright-html-report-attempt-${{ github.run_attempt }}
          path: web_ui/playwright-report
          retention-days: 14

  component-workflow:
    name: Component workflow
    needs: [lint, unit-tests, merge-playwright-reports]
    permissions:
      contents: read # to checkout code
      id-token: write # is required by nested component-check
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REGISTRY: ${{ secrets.REGISTRY }}
    uses: ./.github/workflows/component.yml
    with:
      image-tag: ${{ inputs.image-tag }}
      component-dir: web_ui
      push: ${{ inputs.push }}
