{{- if eq (default "standard" .Values.global.installation_profile) "standard" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "observability.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "observability.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "observability.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- end }}