{{- if .Values.global.install_telemetry_stack }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "observability.name" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - events
  - services
  - replicationcontrollers
  - configmaps
  - nodes
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
  {{- end }}