---
{{- if not .Values.global.istio_ambient_mesh }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "observability.name" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.global.istio_ingress_namespace }}/{{ .Values.global.istio_gateway_name }}
  http:
  - match:
    - uri:
        prefix: "/api/v1/logs"
    rewrite:
      uri: "/api/v1/logs/"
    {{- if $.Values.global.cors_policy.enabled }}
    corsPolicy:
      allowHeaders: {{- include "observability.appendToArray" (dict "sourceArray" $.Values.global.cors_policy.allowed_headers) | indent 6 }}
      allowOrigins: {{- include "observability.formatKeyValuePair" (dict "sourceDict" $.Values.global.cors_policy.allowed_origins) | indent 6 }}
      allowMethods: {{- include "observability.appendToArray" (dict "sourceArray" $.Values.global.cors_policy.allowed_methods) | indent 6 }}
      maxAge: {{ .Values.global.cors_policy.max_age | quote }}
      allowCredentials: {{ .Values.global.cors_policy.allow_credentials }}
    {{- end }}
    headers:
      response:
        set:
          Cache-Control: "no-cache, no-store, max-age=0, must-revalidate"
{{ .Values.global.security_headers | indent 10 }}
        remove:
{{ .Values.global.stripped_headers | indent 8 }}
    timeout: 360s
    route:
    - destination:
        host: {{ include "observability.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.port }}
{{- end }}
